<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
<HEAD>
	<TITLE>Millsberry - Game</TITLE>
  <LINK REL="stylesheet" TYPE="text/css" HREF="http://www.millsberry.com/styles.css">
  </HEAD>
<BODY LEFTMARGIN=0 TOPMARGIN=0 MARGINWIDTH=0 MARGINHEIGHT=0 BACKGROUND='http://www.millsberry.com/images/site_gfx/tile_mill.gif'>
<TABLE BORDER="0" HEIGHT="100%" WIDTH="100%" ALIGN="LEFT" CELLSPACING="0" CELLPADDING="0">
  <TR>
    <TD ROWSPAN='2'><A HREF='http://www.millsberry.com'><IMG SRC="http://www.millsberry.com/images/site_gfx/logo.gif" onMouseOut="src='http://www.millsberry.com/images/site_gfx/logo.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/logo_over.gif';" BORDER="0" ALT="Back to MAIN"></A></TD>
    <TD WIDTH="650" HEIGHT="55" VALIGN="TOP" BGCOLOR='#000000'>
      <TABLE BORDER='0' CELLPADDING='0' CELLSPACING='0'>
        <TR>
          <TD>
            <A HREF="http://www.millsberry.com/home/"><IMG SRC="http://www.millsberry.com/images/site_gfx/visit_home.gif" BORDER="0" ALT="Visit your Home!" onMouseOut="src='http://www.millsberry.com/images/site_gfx/visit_home.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/visit_home_over.gif';"></A>
          </TD>
          <TD>
            <A HREF="http://www.millsberry.com/main_map.phtml?location=downtown"><IMG SRC="http://www.millsberry.com/images/site_gfx/visit_shopping.gif" BORDER="0" ALT="Visit the Town Center!" onMouseOut="src='http://www.millsberry.com/images/site_gfx/visit_shopping.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/visit_shopping_over.gif';"></A>
          </TD>
          <TD>
            <A HREF="http://www.millsberry.com/gamepages/hiscores.phtml"><IMG SRC="http://www.millsberry.com/images/site_gfx/visit_hi_scores.gif" BORDER="0" ALT="Visit the Hi Scores!" onMouseOut="src='http://www.millsberry.com/images/site_gfx/visit_hi_scores.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/visit_hi_scores_over.gif';"></A>
          </TD>
          <TD>
            <A HREF="http://www.millsberry.com/town_hall/faq.phtml"><IMG SRC="http://www.millsberry.com/images/site_gfx/visit_faq.gif" BORDER="0" ALT="Visit the Help Pages!" onMouseOut="src='http://www.millsberry.com/images/site_gfx/visit_faq.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/visit_faq_over.gif';"></A>
          </TD>
        </TR>
        <FORM NAME='login' ACTION='http://www.millsberry.com/index.phtml' method='post'>
        <TR>
          <TD COLSPAN='4' VALIGN='bottom'>
            <FONT COLOR="#FFFFFF">
              <B>
                &nbsp;&nbsp;&nbsp;
                Username
                       <input type='text' name='login_username' SIZE='10'>
                       Password
                       <input type='password' name='login_pass' SIZE='10'>&nbsp;
                       <input type='image' src='http://www.millsberry.com/images/site_gfx/visit_log_in.gif' HEIGHT=20 name='login' value='go' border='0' align='top' onMouseOut="src='http://www.millsberry.com/images/site_gfx/visit_log_in.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/visit_log_in_over.gif';"> <A HREF='http://www.millsberry.com/town_hall/support.phtml?q=pw'><FONT COLOR='#FFFFFF' class='smallfont'>[ forgot your password? ]</FONT></A>              </B>
            </FONT>
          </TD>
        </TR>
        </FORM>
      </TABLE>
    </TD>
    <TD WIDTH="100%" BGCOLOR='#000000' COLSPAN='2'>
      
    </TD>
  </TR>
  <FORM NAME='search' ACTION='http://www.millsberry.com/site_search.phtml' method='get'>
  <TR>
    <TD COLSPAN='3' WIDTH="600" HEIGHT="25" VALIGN="TOP" ALIGN="LEFT" CLASS="header_stripe_TD"><TABLE WIDTH='100%' BORDER='0' CELLPADDING='0' CELLSPACING='0'><TR><TD><IMG SRC='http://www.millsberry.com/images/site_gfx/header_stripe.gif'><IMG SRC='http://www.millsberry.com/images/site_gfx/slice_11.gif'></TD><TD ALIGN='RIGHT' CLASS='header_stripe_TD'>Search:<INPUT TYPE='text' NAME='search'></TD><TD><input type='image' src='http://www.millsberry.com/images/site_gfx/visit_go.gif' HEIGHT='25' name='login' border='0' align='top' onMouseOut="src='http://www.millsberry.com/images/site_gfx/visit_go.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/visit_go_over.gif';" CLASS='checkbox'></TD></TR></TABLE></TD>
  </TR>
  </FORM>
  <TR>
    <TD WIDTH="150" VALIGN="TOP" HEIGHT="100%" CLASS="sidenav_TD" background="http://www.millsberry.com/images/site_gfx/left_side_nav_stripe.gif">
          <TABLE BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH='100%'>
        <TR>
          <TD ALIGN='CENTER' VALIGN='TOP'>
              <A HREF='http://www.millsberry.com/main_map.phtml'><IMG SRC='http://www.millsberry.com/images/site_gfx/mapbutton.gif' onMouseDown="src='http://www.millsberry.com/images/site_gfx/mapbutton_down.gif';" onMouseOut="src='http://www.millsberry.com/images/site_gfx/mapbutton.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/mapbutton_over.gif';" BORDER='0'></A><BR><A HREF='http://www.millsberry.com/gamepages/games_list.phtml'><IMG SRC='http://www.millsberry.com/images/site_gfx/gamesbutton.gif' onMouseDown="src='http://www.millsberry.com/images/site_gfx/gamesbutton_down.gif';" onMouseOut="src='http://www.millsberry.com/images/site_gfx/gamesbutton.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/gamesbutton_over.gif';" BORDER='0'></A><BR><A HREF='http://www.millsberry.com/signup.phtml'><IMG SRC='http://www.millsberry.com/images/site_gfx/prebuddy.gif' BORDER='1'></A><BR>
  <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" width="150" height="70">
  <param name="allowScriptAccess" value="sameDomain" />
  <param name=movie value="http://www.millsberry.com/images/site_gfx/sideNavButton_v1.swf?sideNavButtonXML=<button><name>sideNavButton_mc</name><label><text>%3CP%20ALIGN%3D%22CENTER%22%3E%3CFONT%20SIZE%3D%2215%22%3E%3CP%3E%26nbsp%3B%3C%2FP%3E%3C%2FFONT%3E%3CFONT%20SIZE%3D%2228%22%20COLOR%3D%22%23FFFFFF%22%3ESign%20Up%21%21%3C%2FFONT%3E%3C%2FP%3E</text><dropShadow><x>3</x><y>3</y><colorTransform>0,0,0,0,0,0,50,0</colorTransform></dropShadow></label><url>http%3A%2F%2Fwww.millsberry.com%2Fsignup.phtml</url><target>_self</target></button>">
  <param name=quality value=high>
  <param name=menu value=false>
  <param name="wmode" value="transparent" />
  <param name=scale value=noscale>
  <param name="salign" value="lt" />
  <embed src="http://www.millsberry.com/images/site_gfx/sideNavButton_v1.swf?sideNavButtonXML=<button><name>sideNavButton_mc</name><label><text>%3CP%20ALIGN%3D%22CENTER%22%3E%3CFONT%20SIZE%3D%2215%22%3E%3CP%3E%26nbsp%3B%3C%2FP%3E%3C%2FFONT%3E%3CFONT%20SIZE%3D%2228%22%20COLOR%3D%22%23FFFFFF%22%3ESign%20Up%21%21%3C%2FFONT%3E%3C%2FP%3E</text><dropShadow><x>3</x><y>3</y><colorTransform>0,0,0,0,0,0,50,0</colorTransform></dropShadow></label><url>http%3A%2F%2Fwww.millsberry.com%2Fsignup.phtml</url><target>_self</target></button>" quality="high" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" scale="exactfit" width="150" height="70" wmode="transparent">
  </embed>
  </object>          </TD>
        </TR>
      </TABLE>    </TD>
    <TD WIDTH="650" HEIGHT="100%" VALIGN="TOP" ALIGN='LEFT'><TABLE BORDER='0' CELLPADDING='0' CELLSPACING='0'>
           <TR>
             <TD BGCOLOR='#EFEFEF'>
               <b>You are not logged in. A lot of the site's content won't be available to you unless you are logged in. To login, enter your username in the top left box. You can still play games if you aren't a member, but you won't earn any Millsbucks... so <a href=http://www.millsberry.com/signup.phtml>SIGN UP NOW!</A>
             </TD>
           </TR>
         </TABLE>
  <script name='JavaScript'>
  <!--
  var game_win = null;
  
  function opengamewin_16( ) {
  
  if (game_win) { game_win.close();}
  
    // Quality
    if ( document.qualform_16 != null ) {
      with ( document.qualform_16 ) {
      quality = quality_select_16.options[quality_select_16.selectedIndex].value;
    }
  } else {
    quality = "high";
  }
  
  // Size
  var width = 580;
  var height = 380;
  if ( document.sizeform_16 != null ) {
    with ( document.sizeform_16 ) {
      str = size_select_16.options[size_select_16.selectedIndex].value;
      var tmparr = str.split("-");
      width = tmparr[0];
      height = tmparr[1];
    }
  }
  var sizestr = "width=" + width + ", height=" + height;
  if ( width == 999 ) sizestr = "scrolling=no,scroll=no,scrollbars=no,resizable=no,toolbar=no,fullscreen=yes";
  
  game_win = window.open('../gamingsystem/launch_game.phtml?hiscore=0&sp=0&va=&world=&height=380&width=580&r=9470212&game_id=16&questionSet=&quality=' + quality, 'newwin_16', '' +sizestr + '' );
game_win.focus();      return false;
  
    }
  
  //-->
  </script>
  
  <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" width="600" height="400" id="item_loader" align="middle">
<param name="allowScriptAccess" value="sameDomain" />
<param name="movie" value="http://www.millsberry.com/images/item_loader_v3.swf?itemLoaderXML=<?xml version='1.0' ?><message success='1' text = ''><item><frame>1</frame><objectName>item</objectName><url>http%3A%2F%2Fwww.millsberry.com%2Fgamepages%2Fimages%2Finterior_16_v3.swf</url></item><button><objectName>button</objectName><url>javascript%3Avar%20x%3Dopengamewin_16%28%29%3B</url><window>_self</window><useBorderAsRollover>1</useBorderAsRollover></button><border><objectName>border</objectName><lineColor>0x000099</lineColor><size>4</size></border><preloader><objectName>preloader</objectName><width>600</width><height>400</height></preloader></message>"/>
<param name="loop" value="false" />
<param name="menu" value="true" />
<param name="quality" value="high" />
<param name="wmode" value="transparent" />
<param name="devicefont" value="true" />
<param name="bgcolor" value="#666666" />
<embed src="http://www.millsberry.com/images/item_loader_v3.swf?itemLoaderXML=<?xml version='1.0' ?><message success='1' text = ''><item><frame>1</frame><objectName>item</objectName><url>http%3A%2F%2Fwww.millsberry.com%2Fgamepages%2Fimages%2Finterior_16_v3.swf</url></item><button><objectName>button</objectName><url>javascript%3Avar%20x%3Dopengamewin_16%28%29%3B</url><window>_self</window><useBorderAsRollover>1</useBorderAsRollover></button><border><objectName>border</objectName><lineColor>0x000099</lineColor><size>4</size></border><preloader><objectName>preloader</objectName><width>600</width><height>400</height></preloader></message>" width="600" height="400" wmode="transparent"/>
</object>
<table border=0 bordercolor=black width=600 cellpadding=4 cellspacing=0><tr><td valign=middle align=center colspan=2 CLASS='header_stripe_TD'><A HREF='javascript:var x=opengamewin_16();'><IMG SRC='http://www.millsberry.com/images/site_gfx/playbutton.gif' onMouseDown="src='http://www.millsberry.com/images/site_gfx/playbutton_down.gif';" onMouseOut="src='http://www.millsberry.com/images/site_gfx/playbutton.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/playbutton_over.gif';" BORDER='0'></A></td><td align=center CLASS='header_stripe_TD'><table border=0 cellpadding=0 cellspacing=0><form name='qualform_16'><tr>
                 <td align=center><b>Select Quality</b><br><select name='quality_select_16'><option selected value='High'>High<option value='Medium'>Medium<option value='Low'>Low</select></td>
                </tr></form></table></td><td align=center CLASS='header_stripe_TD'><table border=0 cellpadding=0 cellspacing=0><form name='sizeform_16'><tr>
                <td align=center><b>Select Size</b>
                  <br>


                   <select name='size_select_16'>
<option value='464-304'>Small (640x480)
<option value='580-380' selected>Normal (800x600)
<option value='812-532'>Large (1024x768)
<option value='1044-684'>X-Large (1600x1200)
</select>

</td></tr></form></table></td></tr><tr bgcolor=#cccccc><td align=center>Your Scores<br>Sent Today:<br> 0</td><td align=center>Total Scores<br>Sent Today:<br>367</td><td align=center>
            <a href=hiscores.phtml?get=all&game_id=16><b>All Hi Scores</b></a>
            <br>Your Hi Score:
            <br> 0</td><td align=center>100 MB per 100 points
             <BR>
             (1000 maximum per game)
           </td></tr><tr bgcolor=whitesmoke>
          <td colspan=4>
            <b>
              Millsberry&#039;s Match Wanted
            </b> <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" width="30" height="20" id="item_loader" align="middle">
<param name="allowScriptAccess" value="sameDomain" />
<param name="movie" value="http://www.millsberry.com/images/item_loader_v3.swf?itemLoaderXML=<?xml version='1.0' ?><message success='1' text = ''><item><frame>1</frame><objectName>item</objectName><url>http%3A%2F%2Fwww.millsberry.com%2Fimages%2Fsite_gfx%2Fstat_icon_civics_v1.swf</url><scale>50</scale><_x>0</_x><_y>0</_y></item><preloader><objectName>preloader</objectName><width>30</width><height>20</height></preloader></message>"/>
<param name="loop" value="false" />
<param name="menu" value="true" />
<param name="quality" value="high" />
<param name="wmode" value="transparent" />
<param name="devicefont" value="true" />
<param name="bgcolor" value="#666666" />
<embed src="http://www.millsberry.com/images/item_loader_v3.swf?itemLoaderXML=<?xml version='1.0' ?><message success='1' text = ''><item><frame>1</frame><objectName>item</objectName><url>http%3A%2F%2Fwww.millsberry.com%2Fimages%2Fsite_gfx%2Fstat_icon_civics_v1.swf</url><scale>50</scale><_x>0</_x><_y>0</_y></item><preloader><objectName>preloader</objectName><width>30</width><height>20</height></preloader></message>" width="30" height="20" wmode="transparent"/>
</object>

          </td>
         </tr><tr bgcolor=white>
          <td colspan=4>
            Bandits are making off with the townspeople's money! Put them behind bars and recover the cash!<p>  The scoreboard will show you what piece is next. Click on the game board where you want to place the piece. You must match 4 or more of the same color money bag to reclaim it from the bandits. Match 4 or more of the same bandits to clear them from the game board. To clear the level, clear the game area of bandits. Your game ends when you have no more spaces to put a bandit on. 
<p>
*Tip: You can match bags of money AND bandits if they are of the same color.
<p>
You get 3 bombs, which will clear the screen in a 3x3 pattern wherever you place it. To cancel a bomb, click on the bomb icon on the scoreboard again.

          </td>
         </tr></table></TD>
        <TD WIDTH='150' VALIGN='TOP' ALIGN='CENTER' HEIGHT='100%'>          </TD>
          <TD WIDTH='100%'>
            &nbsp;
          </TD>
  </TR>
  <TR>
    <TD COLSPAN="4" WIDTH="100%" ALIGN="CENTER" CLASS="footer_TD">
      <SPAN CLASS='footerfont'>
      MILLSBERRY, characters, logos, product names and all related indicia are trademarks of Mills Online, Inc., © 2004.<BR> ® denotes Reg. US Pat. & TM Office. All rights reserved.
        <BR>
        Use of this site signifies your acceptance of the <A HREF='http://www.millsberry.com/town_hall/terms.phtml'>Terms and Conditions</A>.
        <BR>
        Please view our <A HREF='http://www.millsberry.com/town_hall/policy.phtml'>Privacy Policy</A>.      </SPAN>
    </TD>
</TABLE>
</BODY>
</HTML>
