<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- www.millsberry.com -->
<html>
<head>


    <meta http-equiv="imagetoolbar" content="no">
    <meta name="keywords" content="Mills,Millsbury,Milsberry,Milsbury,Millberry,Millbury,Fun games,Spanish language games,Educational games,Active games,Citizen,Cool stuff,Arcade,Music Mix,Fun,Games,Explore,Adventure,Create,Character,Buddy,Care,Academy,School,Gym,Gymnasium,Solver,Science,Project,Town,Pets,Children's games,Games for kid,Kid games,Kids games,Kid's games,Children,Safe gaming">
    <title>Millsberry - High Scores</title>
    <script type="text/javascript" src="/common.js?v=2"></script>
    <script type="text/javascript" src="/js/swfobject.js"></script>

    <link rel="stylesheet" type="text/css" href="/css/theme/royal.css?v=2">
    <link rel="stylesheet" type="text/css" href="/css/template.css?v=5">
    <link rel="stylesheet" type="text/css" href="/css/global.css?v=2">
    <link rel="stylesheet" type="text/css" href="/css/gamepages/hiscores.css?v=1">

    <!--[if lt IE 7.00]>
        <link rel="stylesheet" type="text/css" href="/css/template.ie.css?v=1">
        <link rel="stylesheet" type="text/css" href="/css/global.ie.css?v=1">
        <![endif]-->

</head>
</head>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<body>



<script src="http://www.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript"> _uacct = "UA-1272972-1"; urchinTracker();</script>
<div id='top'>
    <a href='/'><span id='logo'>&nbsp;</span></a>
    <div id='layout_head'>
       <div id='login_info'>
           3,219 citizens online now&nbsp;|&nbsp; <a href='/town_hall/faq.phtml'>HELP</a>
       </div> <!--login_info-->
       <div id='stripe'>
                <div id="top_nav_flashcontent">
     <!--default content-->
	 </div>

	<script type="text/javascript">
		// <![CDATA[
        
        // redirect to the upgrade page if flash is installed, but version is too low
		var version = deconcept.SWFObjectUtil.getPlayerVersion();
        if(version["major"] < 8 && version["major"] > 0) {
            window.location='/flash.phtml';
        } else {
            writeFlashContent();
        }
        
        function writeFlashContent() {
            var so = new SWFObject("http://graphics.millsberry.com/template/top_nav.swf?url=http%3A%2F%2Fwww.millsberry.com%2Ftop_nav_xml.phtml", "top_nav", "750", "36", "8");
            so.addParam("wmode", "transparent");
            so.addParam("scale", "noscale");
            so.addParam("AllowScriptAccess", "always");
            so.useExpressInstall('http://graphics.millsberry.com/expressinstall.swf');
            so.write("top_nav_flashcontent");
        }
		
		// ]]>
	</script>
 
       </div> <!-- stripe -->
    </div> <!-- layout_head -->
</div> <!-- top -->
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='body'>
<div id='layout_body'>
<div id='side_nav'>
<script type='text/javascript'>flash_object ('http://graphics.millsberry.com/template/side_nav_v1.swf', '150', '1250', '&url=http%3A%2F%2Fwww.millsberry.com%2Fside_nav_xml.phtml%3Fpage_relative_url%3D%252Fgamepages%252Fhiscores.phtml%253Fgame_id%253D511%26login_status%3D0%26now%3D1243381891&unixTimeStamp=1243381891&serverTimeOffset=28800', '8', 'noscale', 'transparent');</script></div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='main'>

<div id='interior'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/game_interiors/interior_511_v1.swf', '600', '400', '&unixTimeStamp=1243381891&serverTimeOffset=28800', '7', 'noscale', 'transparent');</script></div>
<div id='interior_stripe'>High Scores : <a href='flashgame_ctp.phtml?game_id=511'>Honey Nut Cheerios&reg;: Save the Honey</a></div>
<div id='content'>

<table id='high_scores' width='100%' border='0' cellpadding='5' cellspacing='0'>
<tr>
<td class='high_score_header' width='10%' align='center' bgcolor='silver'>Rank</td>
<td class='high_score_header' align='center' bgcolor='silver'>Username</td>
<td class='high_score_header' align='center' bgcolor='silver'>Date</td>
<td class='high_score_header' width='20%' align='center' bgcolor='silver'>Score</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>1</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=masterd365'>masterd365</a></td>
<td align='center' bgcolor='#EEEEEE'>05/23/2009</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>13,870</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>2</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=idanyse'>idanyse</a></td>
<td align='center' bgcolor='#FFFFFF'>05/25/2009</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>13,774</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>3</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=sweetmaxy'>sweetmaxy</a></td>
<td align='center' bgcolor='#EEEEEE'>05/24/2009</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>13,632</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>4</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=bellows52'>bellows52</a></td>
<td align='center' bgcolor='#FFFFFF'>05/22/2009</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>13,585</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>5</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=bush3'>bush3</a></td>
<td align='center' bgcolor='#EEEEEE'>05/23/2009</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>13,561</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>6</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=janem15'>janem15</a></td>
<td align='center' bgcolor='#FFFFFF'>05/23/2009</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>13,555</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>7</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=cutedog1995'>cutedog1995</a></td>
<td align='center' bgcolor='#EEEEEE'>05/22/2009</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>13,509</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>8</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=achmed11811'>achmed11811</a></td>
<td align='center' bgcolor='#FFFFFF'>05/22/2009</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>13,304</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>9</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=capullito1000'>capullito1000</a></td>
<td align='center' bgcolor='#EEEEEE'>05/23/2009</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>13,297</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>10</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=bbkmadi123'>bbkmadi123</a></td>
<td align='center' bgcolor='#FFFFFF'>05/25/2009</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>13,290</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>11</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=lebarivka90'>lebarivka90</a></td>
<td align='center' bgcolor='#EEEEEE'>05/25/2009</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>13,264</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>12</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=reallyrubbish'>reallyrubbish</a></td>
<td align='center' bgcolor='#FFFFFF'>05/25/2009</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>13,254</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>13</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=xxxtomxxx'>xxxtomxxx</a></td>
<td align='center' bgcolor='#EEEEEE'>05/23/2009</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>13,237</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>14</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=conman1990'>conman1990</a></td>
<td align='center' bgcolor='#FFFFFF'>05/22/2009</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>13,235</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>15</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=band_blonde'>band_blonde</a></td>
<td align='center' bgcolor='#EEEEEE'>05/22/2009</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>13,210</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>16</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=iluvmonkeys'>iluvmonkeys</a></td>
<td align='center' bgcolor='#FFFFFF'>05/22/2009</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>13,204</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>17</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=gwballer'>gwballer</a></td>
<td align='center' bgcolor='#EEEEEE'>05/25/2009</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>13,203</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>18</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=poopeyapple'>poopeyapple</a></td>
<td align='center' bgcolor='#FFFFFF'>05/22/2009</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>13,197</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>19</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=pinkorangebubbles91'>pinkorangebubbles91</a></td>
<td align='center' bgcolor='#EEEEEE'>05/25/2009</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>13,189</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>20</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=mackieandhayhay'>mackieandhayhay</a></td>
<td align='center' bgcolor='#FFFFFF'>05/24/2009</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>13,187</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>21</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=23titan'>23titan</a></td>
<td align='center' bgcolor='#EEEEEE'>05/26/2009</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>13,170</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>22</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=dabomb8675303'>dabomb8675303</a></td>
<td align='center' bgcolor='#FFFFFF'>05/23/2009</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>13,166</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>23</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=tiggrbabie'>tiggrbabie</a></td>
<td align='center' bgcolor='#EEEEEE'>05/22/2009</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>13,159</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>24</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=msshlc'>msshlc</a></td>
<td align='center' bgcolor='#FFFFFF'>05/23/2009</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>13,155</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>25</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=5hortay'>5hortay</a></td>
<td align='center' bgcolor='#EEEEEE'>05/23/2009</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>13,147</td>
</tr>
</table></div></div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='footer'>
    
<div id="ad_spot">
    <a href="javascript:void(0);"  onMouseOver="showspot(); return false;" onMouseOut="hidespot(); return false;" >
        <img src="http://graphics.millsberry.com/site_gfx/adSpot_icon.gif" width="30" height="25"  border="0"/>
    </a>
</div>
<div id="warning" style="position:absolute; visibility:hidden;">
    <img src="http://graphics.millsberry.com/site_gfx/adSpot_popup.gif" hspace="10" width="258" height="49" alt="" border="0"/>
</div>
MILLSBERRY &reg;, characters, logos, product names 
and all related indicia are trademarks of Mills Online, Inc., &copy; 
2004-2009.<BR> &reg; denotes Reg. US Pat. & TM Office. All rights 
reserved.<br>
Use of this site signifies your acceptance of the <a href='/town_hall/terms.phtml'><b>Terms and Conditions</b></a>.
Please view our <a href='/town_hall/terms.phtml'><b>Privacy Policy</b></a>.<br>
<br>

</div>
</div>
<div id='bottom'>&nbsp;</div>
</div>
</body>
</html>
