
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- www.millsberry.com -->
<html>
<!--[if lt IE 7]>
        <script type="text/javascript" src="/js/unitpngfix/unitpngfix.js"></script>
<![endif]--> 
<head>


    <meta http-equiv="imagetoolbar" content="no">
    <meta name="keywords" content="Mills,Millsbury,Milsberry,Milsbury,Millberry,Millbury,Fun games,Spanish language games,Educational games,Active games,Citizen,Cool stuff,Arcade,Music Mix,Fun,Games,Explore,Adventure,Create,Character,Buddy,Care,Academy,School,Gym,Gymnasium,Solver,Science,Project,Town,Pets,Children's games,Games for kid,Kid games,Kids games,Kid's games,Children,Safe gaming">
    <meta name="description" content="Explore the virtual world of Millsberry with your own customized buddy. Design a home, play games, grow a farm that helps those in need, and much more!">
    <title>Millsberry - High Scores</title>
    
    
    <script type="text/javascript" src="/common.js?v=3"></script>
    <script type="text/javascript" src="/js/swfobject.js"></script>
    <script type="text/javascript" src="/js/jquery/jquery-1.3.2.min.js"></script>
    <script type="text/javascript" src="/js/jquery/jquery-ui-1.7.2.custom.min.js"></script>
    <script type="text/javascript" src="/js/jquery/jquery-millsberry.js"></script>

    <link rel="stylesheet" type="text/css" href="/css/theme/royal.phtml?v=3">
    <link rel="stylesheet" type="text/css" href="/css/template.css?v=6">
    <link rel="stylesheet" type="text/css" href="/css/global.css?v=3">
    <link rel="stylesheet" type="text/css" href="/css/jquery/jquery-custom.css">
    <link rel="stylesheet" type="text/css" href="/css/jquery/jquery-millsberry-css.phtml">
    <link rel="stylesheet" type="text/css" href="/css/gamepages/hiscores.css?v=1">

    <!--[if lt IE 7.00]>
        <link rel="stylesheet" type="text/css" href="/css/template.ie.css?v=2">
        <link rel="stylesheet" type="text/css" href="/css/global.ie.css?v=2">
        <link rel="stylesheet" type="text/css" href="/css/jquery/jquery-millsberry-css.ie.phtml">
        <![endif]-->

</head>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<body  >

<script src="http://www.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript"> _uacct = "UA-1272972-1"; urchinTracker();</script>
<!-- BEGIN: LOGIN POPUP -->
<div id="login_popup" class="dlg_modal" style="width:535px; height:295px; display:none;">
	<div id="close_overlay" class="close_overlay" onclick="closeDialogWindow('login_popup')" style="position:relative;left:465px;top:-10px;"></div>
	<div align="left" style="display:block; position:relative; top:55px; left:103px; width:320px">
		
		<form action='' method="post">
			<fieldset style="border:none">
				<div id="login_name_container" class="input_container input_container_inactive " style="width:157px; height:32px; text-align: center; ">
					<div id="login_name" style="position:relative; top:5px;">
						<input width="76" type="text" name="login_username" id="login_username" class="jq_input_field text ui-widget-content ui-corner-all input_field" />
					</div>
				</div>
				<div id="login_password_container" class="input_container input_container_inactive " style="width:157px; height:32px; text-align: center; ">
					<div id="login_password" style="position:relative; top:5px;">
						<input width="76" type="password" name="login_pass" id="login_pass" value="" class="jq_input_field text ui-widget-content ui-corner-all input_field" />
					</div>
				</div>
				<!-- width="76" height="27"-->
				<div style="position:relative; top:7px; left:-100px; width:255px; height:27px; " >
										<div style="float:right; ">
						<input type="image" value="Login" src="http://graphics.millsberry.com/site_gfx/login/go-button.gif">						
					</div>
						
				</div>
				
			</fieldset>
		</form>	

		<div style="float:left; position:relative; top:-29px; left:265px">
			<a href="/signup.phtml"><img src="http://graphics.millsberry.com/site_gfx/login/start-button.gif" width="97" height="27" border="0" name="start" /></a>					
		</div>
		
	</div>
</div>
<!-- END: LOGIN POPUP -->


<div id='top'>
	    <a href='/'><span id='logo'>&nbsp;</span></a>
    
    <div id='layout_head'>
		<div id='login_info'>
			244 citizens online now&nbsp;|&nbsp; <a href='/town_hall/faq.phtml'>HELP</a>
		</div> <!--login_info-->
		<div id='stripe'>
			     <div id="top_nav_flashcontent">
     <!--default content-->
	 </div>

	<script type="text/javascript">
		// <![CDATA[
        
        // redirect to the upgrade page if flash is installed, but version is too low
		var version = deconcept.SWFObjectUtil.getPlayerVersion();
        if(version["major"] < 8 && version["major"] > 0) {
            window.location='/flash.phtml';
        } else {
            writeFlashContent();
        }
        
        function writeFlashContent() {
            var so = new SWFObject("http://graphics.millsberry.com/template/top_nav_v2.swf?url=http%3A%2F%2Fwww.millsberry.com%2Ftop_nav_xml.phtml", "top_nav", "750", "45", "8");
            so.addParam("wmode", "transparent");
            so.addParam("scale", "noscale");
            so.addParam("AllowScriptAccess", "always");
            so.useExpressInstall('http://graphics.millsberry.com/expressinstall.swf');
            so.write("top_nav_flashcontent");
        }
		
		// ]]>
	</script>
		</div> <!-- stripe -->
    </div> <!-- layout_head -->
</div> <!-- top -->

<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='body'>
	<div id='layout_body'>		
		<div id='side_nav'>
			<script type='text/javascript'>flash_object ('http://graphics.millsberry.com/template/side_nav_v3.swf', '155', '1300', '&url=http%3A%2F%2Fwww.millsberry.com%2Fside_nav_xml.phtml%3Fpage_relative_url%3D%252Fgamepages%252Fhiscores.phtml%253Fgame_id%253D525%26now%3D1284109428&unixTimeStamp=1284109428&serverTimeOffset=28800', '8', 'noscale', 'transparent');</script>		</div>
		<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
		<div id='main'>		
			
<div id='interior'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/game_interiors/interior_525_v1.swf', '600', '400', '&unixTimeStamp=1284109428&serverTimeOffset=28800', '7', 'noscale', 'transparent');</script></div>
<div id='interior_stripe'>High Scores : <a href='flashgame_ctp.phtml?game_id=525'>Fruit Gushers&#174; Flavor Shock presents GushBerry</a></div>
<div id='content'>

<table id='high_scores' width='100%' border='0' cellpadding='5' cellspacing='0'>
<tr>
<td class='high_score_header' width='10%' align='center' bgcolor='silver'>Rank</td>
<td class='high_score_header' align='center' bgcolor='silver'>Username</td>
<td class='high_score_header' align='center' bgcolor='silver'>Date</td>
<td class='high_score_header' width='20%' align='center' bgcolor='silver'>Score</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>1</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=rickys_beast'>rickys_beast</a></td>
<td align='center' bgcolor='#EEEEEE'>09/07/2010</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,293</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>2</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=ricky_rocks'>ricky_rocks</a></td>
<td align='center' bgcolor='#FFFFFF'>09/07/2010</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>1,291</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>3</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=phillies987654321'>phillies987654321</a></td>
<td align='center' bgcolor='#EEEEEE'>09/07/2010</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,282</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>4</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=ratty_41'>ratty_41</a></td>
<td align='center' bgcolor='#FFFFFF'>09/06/2010</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>1,280</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>5</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=kingsway7'>kingsway7</a></td>
<td align='center' bgcolor='#EEEEEE'>09/07/2010</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,280</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>6</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=9884340a'>9884340a</a></td>
<td align='center' bgcolor='#FFFFFF'>09/08/2010</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>1,279</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>7</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=kddmfcwl'>kddmfcwl</a></td>
<td align='center' bgcolor='#EEEEEE'>09/08/2010</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,278</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>8</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=mariceallen'>mariceallen</a></td>
<td align='center' bgcolor='#FFFFFF'>09/09/2010</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>1,278</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>9</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=naz004'>naz004</a></td>
<td align='center' bgcolor='#EEEEEE'>09/09/2010</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,276</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>10</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=cail_wilckins'>cail_wilckins</a></td>
<td align='center' bgcolor='#FFFFFF'>09/09/2010</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>1,274</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>11</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=kristinesader'>kristinesader</a></td>
<td align='center' bgcolor='#EEEEEE'>09/10/2010</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,273</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>12</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=confettifireworks'>confettifireworks</a></td>
<td align='center' bgcolor='#FFFFFF'>09/10/2010</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>1,272</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>13</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=tartar23'>tartar23</a></td>
<td align='center' bgcolor='#EEEEEE'>09/06/2010</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,270</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>14</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=shy6oonh'>shy6oonh</a></td>
<td align='center' bgcolor='#FFFFFF'>09/06/2010</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>1,269</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>15</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=teddybear909643'>teddybear909643</a></td>
<td align='center' bgcolor='#EEEEEE'>09/06/2010</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,268</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>16</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=husnan'>husnan</a></td>
<td align='center' bgcolor='#FFFFFF'>09/06/2010</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>1,267</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>17</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=katyperry505'>katyperry505</a></td>
<td align='center' bgcolor='#EEEEEE'>09/09/2010</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,267</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>18</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=germanpetra'>germanpetra</a></td>
<td align='center' bgcolor='#FFFFFF'>09/09/2010</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>1,266</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>19</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=awesomekid1997'>awesomekid1997</a></td>
<td align='center' bgcolor='#EEEEEE'>09/07/2010</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,264</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>20</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=mynamesharry1998'>mynamesharry1998</a></td>
<td align='center' bgcolor='#FFFFFF'>09/06/2010</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>1,261</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>21</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=moomoo9287'>moomoo9287</a></td>
<td align='center' bgcolor='#EEEEEE'>09/08/2010</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,261</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>22</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=narutofan1998'>narutofan1998</a></td>
<td align='center' bgcolor='#FFFFFF'>09/08/2010</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>1,259</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>23</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=hannah599796'>hannah599796</a></td>
<td align='center' bgcolor='#EEEEEE'>09/07/2010</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,258</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>24</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=tylerr1949'>tylerr1949</a></td>
<td align='center' bgcolor='#FFFFFF'>09/09/2010</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>1,258</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>25</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=elesabet'>elesabet</a></td>
<td align='center' bgcolor='#EEEEEE'>09/08/2010</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,257</td>
</tr>
</table></div>		</div>
		<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
		<div id='footer'>
		    
<div id="ad_spot">
    <a href="javascript:void(0);"  onMouseOver="showspot(); return false;" onMouseOut="hidespot(); return false;" >
        <img src="http://graphics.millsberry.com/site_gfx/adSpot_icon.gif" width="30" height="25"  border="0"/>
    </a>
</div>
<div id="warning" style="position:absolute; visibility:hidden;">
    <img src="http://graphics.millsberry.com/site_gfx/adSpot_popup.gif" hspace="10" width="258" height="49" alt="" border="0"/>
</div>

MILLSBERRY &reg;, characters, logos, product names 
and all related indicia are trademarks of Mills Online, Inc., &copy; 
2004-2010.<BR> &reg; denotes Reg. US Pat. & TM Office. All rights 
reserved.<br>
Use of this site signifies your acceptance of the <a href='/town_hall/terms.phtml'><b>Terms and Conditions</b></a>.
Please view our <a href='/town_hall/terms.phtml'><b>Privacy Policy</b></a>.<br>
<br>

		</div>
	</div>
	<div id='bottom'>&nbsp;</div>
</div>


</body>
</html>