<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
<HEAD>
	<TITLE>Millsberry - Town Hall (Frequently Asked Questions)</TITLE>
  <LINK REL="stylesheet" TYPE="text/css" HREF="http://www.millsberry.com/styles.css">
  </HEAD>
<BODY LEFTMARGIN=0 TOPMARGIN=0 MARGINWIDTH=0 MARGINHEIGHT=0 BACKGROUND='http://www.millsberry.com/images/site_gfx/tile_mill.gif'>
<TABLE BORDER="0" HEIGHT="100%" WIDTH="100%" ALIGN="LEFT" CELLSPACING="0" CELLPADDING="0">
  <TR>
    <TD ROWSPAN='2'><A HREF='http://www.millsberry.com'><IMG SRC="http://www.millsberry.com/images/site_gfx/logo.gif" onMouseOut="src='http://www.millsberry.com/images/site_gfx/logo.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/logo_over.gif';" BORDER="0" ALT="Back to MAIN"></A></TD>
    <TD WIDTH="650" HEIGHT="55" VALIGN="TOP" BGCOLOR='#000000'>
      <TABLE BORDER='0' CELLPADDING='0' CELLSPACING='0'>
        <TR>
          <TD>
            <A HREF="http://www.millsberry.com/home/?r=66777"><IMG SRC="http://www.millsberry.com/images/site_gfx/visit_home.gif" BORDER="0" ALT="Visit your Home!" onMouseOut="src='http://www.millsberry.com/images/site_gfx/visit_home.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/visit_home_over.gif';"></A>
          </TD>
          <TD>
            <A HREF="http://www.millsberry.com/main_map.phtml?location=downtown"><IMG SRC="http://www.millsberry.com/images/site_gfx/visit_shopping.gif" BORDER="0" ALT="Visit the Town Center!" onMouseOut="src='http://www.millsberry.com/images/site_gfx/visit_shopping.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/visit_shopping_over.gif';"></A>
          </TD>
          <TD>
            <A HREF="http://www.millsberry.com/gamepages/hiscores.phtml"><IMG SRC="http://www.millsberry.com/images/site_gfx/visit_hi_scores.gif" BORDER="0" ALT="Visit the Hi Scores!" onMouseOut="src='http://www.millsberry.com/images/site_gfx/visit_hi_scores.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/visit_hi_scores_over.gif';"></A>
          </TD>
          <TD>
            <A HREF="http://www.millsberry.com/town_hall/faq.phtml"><IMG SRC="http://www.millsberry.com/images/site_gfx/visit_faq.gif" BORDER="0" ALT="Visit the Help Pages!" onMouseOut="src='http://www.millsberry.com/images/site_gfx/visit_faq.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/visit_faq_over.gif';"></A>
          </TD>
        </TR>
        <FORM NAME='login' ACTION='http://www.millsberry.com/index.phtml' method='post'>
        <TR>
          <TD COLSPAN='4' VALIGN='bottom'>
            <FONT COLOR="#FFFFFF">
              <B>
                &nbsp;&nbsp;&nbsp;
                Username
                       <input type='text' name='login_username' SIZE='10'>
                       Password
                       <input type='password' name='login_pass' SIZE='10'>&nbsp;
                       <input type='image' src='http://www.millsberry.com/images/site_gfx/visit_log_in.gif' HEIGHT=20 name='login' value='go' border='0' align='top' onMouseOut="src='http://www.millsberry.com/images/site_gfx/visit_log_in.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/visit_log_in_over.gif';"> <A HREF='http://www.millsberry.com/town_hall/support.phtml?q=pw'><FONT COLOR='#FFFFFF' class='smallfont'>[ forgot your password? ]</FONT></A>              </B>
            </FONT>
          </TD>
        </TR>
        </FORM>
      </TABLE>
    </TD>
    <TD WIDTH="100%" BGCOLOR='#000000' COLSPAN='2'>
      
    </TD>
  </TR>
  <FORM NAME='search' ACTION='http://www.millsberry.com/site_search.phtml' method='get'>
  <TR>
    <TD COLSPAN='3' WIDTH="600" HEIGHT="25" VALIGN="TOP" ALIGN="LEFT" CLASS="header_stripe_TD"><TABLE WIDTH='100%' BORDER='0' CELLPADDING='0' CELLSPACING='0'><TR><TD><IMG SRC='http://www.millsberry.com/images/site_gfx/header_stripe.gif'><IMG SRC='http://www.millsberry.com/images/site_gfx/slice_11.gif'></TD><TD ALIGN='RIGHT' CLASS='header_stripe_TD'>Search:<INPUT TYPE='text' NAME='search'></TD><TD><input type='image' src='http://www.millsberry.com/images/site_gfx/visit_go.gif' HEIGHT='25' name='login' border='0' align='top' onMouseOut="src='http://www.millsberry.com/images/site_gfx/visit_go.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/visit_go_over.gif';" CLASS='checkbox'></TD></TR></TABLE></TD>
  </TR>
  </FORM>
  <TR>
    <TD WIDTH="150" VALIGN="TOP" HEIGHT="100%" CLASS="sidenav_TD" background="http://www.millsberry.com/images/site_gfx/left_side_nav_stripe.gif">
          <TABLE BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH='100%'>
        <TR>
          <TD ALIGN='CENTER' VALIGN='TOP'>
              
  <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" width="150" height="70">
  <param name="allowScriptAccess" value="sameDomain" />
  <param name=movie value="http://www.millsberry.com/images/site_gfx/sideNavButton_v1.swf?sideNavButtonXML=<button><name>sideNavButton_mc</name><label><text>%3CP%20ALIGN%3D%22CENTER%22%3E%3CFONT%20SIZE%3D%226%22%3E%3CP%3E%26nbsp%3B%3C%2FP%3E%3C%2FFONT%3E%3CFONT%20SIZE%3D%2240%22%20COLOR%3D%22%23FFFFFF%22%3EMap%3C%2FFONT%3E%3C%2FP%3E</text><dropShadow><x>3</x><y>3</y><colorTransform>0,0,0,0,0,0,50,0</colorTransform></dropShadow></label><url>http%3A%2F%2Fwww.millsberry.com%2Fmain_map.phtml</url><target>_self</target></button>">
  <param name=quality value=high>
  <param name=menu value=false>
  <param name="wmode" value="transparent" />
  <param name=scale value=noscale>
  <param name="salign" value="lt" />
  <embed src="http://www.millsberry.com/images/site_gfx/sideNavButton_v1.swf?sideNavButtonXML=<button><name>sideNavButton_mc</name><label><text>%3CP%20ALIGN%3D%22CENTER%22%3E%3CFONT%20SIZE%3D%226%22%3E%3CP%3E%26nbsp%3B%3C%2FP%3E%3C%2FFONT%3E%3CFONT%20SIZE%3D%2240%22%20COLOR%3D%22%23FFFFFF%22%3EMap%3C%2FFONT%3E%3C%2FP%3E</text><dropShadow><x>3</x><y>3</y><colorTransform>0,0,0,0,0,0,50,0</colorTransform></dropShadow></label><url>http%3A%2F%2Fwww.millsberry.com%2Fmain_map.phtml</url><target>_self</target></button>" quality="high" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" scale="exactfit" width="150" height="70" wmode="transparent">
  </embed>
  </object>
  <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" width="150" height="70">
  <param name="allowScriptAccess" value="sameDomain" />
  <param name=movie value="http://www.millsberry.com/images/site_gfx/sideNavButton_v1.swf?sideNavButtonXML=<button><name>sideNavButton_mc</name><label><text>%3CP%20ALIGN%3D%22CENTER%22%3E%3CFONT%20SIZE%3D%226%22%3E%3CP%3E%26nbsp%3B%3C%2FP%3E%3C%2FFONT%3E%3CFONT%20SIZE%3D%2240%22%20COLOR%3D%22%23FFFFFF%22%3EGames%3C%2FFONT%3E%3C%2FP%3E</text><dropShadow><x>3</x><y>3</y><colorTransform>0,0,0,0,0,0,50,0</colorTransform></dropShadow></label><url>http%3A%2F%2Fwww.millsberry.com%2Fgamepages%2Fgames_list.phtml</url><target>_self</target></button>">
  <param name=quality value=high>
  <param name=menu value=false>
  <param name="wmode" value="transparent" />
  <param name=scale value=noscale>
  <param name="salign" value="lt" />
  <embed src="http://www.millsberry.com/images/site_gfx/sideNavButton_v1.swf?sideNavButtonXML=<button><name>sideNavButton_mc</name><label><text>%3CP%20ALIGN%3D%22CENTER%22%3E%3CFONT%20SIZE%3D%226%22%3E%3CP%3E%26nbsp%3B%3C%2FP%3E%3C%2FFONT%3E%3CFONT%20SIZE%3D%2240%22%20COLOR%3D%22%23FFFFFF%22%3EGames%3C%2FFONT%3E%3C%2FP%3E</text><dropShadow><x>3</x><y>3</y><colorTransform>0,0,0,0,0,0,50,0</colorTransform></dropShadow></label><url>http%3A%2F%2Fwww.millsberry.com%2Fgamepages%2Fgames_list.phtml</url><target>_self</target></button>" quality="high" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" scale="exactfit" width="150" height="70" wmode="transparent">
  </embed>
  </object><object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" width="140" height="350" id="item_loader" align="middle">
<param name="allowScriptAccess" value="sameDomain" />
<param name="movie" value="http://www.millsberry.com/images/item_loader_v3.swf?itemLoaderXML=<?xml version='1.0' ?><message success='1' text = ''><item><frame>1</frame><objectName>item</objectName><url>http%3A%2F%2Fwww.millsberry.com%2Fimages%2Fsite_gfx%2Fprebuddy.swf</url></item><button><objectName>button</objectName><url>http%3A%2F%2Fwww.millsberry.com%2Fsignup.phtml</url><window>_self</window><useBorderAsRollover>1</useBorderAsRollover></button><border><objectName>border</objectName><lineColor>0x000099</lineColor><size>4</size></border><preloader><objectName>preloader</objectName><width>140</width><height>350</height></preloader></message>"/>
<param name="loop" value="false" />
<param name="menu" value="true" />
<param name="quality" value="high" />
<param name="wmode" value="transparent" />
<param name="devicefont" value="true" />
<param name="bgcolor" value="#666666" />
<embed src="http://www.millsberry.com/images/item_loader_v3.swf?itemLoaderXML=<?xml version='1.0' ?><message success='1' text = ''><item><frame>1</frame><objectName>item</objectName><url>http%3A%2F%2Fwww.millsberry.com%2Fimages%2Fsite_gfx%2Fprebuddy.swf</url></item><button><objectName>button</objectName><url>http%3A%2F%2Fwww.millsberry.com%2Fsignup.phtml</url><window>_self</window><useBorderAsRollover>1</useBorderAsRollover></button><border><objectName>border</objectName><lineColor>0x000099</lineColor><size>4</size></border><preloader><objectName>preloader</objectName><width>140</width><height>350</height></preloader></message>" width="140" height="350" wmode="transparent"/>
</object>

  <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" width="150" height="70">
  <param name="allowScriptAccess" value="sameDomain" />
  <param name=movie value="http://www.millsberry.com/images/site_gfx/sideNavButton_v1.swf?sideNavButtonXML=<button><name>sideNavButton_mc</name><label><text>%3CP%20ALIGN%3D%22CENTER%22%3E%3CFONT%20SIZE%3D%2215%22%3E%3CP%3E%26nbsp%3B%3C%2FP%3E%3C%2FFONT%3E%3CFONT%20SIZE%3D%2228%22%20COLOR%3D%22%23FFFFFF%22%3ESign%20Up%21%21%3C%2FFONT%3E%3C%2FP%3E</text><dropShadow><x>3</x><y>3</y><colorTransform>0,0,0,0,0,0,50,0</colorTransform></dropShadow></label><url>http%3A%2F%2Fwww.millsberry.com%2Fsignup.phtml</url><target>_self</target></button>">
  <param name=quality value=high>
  <param name=menu value=false>
  <param name="wmode" value="transparent" />
  <param name=scale value=noscale>
  <param name="salign" value="lt" />
  <embed src="http://www.millsberry.com/images/site_gfx/sideNavButton_v1.swf?sideNavButtonXML=<button><name>sideNavButton_mc</name><label><text>%3CP%20ALIGN%3D%22CENTER%22%3E%3CFONT%20SIZE%3D%2215%22%3E%3CP%3E%26nbsp%3B%3C%2FP%3E%3C%2FFONT%3E%3CFONT%20SIZE%3D%2228%22%20COLOR%3D%22%23FFFFFF%22%3ESign%20Up%21%21%3C%2FFONT%3E%3C%2FP%3E</text><dropShadow><x>3</x><y>3</y><colorTransform>0,0,0,0,0,0,50,0</colorTransform></dropShadow></label><url>http%3A%2F%2Fwww.millsberry.com%2Fsignup.phtml</url><target>_self</target></button>" quality="high" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" scale="exactfit" width="150" height="70" wmode="transparent">
  </embed>
  </object>          </TD>
        </TR>
      </TABLE>    </TD>
    <TD WIDTH="650" HEIGHT="100%" VALIGN="TOP" ALIGN='LEFT'>  <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" width="600" height="400">
  <param name="allowScriptAccess" value="sameDomain" />
  <param name=movie value="http://www.millsberry.com/images/site_gfx/interiors/int_townhall_v2.swf">
  <param name=quality value=high>
  <param name=menu value=false>
  <param name="wmode" value="transparent" />
  <param name=scale value=exactfit>
  <param name="salign" value="lt" />
  <embed src="http://www.millsberry.com/images/site_gfx/interiors/int_townhall_v2.swf" quality="high" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" scale="exactfit" width="600" height="400">
  </embed>
  </object>
  <HR /><P ALIGN='CENTER'><B>Frequently Asked Questions</B></P><HR /><p>Here are some of the most frequently asked questions about the site. Be sure to read through them -- you might learn something
you didn't know!

<p><A HREF='#1'>What is Millsberry?</A></p>
<p><A HREF='#2'>Does it cost anything?</A></p>
<p><A HREF='#3'>What do I have to do?</A></p>
<p><A HREF='#4'>I have a character. What do I do now?</A></p>
<p><A HREF='#5'>What kind of password should I choose?</A></p>
<p><A HREF='#6'>How do I keep my password a secret?</A></p>
<p><A HREF='#7'>How can I contact Millsberry.com?</A></p>
<p><A HREF='#8'>My character is hungry. What do I do?</A></p>
<p><A HREF='#9'>How do I get more Millsbucks?</A></p>
<p><A HREF='#10'>How do bank accounts work?</A></p>
<p><A HREF='#11'>The game I'm playing is really slow!</A></p>
<p><A HREF='#12'>Where is the ______ Shop?</A></p>
<p><A HREF='#13'>What does the Shortcuts bar do?</A></p>
<p><A HREF='#14'>How do I become Citizen of the Day?</A></p>
<p><A HREF='#15'>Can I rename my character?</A></p>
<p><A HREF='#16'>What do the four symbols under my character mean?</A></p>
<p><A HREF='#17'>When I created my character, he only had 10 different shirts! What's up with that?</A></p>
<p><A HREF='#18'>Why does my food go bad?</A></p>
<p><A HREF='#19'>When I read a book, my intelligence stat doesn't increase. Why?</A></p>
<p><A HREF='#21'>How do I get chosen to be the Featured Home?</A></p>
<hr>

<P><A NAME='1'></A><b>What is Millsberry?</b><br>Millsberry is a fun virtual city for you to explore. 
You create a citizen of the city and discover Millsberry through his eyes. You'll need to make sure he takes care of himself, 
so you'll need to get food (from the shopping area) and make sure he exercises (by playing games), but you'll also get to 
go on adventures, solve mysteries and have all kinds of fun while visiting Millsberry!</P>

<P><A NAME='2'></A><b>Does it cost anything?</b><br>No. Being a citizen of Millsberry is absolutely free. </P>

<P><A NAME='3'></A><b>What do I have to do?</b><br>The first thing you need to do is sign up. Click HERE to create an account. 
Once you have created an account, you can create your own Millsberry citizen. Click on Start Here and decide your citizen's gender, 
appearance and even personality traits.</P>

<P><A NAME='4'></A><b>I have a character. What do I do now?</b><br>Explore Millsberry! You can go to the shopping complex, 
set up a bank account, play some games, or just look around for the many surprises waiting for you to discover!</P>

<P><A NAME='5'></A><b>What kind of password should I choose?</b><br>When you choose a password, don't go for something really obvious. 
Some examples of bad passwords are:
<div align="center"><p>password
<br>12345
<br>letmein
<br>Millsberry
<br>or any famous fictional character</div>
<P>Use a combination of letters and numbers. That makes it a lot harder for people to guess.

<P><A NAME='6'></A><b>How do I keep my password a secret?</b><br>By not telling it to ANYBODY! Never tell anybody your password, 
no matter who they say they are. No staff member will ever need to ask for your password. There are many people out there who would 
love to get their hands on your hard earned Millsbucks and they will pretend to be staff, have a secret code, anything to try 
getting you to tell them. Again, no Millsberry staff member will ever contact you via hotmail, AIM, MSN Messenger. 
<P>Also, if you visit Millsberry in a public place such as a school or library, be sure to log out when you are done. 
To log out, simply click on 'Log Out' at the top of the screen.
<p>Finally, if something looks too good to be true, chances are it is. There are no secret codes to become rich overnight, 
there is no magic web page that gives you one million Millsbucks.

<P><A NAME='7'></A><b>How can I contact Millsberry.com?</b><br>By filling out the feedback form located <A HREF='support.phtml'>here</A>

<P><A NAME='8'></A><b>My character is hungry. What do I do?</b><br>
Click on the SHOPPING button at the top of the screen and go to the Grocery Store. 
There, you'll find all kinds of foods for your character. 
Just remember it's important to fill your stomach but it's also important to make healthy choices. 
Make sure to choose a variety of foods to help keep your character healthy.

<P><A NAME='9'></A><b>How do I get more Millsbucks?</b><br>
By playing games! Playing a game doesn't cost you anything - it's always free. And, when you send in a score, you get points. 
You can use your points to buy food, clothes, furniture, or any number of other things in Millsberry.

<P><A NAME='10'></A><b>How do bank accounts work?</b><br>
You deposit money in the bank and they pay you interest based on how much money you have in your account. The more money you have
invested in the bank, the larger the interest becomes. In a way, the bank pays you money to keep money there. But you don't get
your interest payments automatically -- you have to stop by the bank every day to pick up your interest. If you skip a day, you
don't get your interest bonus.

<p>The larger your account is, the more interest you collect, so be sure to keep as much money as possible in the bank, keeping the
rest as spending money as you go around town. Never withdraw more money than you need -- the more money you have in the bank, the
more interest you earn!

<P><A NAME='11'></A><b>The game I'm playing is really slow!</b><br>
You can adjust the quality of your game when you first click on it.  High Quality (the default) makes your game look better, 
but move much slower.  If you want your game to work and load faster, select Low Quality.  Also, you might want to adjust the 
size of the game to make it load faster as well.

<P><A NAME='12'></A><b>Where is the ______ Shop?</b><br>
All shops are located in Downtown Millsberry.  To get there, all you have to do is click 
<a href=http://gmidev.neopets.com/main_map.phtml?location=downtown>here</a> .

<P><A NAME='13'></A><b>What does the Shortcuts bar do?</b><br>
If you're a constant buyer at the Book Store, you may want to get there without all the hassle of going to Downtown Millsberry.  
To add a page to your Shortcuts menu, simply click "+" on the shortcuts bar when you are at that page.  Then, whenever you want to 
get there, all you have to do is click!

<P><A NAME='14'></A><b>How do I become Citizen of the Day?</b><br>
Citizen of the Day is chosen by the Millsberry City Council. Each day, they look through the city records and choose a Citizen.
If you'd like your Citizen to be considered for this prestigious award, just be the best example you can be!

<P><A NAME='15'></A><b>Can I rename my character?</b><br>
Once you've named your character, you can't change his or her name.  After all, would you want someone changing <em>your</em> name?

<P><A NAME='16'></A><b>What do the four symbols under my character mean?</b><br>
They are your character's statistics. If you put your cursor over each bar, you'll see the name for each statistic. 
Blue is Fitness, measuring your character's general physical abilities. Green is Civics, measuring much your character 
contributes to the community and looks after others. Red is Health, which measures how physically well your character is. 
Lastly, yellow is Intelligence, representing how often your character studies.

<P><A NAME='17'></A><b>When I created my character, he only had 10 different shirts! What's up with that?</b><br>
If you want your character to be snazzy and stylish, you'll have to play games and earn some Millsbucks so that you can 
buy new clothes for him or her at the Clothes Shop.

<P><A NAME='18'></A><b>Why does my food go bad?</b><br>
Because that's what happens to food! Nothing lasts forever, even if you keep it in the freezer. Eventually, all food loses its freshness
and you need to go out and buy new groceries.

<p><A HREF='#19'>When I read a book, my intelligence stat doesn't increase. Why?</b></p>
The first time you read a book, your Intelligence goes up. Re-reading the same book over and over again won't make you any
smarter; you'll have to go out and get <i>new</i> books.

<P><A NAME='22'></A><b>How do I get chosen to be the Featured Home?</b><br>
B keeping your house clean, arranging the furniture in keen ways, and keeping the door open to visitors!  </TD>
    <TD WIDTH="150" VALIGN="TOP" ALIGN='CENTER' HEIGHT="100%">
          </TD>
          <TD WIDTH='100%'>
            &nbsp;
          </TD>
  </TR>
  <TR>
    <TD COLSPAN="4" WIDTH="100%" ALIGN="CENTER" CLASS="footer_TD">
      <SPAN CLASS='footerfont'>
      MILLSBERRY, characters, logos, product names and all related indicia are trademarks of General Mills, Inc., © 2004.<BR> ® denotes Reg. US Pat. & TM Office. All rights reserved.
        <BR>
        Use of this site signifies your acceptance of the <A HREF='http://www.millsberry.com/town_hall/terms.phtml'>Terms and Conditions</A>.
        <BR>
        Please view our <A HREF='http://www.millsberry.com/town_hall/policy.phtml'>Privacy Policy</A>.
        <BR>
        Please send all comments and inquiries <A HREF='http://www.millsberry.com/town_hall/support.phtml'>here</A>.      </SPAN>
    </TD>
</TABLE>
</BODY>
</HTML>
