<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
<HEAD>
	<TITLE>Millsberry - Police Department (Internet Safety)</TITLE>
  <LINK REL="stylesheet" TYPE="text/css" HREF="http://www.millsberry.com/styles.css">
  </HEAD>
<BODY LEFTMARGIN=0 TOPMARGIN=0 MARGINWIDTH=0 MARGINHEIGHT=0 BACKGROUND='http://www.millsberry.com/images/site_gfx/tile_mill.gif'>
<TABLE BORDER="0" HEIGHT="100%" WIDTH="100%" ALIGN="LEFT" CELLSPACING="0" CELLPADDING="0">
  <TR>
    <TD ROWSPAN='2'><A HREF='http://www.millsberry.com'><IMG SRC="http://www.millsberry.com/images/site_gfx/logo.gif" onMouseOut="src='http://www.millsberry.com/images/site_gfx/logo.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/logo_over.gif';" BORDER="0" ALT="Back to MAIN"></A></TD>
    <TD WIDTH="650" HEIGHT="55" VALIGN="TOP" BGCOLOR='#000000'>
      <TABLE BORDER='0' CELLPADDING='0' CELLSPACING='0'>
        <TR>
          <TD>
            <A HREF="http://www.millsberry.com/home/"><IMG SRC="http://www.millsberry.com/images/site_gfx/visit_home.gif" BORDER="0" ALT="Visit your Home!" onMouseOut="src='http://www.millsberry.com/images/site_gfx/visit_home.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/visit_home_over.gif';"></A>
          </TD>
          <TD>
            <A HREF="http://www.millsberry.com/main_map.phtml?location=downtown"><IMG SRC="http://www.millsberry.com/images/site_gfx/visit_shopping.gif" BORDER="0" ALT="Visit the Town Center!" onMouseOut="src='http://www.millsberry.com/images/site_gfx/visit_shopping.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/visit_shopping_over.gif';"></A>
          </TD>
          <TD>
            <A HREF="http://www.millsberry.com/gamepages/hiscores.phtml"><IMG SRC="http://www.millsberry.com/images/site_gfx/visit_hi_scores.gif" BORDER="0" ALT="Visit the Hi Scores!" onMouseOut="src='http://www.millsberry.com/images/site_gfx/visit_hi_scores.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/visit_hi_scores_over.gif';"></A>
          </TD>
          <TD>
            <A HREF="http://www.millsberry.com/town_hall/faq.phtml"><IMG SRC="http://www.millsberry.com/images/site_gfx/visit_faq.gif" BORDER="0" ALT="Visit the Help Pages!" onMouseOut="src='http://www.millsberry.com/images/site_gfx/visit_faq.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/visit_faq_over.gif';"></A>
          </TD>
        </TR>
        <FORM NAME='login' ACTION='http://www.millsberry.com/index.phtml' method='post'>
        <TR>
          <TD COLSPAN='4' VALIGN='bottom'>
            <FONT COLOR="#FFFFFF">
              <B>
                &nbsp;&nbsp;&nbsp;
                Username
                       <input type='text' name='login_username' SIZE='10'>
                       Password
                       <input type='password' name='login_pass' SIZE='10'>&nbsp;
                       <input type='image' src='http://www.millsberry.com/images/site_gfx/visit_log_in.gif' HEIGHT=20 name='login' value='go' border='0' align='top' onMouseOut="src='http://www.millsberry.com/images/site_gfx/visit_log_in.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/visit_log_in_over.gif';"> <A HREF='http://www.millsberry.com/town_hall/support.phtml?q=pw'><FONT COLOR='#FFFFFF' class='smallfont'>[ forgot your password? ]</FONT></A>              </B>
            </FONT>
          </TD>
        </TR>
        </FORM>
      </TABLE>
    </TD>
    <TD WIDTH="100%" BGCOLOR='#000000' COLSPAN='2'>
      
    </TD>
  </TR>
  <FORM NAME='search' ACTION='http://www.millsberry.com/site_search.phtml' method='get'>
  <TR>
    <TD COLSPAN='3' WIDTH="600" HEIGHT="25" VALIGN="TOP" ALIGN="LEFT" CLASS="header_stripe_TD"><TABLE WIDTH='100%' BORDER='0' CELLPADDING='0' CELLSPACING='0'><TR><TD><IMG SRC='http://www.millsberry.com/images/site_gfx/header_stripe.gif'><IMG SRC='http://www.millsberry.com/images/site_gfx/slice_11.gif'></TD><TD ALIGN='RIGHT' CLASS='header_stripe_TD'>Phone Book:<INPUT TYPE='text' NAME='search'></TD><TD><input type='image' src='http://www.millsberry.com/images/site_gfx/visit_go.gif' HEIGHT='25' name='login' border='0' align='top' onMouseOut="src='http://www.millsberry.com/images/site_gfx/visit_go.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/visit_go_over.gif';" CLASS='checkbox'></TD></TR></TABLE></TD>
  </TR>
  </FORM>
  <TR>
    <TD WIDTH="150" VALIGN="TOP" HEIGHT="100%" CLASS="sidenav_TD" background="http://www.millsberry.com/images/site_gfx/left_side_nav_stripe.gif">
          <TABLE BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH='100%'>
        <TR>
          <TD ALIGN='CENTER' VALIGN='TOP'>
              <A HREF='http://www.millsberry.com/main_map.phtml'><IMG SRC='http://www.millsberry.com/images/site_gfx/mapbutton.gif' onMouseDown="src='http://www.millsberry.com/images/site_gfx/mapbutton_down.gif';" onMouseOut="src='http://www.millsberry.com/images/site_gfx/mapbutton.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/mapbutton_over.gif';" BORDER='0'></A><BR><A HREF='http://www.millsberry.com/gamepages/games_list.phtml'><IMG SRC='http://www.millsberry.com/images/site_gfx/gamesbutton.gif' onMouseDown="src='http://www.millsberry.com/images/site_gfx/gamesbutton_down.gif';" onMouseOut="src='http://www.millsberry.com/images/site_gfx/gamesbutton.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/gamesbutton_over.gif';" BORDER='0'></A><BR><A HREF='http://www.millsberry.com/signup.phtml'><IMG SRC='http://www.millsberry.com/images/site_gfx/prebuddy.gif' BORDER='1'></A><BR>
  <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" width="150" height="70">
  <param name="allowScriptAccess" value="sameDomain" />
  <param name=movie value="http://www.millsberry.com/images/site_gfx/sideNavButton_v1.swf?sideNavButtonXML=<button><name>sideNavButton_mc</name><label><text>%3CP%20ALIGN%3D%22CENTER%22%3E%3CFONT%20SIZE%3D%2215%22%3E%3CP%3E%26nbsp%3B%3C%2FP%3E%3C%2FFONT%3E%3CFONT%20SIZE%3D%2228%22%20COLOR%3D%22%23FFFFFF%22%3ESign%20Up%21%21%3C%2FFONT%3E%3C%2FP%3E</text><dropShadow><x>3</x><y>3</y><colorTransform>0,0,0,0,0,0,50,0</colorTransform></dropShadow></label><url>http%3A%2F%2Fwww.millsberry.com%2Fsignup.phtml</url><target>_self</target></button>">
  <param name=quality value=high>
  <param name=menu value=false>
  <param name="wmode" value="transparent" />
  <param name=scale value=noscale>
  <param name="salign" value="lt" />
  <embed src="http://www.millsberry.com/images/site_gfx/sideNavButton_v1.swf?sideNavButtonXML=<button><name>sideNavButton_mc</name><label><text>%3CP%20ALIGN%3D%22CENTER%22%3E%3CFONT%20SIZE%3D%2215%22%3E%3CP%3E%26nbsp%3B%3C%2FP%3E%3C%2FFONT%3E%3CFONT%20SIZE%3D%2228%22%20COLOR%3D%22%23FFFFFF%22%3ESign%20Up%21%21%3C%2FFONT%3E%3C%2FP%3E</text><dropShadow><x>3</x><y>3</y><colorTransform>0,0,0,0,0,0,50,0</colorTransform></dropShadow></label><url>http%3A%2F%2Fwww.millsberry.com%2Fsignup.phtml</url><target>_self</target></button>" quality="high" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" scale="exactfit" width="150" height="70" wmode="transparent">
  </embed>
  </object>          </TD>
        </TR>
      </TABLE>    </TD>
    <TD WIDTH="650" HEIGHT="100%" VALIGN="TOP" ALIGN='LEFT'>  <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" width="600" height="400">
  <param name="allowScriptAccess" value="sameDomain" />
  <param name=movie value="http://www.millsberry.com/images/site_gfx/interiors/int_police_v1.swf">
  <param name=quality value=high>
  <param name=menu value=false>
  <param name="wmode" value="transparent" />
  <param name=scale value=exactfit>
  <param name="salign" value="lt" />
  <embed src="http://www.millsberry.com/images/site_gfx/interiors/int_police_v1.swf" quality="high" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" scale="exactfit" width="600" height="400">
  </embed>
  </object>
   <body lang=EN-US style='tab-interval:.5in'>

<div class=Section1>

<p align=center style='text-align:center'><b>Millsberry.com Internet Safety Tips</p></b>

<p>While we try to make
Millsberry.com as safe and friendly as possible, there are still some things
you need to bear in mind. If you are in any doubt using the Internet or
Millsberry.com, talk things over with your Mom, Dad, or a responsible adult who
will know what to do.

<p><b>1. You need
a valid e-mail address to sign up with Millsberry.com. </b>If you're 12 years old
or younger, we use your email address to send you a confirmation that your
account has been activated, but then your email address is automatically and
permanently encrypted within our system so that it cannot be reused. For users
13 or older, you'll also need to enter your e-mail address, as well as your
first and last name and certain other information, to sign up.<span
style="mso-spacerun: yes">  </span>Remember - don't give out personal
information about yourself like your phone number, pictures of you or your
family, where you live, or where you go to school without asking your parents
first. <o:p></o:p></span></p>

<p class=MsoNormal><b><span style='font-size:11.0pt'>2. Don't ever give out
your password to anyone (on or off the Millsberry.com site).</span></b><span
style='font-size:11.0pt'> Millsberry.com staff members will not ask you for
your password, and we will NEVER e-mail you to get your password. Watch out for
fake login screens - some people may copy our login box and post it on their
personal web pages to trick people into entering their user names and
passwords. Look at the URL - if it says anything other than www.Millsberry.com.
DO NOT enter your user information. If anyone does try to get you to reveal
your password, please let us know immediately by using <a
href="http://www.neopets.com/autoform_abuse.phtml?abuse=report"><strong><span
style='color:#000099;text-decoration:none;text-underline:none'>this form</span></strong></a>.
<o:p></o:p></span></p>

<p><b>3. Be
careful whom you talk to on the web.</b> If somebody says something to you, sends you
something, or you see something that makes you uncomfortable, don't look around
or explore. Get your parents instead - they will know what to do. If this
happens on the Millsberry.com site, please let us know by using <a
href="http://www.neopets.com/autoform_abuse.phtml?abuse=report"><strong><span
style='color:#000099;text-decoration:none;text-underline:none'>this form</span></strong></a>
and we will take the necessary action. Also, remember that nothing you write on
the web is truly private -- be careful and think before you type!

<p><b>4. All REAL Millsberry.com
activities and games are contained within the Millsberry.com site.</b>Delete e-mails, files, or web pages that you get from
people you don't really know or trust. Sometimes people post links to viruses
around the Internet, including on the Millsberry.com site, saying the links
lead to other Millsberry.com stuff.<span style="mso-spacerun: yes"> 
</span>Don't be fooled! Links like these may go to nasty viruses that can
seriously damage your computer.<span style="mso-spacerun: yes">  </span>If
they're not located within the Millsberry.com site, then we do not endorse them
and you are proceeding at your own risk. <b>Don't forget: no one needs your
password to send you an item or for any other reason!</b>

<p><b>5. Millsberry.com is
completely FREE, but not all sites are.</b>
Don't ever do anything on the Internet that could cost your family money unless
your parents are there to help you do it.

<p><b>6. Always
follow your family's rules for the Internet.</b> They're there to make sure you have fun
and stay safe online. <o:p></o:p></span></p></TD>
        <TD WIDTH='150' VALIGN='TOP' ALIGN='CENTER' HEIGHT='100%'>          </TD>
          <TD WIDTH='100%'>
            &nbsp;
          </TD>
  </TR>
  <TR>
    <TD COLSPAN="4" WIDTH="100%" ALIGN="CENTER" CLASS="footer_TD">
      <SPAN CLASS='footerfont'>
      MILLSBERRY, characters, logos, product names and all related indicia are trademarks of Mills Online, Inc., © 2004.<BR> ® denotes Reg. US Pat. & TM Office. All rights reserved.
        <BR>
        Use of this site signifies your acceptance of the <A HREF='http://www.millsberry.com/town_hall/terms.phtml'>Terms and Conditions</A>.
        <BR>
        Please view our <A HREF='http://www.millsberry.com/town_hall/policy.phtml'>Privacy Policy</A>.      </SPAN>
    </TD>
</TABLE>
</BODY>
</HTML>
