<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- 10.100.56.31 -->
<html>
<head>
<meta http-equiv='imagetoolbar' content='no'>
<meta name='keywords' content="Mills,Millsbury,Milsberry,Milsbury,Millberry,Millbury,Fun games,Spanish language games,Educational games,Active games,Citizen,Cool stuff,Arcade,Music Mix,Fun,Games,Explore,Adventure,Create,Character,Buddy,Care,Academy,School,Gym,Gymnasium,Solver,Science,Project,Town,Pets,Children's games,Games for kid,Kid games,Kids games,Kid's games,Children,Safe gaming">
<title>Millsberry - Jenneira's Time-Ship</title>
<script type='text/javascript' src='/common.js'></script>
<link rel='shortcut icon' type='image/x-icon' href='/favicon.ico'>
<!-- Appending v=# to these files causes them to recache in the user's browser when # changes -->
<link rel='stylesheet' type='text/css' href='/css/theme/royal.css?v=2'>
<link rel='stylesheet' type='text/css' href='/css/template.css?v=4'>
<link rel='stylesheet' type='text/css' href='/css/global.css?v=1'>
<!--[if lt IE 7.00]>
<link rel='stylesheet' type='text/css' href='/css/template.ie.css?v=1'>
<link rel='stylesheet' type='text/css' href='/css/global.ie.css?v=1'>
<![endif]-->
<link rel='stylesheet' type='text/css' href='/css/crater/ship.css?v=1'>
</head>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<body>

<!--<div id='leaderboard'><h2>Leader Board</h2></div>-->
<div id='top'>
<a href='/index.phtml'><span id='logo'>&nbsp;</span></a>
<div id='layout_head'>
	<div id='login_info'><form name='login' method='post' action='/crater/ship.phtml?msg=1'>
Username <input type='text' name='login_username' size='10'>&nbsp;&nbsp;
Password <input type='password' name='login_pass' size='10'>
<input type='submit' value='Go'>
</form></div>
	<div id='stripe'>
		<div id='stripe_shortcuts'>
			<table width='95' border='0' cellpadding='0' cellspacing='0'><tr>
				<td width='72'></td>
				<td width='23' valign='bottom'></td>
			</tr></table>
		</div>
		<div id='stripe_search'>
			<form name='search' action='/site_search.phtml' method='get'>
			<table width='340' border='0' cellpadding='0' cellspacing='0'><tr>
				<td width='135' align='right'>Address Book&nbsp;</td>
				<td width='105' align='left' valign='middle'><input type='text' name='search' size='15'></td>
				<td width='30' align='center' valign='bottom'><a href='javascript: document.search.submit();' class='stripe_button'><span id='search_button'>&nbsp;</span></a></td>
				<td width='60' align='right'><a href='/town_hall/faq.phtml'>Help</a></td>
			</tr></table>
			</form>
		</div>
	</div>
</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='body'>
<div id='layout_body'>
<div id='side_nav'>
<a href='/main_map.phtml' class='nav_button_hover'><span id='nav_the_city' class='nav_button'>&nbsp;</span></a>
<a href='/main_map.phtml?location=downtown' class='nav_button_hover'><span id='nav_downtown' class='nav_button'>&nbsp;</span></a>
<a href='/tour.phtml' class='nav_button_hover'><span id='nav_tour' class='nav_button'>&nbsp;</span></a>
<a href='/signup.phtml' class='nav_button_hover'><span id='nav_signup' class='nav_button'>&nbsp;</span></a>
<a href='/complex/arcade.phtml' class='nav_button_hover'><span id='nav_arcade' class='nav_button'>&nbsp;</span></a>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='main'>
<div id='interior'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/site_gfx/interiors/int_clearing_v3.swf', '600', '400', '&unixTimeStamp=1157245187&serverTimeOffset=28800', '7', 'noscale');</script></div>
<div id='interior_stripe'>Jenneira's Time-Ship</div>
<div id='content'>
<div class='wce_info'>Hi! I see you've found my time-ship. My name's Jenneira, and I come from the future. I was out flying my time-ship when it got caught in the Alpha Lyrid meteor shower and knocked into your time!<br><br>My engines started failing, and quite a few pieces of my ship fell off as I flew over <a href='/main_map.phtml?location=downtown'>Downtown Millsberry</a>. I'll need to find them in order to get my ship back in working condition. But I have so many repairs to make, I can't leave my ship!<br><br>So the next time you're in Downtown, could you keep an eye out for my time-ship's pieces? I'm certain that you'll know them when you see them! If you do find one of my time-ship's pieces, please pick it up and bring it back to me as soon as possible.<br><br>I must warn you, though&mdash;some of the pieces are very large and quite heavy, so it'll take strong arms to carry them back up here! But your assistance will be appreciated and you will be rewarded for your effort!</div>
You've found a time-ship hidden away in the woods! This vehicle must have created the Westridge Crater, since it's quite battered and looks like it's missing a few important pieces. This young pilot looks like she could use some help. Maybe you could give her a hand?
</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='footer'>
MILLSBERRY &reg;, characters, logos, product names and all related indicia are trademarks of Mills Online, Inc., &copy; 2004-2006.<BR> &reg; denotes Reg. US Pat. & TM Office. All rights reserved.<br>Use of this site signifies your acceptance of the <a href='/town_hall/terms.phtml'><b>Terms and Conditions</b></a>.<br>Please view our <a href='/town_hall/terms.phtml'><b>Privacy Policy</b></a>.
</div>
</div>
<div id='bottom'>&nbsp;</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='debug'>
</div>
</body>
</html>
