<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- www.millsberry.com -->
<html>
<head>


    <meta http-equiv="imagetoolbar" content="no">
    <meta name="keywords" content="Mills,Millsbury,Milsberry,Milsbury,Millberry,Millbury,Fun games,Spanish language games,Educational games,Active games,Citizen,Cool stuff,Arcade,Music Mix,Fun,Games,Explore,Adventure,Create,Character,Buddy,Care,Academy,School,Gym,Gymnasium,Solver,Science,Project,Town,Pets,Children's games,Games for kid,Kid games,Kids games,Kid's games,Children,Safe gaming">
    <title>Millsberry - Batman Fruit Roll Ups Good Guy Challenge</title>
    <script type="text/javascript" src="/common.js?v=2"></script>
    <script type="text/javascript" src="/js/swfobject.js"></script>

    <link rel="stylesheet" type="text/css" href="/css/theme/royal.css?v=2">
    <link rel="stylesheet" type="text/css" href="/css/template.css?v=5">
    <link rel="stylesheet" type="text/css" href="/css/global.css?v=2">

    <!--[if lt IE 7.00]>
        <link rel="stylesheet" type="text/css" href="/css/template.ie.css?v=1">
        <link rel="stylesheet" type="text/css" href="/css/global.ie.css?v=1">
        <![endif]-->

</head>
</head>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<body>
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript"> _uacct = "UA-1272972-1"; urchinTracker();</script>
<div id='top'>
    <a href='/'><span id='logo'>&nbsp;</span></a>
    <div id='layout_head'>
       <div id='login_info'>
           2,145 citizens online now&nbsp;|&nbsp; <a href='/town_hall/faq.phtml'>HELP</a>
       </div> <!--login_info-->
       <div id='stripe'>
                <div id="top_nav_flashcontent">
     <!--default content-->
	 </div>

	<script type="text/javascript">
		// <![CDATA[
        
        // redirect to the upgrade page if flash is installed, but version is too low
		var version = deconcept.SWFObjectUtil.getPlayerVersion();
        if(version["major"] < 8 && version["major"] > 0) {
            window.location='/flash.phtml';
        } else {
            writeFlashContent();
        }
        
        function writeFlashContent() {
            var so = new SWFObject("http://graphics.millsberry.com/template/top_nav.swf?url=http%3A%2F%2Fmillsberry.com%2Ftop_nav_xml.phtml", "top_nav", "750", "36", "8");
            so.addParam("wmode", "transparent");
            so.addParam("scale", "noscale");
            so.addParam("AllowScriptAccess", "always");
            so.useExpressInstall('http://graphics.millsberry.com/expressinstall.swf');
            so.write("top_nav_flashcontent");
        }
		
		// ]]>
	</script>
 
       </div> <!-- stripe -->
    </div> <!-- layout_head -->
</div> <!-- top -->
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='body'>
<div id='layout_body'>
<div id='side_nav'>
<script type='text/javascript'>flash_object ('http://graphics.millsberry.com/template/side_nav_v1.swf', '150', '1280', '&url=http%3A%2F%2Fmillsberry.com%2Fside_nav_xml.phtml%3Fpage_relative_url%3D%252Factivities%252Fbatmanfru%252Fbatman.phtml%26login_status%3D0%26now%3D1225600306&unixTimeStamp=1225600306&serverTimeOffset=28800', '8', 'noscale', 'transparent');</script></div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='main'>
<div id='interior'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/activities/batmanfru/landing.swf', '600', '800', 'location_name=Community+Center&location_url=http%3a%2f%2fmillsberry.com%2fcommunitycenter%2f&unixTimeStamp=1225600306&serverTimeOffset=28800', '7', 'noscale', 'transparent');</script></div>






<!-- Start of DoubleClick Spotlight Tag: Please do not remove-->
<!-- Activity Name for this tag is:FRU F09 Display Campaign Landing Page -->
<!-- Web site URL where tag should be placed: http://www.millsberry.com -->
<!-- This tag must be placed within the opening <body> tag, as close to the beginning of it as possible-->
<!-- Creation Date:10/1/2008 -->
<SCRIPT language="JavaScript">
var axel = Math.random()+"";
var a = axel * 10000000000000;
document.write('<IFRAME SRC="http://fls.doubleclick.net/activityi;src=1661533;type=f09ca686;cat=fruf0906;ord=1;num='+ a + '?" WIDTH=1 HEIGHT=1 FRAMEBORDER=0></IFRAME>');
</SCRIPT>
<NOSCRIPT>
<IFRAME SRC="http://fls.doubleclick.net/activityi;src=1661533;type=f09ca686;cat=fruf0906;ord=1;num=1?" WIDTH=1 HEIGHT=1 FRAMEBORDER=0></IFRAME>
</NOSCRIPT>
<!-- End of DoubleClick Spotlight Tag: Please do not remove--




<!-- Start of DoubleClick Spotlight Tag: Please do not remove-->
<!-- Activity Name for this tag is:FRU F09 Display Campaign Landing Page (standard) -->
<!-- Web site URL where tag should be placed: http://www.millsberry.com -->
<!-- This tag must be placed within the opening <body> tag, as close to the beginning of it as possible-->
<!-- Creation Date:10/1/2008 -->
<SCRIPT language="JavaScript">
var axel = Math.random()+"";
var a = axel * 10000000000000;
document.write('<IFRAME SRC="http://fls.doubleclick.net/activityi;src=1661533;type=f09ca686;cat=fruf0892;ord='+ a + '?" WIDTH=1 HEIGHT=1 FRAMEBORDER=0></IFRAME>');
</SCRIPT>
<NOSCRIPT>
<IFRAME SRC="http://fls.doubleclick.net/activityi;src=1661533;type=f09ca686;cat=fruf0892;ord=1?" WIDTH=1 HEIGHT=1 FRAMEBORDER=0></IFRAME>
</NOSCRIPT>
<!-- End of DoubleClick Spotlight Tag: Please do not remove-->>

</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='footer'>
    
<div id="ad_spot">
    <a href="javascript:void(0);"  onMouseOver="showspot(); return false;" onMouseOut="hidespot(); return false;" >
        <img src="http://graphics.millsberry.com/site_gfx/adSpot_icon.gif" width="30" height="25"  border="0"/>
    </a>
</div>
<div id="warning" style="position:absolute; visibility:hidden;">
    <img src="http://graphics.millsberry.com/site_gfx/adSpot_popup.gif" hspace="10" width="258" height="49" alt="" border="0"/>
</div>
MILLSBERRY &reg;, characters, logos, product names 
and all related indicia are trademarks of Mills Online, Inc., &copy; 
2004-2008.<BR> &reg; denotes Reg. US Pat. & TM Office. All rights 
reserved.<br>
Use of this site signifies your acceptance of the <a href='/town_hall/terms.phtml'><b>Terms and Conditions</b></a>.
Please view our <a href='/town_hall/terms.phtml'><b>Privacy Policy</b></a>.<br>
<br>
<table border="0" align="center"><tr><td rowspan="2"><img src="http://graphics.millsberry.com/site_gfx/dc_comics_icon.gif" width="58" height="51"  border="0" align="top"/></td>
<td>BATMAN<br>(s08)</td><td> and all related characters and elements are trademarks of and &copy;  <strong>DC Comics</strong>.<br>&nbsp;</td>
</tr></table>

</div>
</div>
<div id='bottom'>&nbsp;</div>
</div>
</body>
</html>
