<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
<HEAD>
	<TITLE>Clue Archive</TITLE>
  <LINK REL="stylesheet" TYPE="text/css" HREF="http://www.millsberry.com/styles.css">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</HEAD>
<BODY LEFTMARGIN=0 TOPMARGIN=0 MARGINWIDTH=0 MARGINHEIGHT=0 ALIGN="LEFT" BACKGROUND="http://www.millsberry.com/images/site_gfx/tile_mill.gif">

<TABLE BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="100%" HEIGHT="100%" BORDERCOLOR="#000066">
       <TR BGCOLOR="#F24F13">
         <TD HEIGHT="300" VALIGN="TOP" COLSPAN="2"><IMG SRC="http://graphics.millsberry.com/site_gfx/interiors/gazette/ads/ad_charmhint_3_v1.gif" WIDTH='285'></TD>
      </TR>
       <TR BGCOLOR="#F24F13">
         <TD WIDTH="150" HEIGHT="50" ALIGN="CENTER"><A HREF='/charm_clue_archive.phtml?viewID=20050413'><IMG SRC='http://graphics.millsberry.com/site_gfx/button/button_charms_2.gif' BORDER='0'></A></TD>
         <TD WIDTH="150" HEIGHT="50" ALIGN="CENTER"><A HREF='/charm_clue_archive.phtml?viewID=20050421'><IMG SRC='http://graphics.millsberry.com/site_gfx/button/button_charms_1.gif' BORDER='0'></A></TD>
    </TABLE>
</BODY>
</HTML>