<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- 10.100.56.30 -->
<html>
<head>
<meta http-equiv='imagetoolbar' content='no'>
<meta name='keywords' content="Mills,Millsbury,Milsberry,Milsbury,Millberry,Millbury,Fun games,Spanish language games,Educational games,Active games,Citizen,Cool stuff,Arcade,Music Mix,Fun,Games,Explore,Adventure,Create,Character,Buddy,Care,Academy,School,Gym,Gymnasium,Solver,Science,Project,Town,Pets,Children's games,Games for kid,Kid games,Kids games,Kid's games,Children,Safe gaming">
<title>Millsberry - Astronomy Trivia!</title>
<script type='text/javascript' src='/common.js'></script>
<link rel='shortcut icon' type='image/x-icon' href='/favicon.ico'>
<!-- Appending v=# to these files causes them to recache in the user's browser when # changes -->
<link rel='stylesheet' type='text/css' href='/css/theme/royal.css?v=2'>
<link rel='stylesheet' type='text/css' href='/css/global.css?v=2'>
<!--[if lt IE 7.00]>
<link rel='stylesheet' type='text/css' href='/css/global.ie.css?v=1'>
<![endif]-->
</head>
<body style='margin: 0; padding: 0; background-color: #E2F9DB;'>
  <table width='100%' border='0' cellpadding='0' cellspacing='0'>
		<tr>
			<td colspan='3'><img src='http://graphics.millsberry.com/site_gfx/site_images/trivia_top.gif' width='500' height='47'></td>
		</tr>
		<tr>
			<td><img src='http://graphics.millsberry.com/site_gfx/site_images/trivia_left.gif' width='37' height='416'></td>
			<td><TABLE BORDER='0' CELLPADDING='0' CELLSPACING='0' WIDTH='426' HEIGHT='416'><TR BGCOLOR='#60C633'><TD HEIGHT='100' ALIGN='LEFT' COLSPAN='3'><FONT COLOR='#FFFFFF'><B><DIV ALIGN='CENTER'>Welcome to the Millsberry Astronomy Challenge!</DIV>This trivia quiz will test your knowledge of our skies!  If you need any help finding the correct answer, please visit the Millsberry Academy Library, which contains all the books you will need to answer the Astronomy Challenge questions.</B></FONT></TD></TR><TR HEIGHT='22'><TD COLSPAN='3'><IMG SRC='http://graphics.millsberry.com/site_gfx/site_images/trivia_div.gif' WIDTH='426' HEIGHT='22'></TD></TR><TR HEIGHT='256' BGCOLOR='#E2F9DB'><TD VALIGN='TOP' COLSPAN='3'><FONT COLOR='#000000'>Remember, everyone who shows their astronomy expertise by earning a score of 100%  
              on the trivia quiz will be awarded their very own specially colored lab coat, lab   
              goggles, and box of Cinnamon Toast Crunch&reg; cereal (generously provided by the event  
              sponsor, Cinnamon Toast Crunch breakfast cereal).   Also, those receiving a perfect  
              score (and wearing their new lab coat and goggles, of course) will get exclusive  
              (and secret) access to a space game, which is accessed through Mr. Fort's science lab! 
              <BR><BR> 
              By the way, if you don't get a perfect score on the first try, don't worry.  You can  
              take the Millsberry Astronomy Challenge as many times as you need until you get 100%. 
              <BR><BR> 
              All set?  Then just click <A HREF='/academy/lab/trivia.phtml?st=1'>Play</A> to go right to the game!  </FONT></TD></TR><TR HEIGHT='33'><TD ALIGN='CENTER' WIDTH='33%'>&nbsp;</TD><TD ALIGN='CENTER' WIDTH='33%'><A HREF='/academy/lab/trivia.phtml?st=1'><IMG SRC='http://graphics.millsberry.com/site_gfx/play.gif' BORDER='0' onMouseOver="src='http://graphics.millsberry.com/site_gfx/play_over.gif';" onMouseOut="src='http://graphics.millsberry.com/site_gfx/play.gif';" onMouseDown="src='http://graphics.millsberry.com/site_gfx/play_down.gif';"></A></TD><TD ALIGN='CENTER' WIDTH='33%'><A HREF='/academy/lab/trivia.phtml?intro=1'><IMG SRC='http://graphics.millsberry.com/site_gfx/next.gif' BORDER='0' onMouseOver="src='http://graphics.millsberry.com/site_gfx/next_over.gif';" onMouseOut="src='http://graphics.millsberry.com/site_gfx/next.gif';" onMouseDown="src='http://graphics.millsberry.com/site_gfx/next_down.gif';"></A></TD></TR><TR HEIGHT='5'><TD COLSPAN='3'></TD></TR></TABLE></td>
			<td><img src='http://graphics.millsberry.com/site_gfx/site_images/trivia_right.gif' width='37' height='416'></TD>
		</tr>
		<tr>
			<td colspan='3'><img src='http://graphics.millsberry.com/site_gfx/site_images/trivia_bottom.gif' width='500' height='37'></td>
		</tr>
	</table>
</body>
</html>