<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- 10.100.56.28 -->
<html>
<head>
<meta http-equiv='imagetoolbar' content='no'>
<meta name='keywords' content="Mills,Millsbury,Milsberry,Milsbury,Millberry,Millbury,Fun games,Spanish language games,Educational games,Active games,Citizen,Cool stuff,Arcade,Music Mix,Fun,Games,Explore,Adventure,Create,Character,Buddy,Care,Academy,School,Gym,Gymnasium,Solver,Science,Project,Town,Pets,Children's games,Games for kid,Kid games,Kids games,Kid's games,Children,Safe gaming">
<title>Millsberry - High Scores</title>
<script type='text/javascript' src='/common.js'></script>
<link rel='shortcut icon' type='image/x-icon' href='/favicon.ico'>
<!-- Appending v=# to these files causes them to recache in the user's browser when # changes -->
<link rel='stylesheet' type='text/css' href='/css/theme/royal.css?v=2'>
<link rel='stylesheet' type='text/css' href='/css/template.css?v=4'>
<link rel='stylesheet' type='text/css' href='/css/global.css?v=1'>
<!--[if lt IE 7.00]>
<link rel='stylesheet' type='text/css' href='/css/template.ie.css?v=1'>
<link rel='stylesheet' type='text/css' href='/css/global.ie.css?v=1'>
<![endif]-->
<link rel='stylesheet' type='text/css' href='/css/gamepages/hiscores.css?v=1'>
</head>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<body>

<!--<div id='leaderboard'><h2>Leader Board</h2></div>-->
<div id='top'>
<a href='/index.phtml'><span id='logo'>&nbsp;</span></a>
<div id='layout_head'>
	<div id='login_info'><form name='login' method='post' action='/gamepages/hiscores.phtml?game_id=440'>
Username <input type='text' name='login_username' size='10'>&nbsp;&nbsp;
Password <input type='password' name='login_pass' size='10'>
<input type='submit' value='Go'>
</form></div>
	<div id='stripe'>
		<div id='stripe_shortcuts'>
			<table width='95' border='0' cellpadding='0' cellspacing='0'><tr>
				<td width='72'></td>
				<td width='23' valign='bottom'></td>
			</tr></table>
		</div>
		<div id='stripe_search'>
			<form name='search' action='/site_search.phtml' method='get'>
			<table width='340' border='0' cellpadding='0' cellspacing='0'><tr>
				<td width='135' align='right'>Address Book&nbsp;</td>
				<td width='105' align='left' valign='middle'><input type='text' name='search' size='15'></td>
				<td width='30' align='center' valign='bottom'><a href='javascript: document.search.submit();' class='stripe_button'><span id='search_button'>&nbsp;</span></a></td>
				<td width='60' align='right'><a href='/town_hall/faq.phtml'>Help</a></td>
			</tr></table>
			</form>
		</div>
	</div>
</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='body'>
<div id='layout_body'>
<div id='side_nav'>
<a href='/main_map.phtml' class='nav_button_hover'><span id='nav_the_city' class='nav_button'>&nbsp;</span></a>
<a href='/main_map.phtml?location=downtown' class='nav_button_hover'><span id='nav_downtown' class='nav_button'>&nbsp;</span></a>
<a href='/tour.phtml' class='nav_button_hover'><span id='nav_tour' class='nav_button'>&nbsp;</span></a>
<a href='/signup.phtml' class='nav_button_hover'><span id='nav_signup' class='nav_button'>&nbsp;</span></a>
<a href='/complex/arcade.phtml' class='nav_button_hover'><span id='nav_arcade' class='nav_button'>&nbsp;</span></a>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='main'>

<div id='interior'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/game_interiors/interior_440_v3.swf', '600', '400', '&unixTimeStamp=1157087801&serverTimeOffset=28800', '7', 'noscale');</script></div>
<div id='interior_stripe'>High Scores : <a href='flashgame_ctp.phtml?game_id=440'>Bumper Boats</a></div>
<div id='content'>

<table id='high_scores' width='100%' border='0' cellpadding='5' cellspacing='0'>
<tr>
<td class='high_score_header' width='10%' align='center' bgcolor='silver'>Rank</td>
<td class='high_score_header' align='center' bgcolor='silver'>Username</td>
<td class='high_score_header' align='center' bgcolor='silver'>Date</td>
<td class='high_score_header' width='20%' align='center' bgcolor='silver'>Score</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>1</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=cristiano11'>cristiano11</a></td>
<td align='center' bgcolor='#EEEEEE'>08/31/2006</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>2,124</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>2</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=jessdirt'>jessdirt</a></td>
<td align='center' bgcolor='#FFFFFF'>08/30/2006</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>1,611</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>3</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=princessnlt'>princessnlt</a></td>
<td align='center' bgcolor='#EEEEEE'>08/28/2006</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,542</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>4</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=cashjp'>cashjp</a></td>
<td align='center' bgcolor='#FFFFFF'>08/29/2006</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>1,527</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>5</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=sahak'>sahak</a></td>
<td align='center' bgcolor='#EEEEEE'>08/30/2006</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,410</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>6</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=sailerc'>sailerc</a></td>
<td align='center' bgcolor='#FFFFFF'>08/30/2006</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>1,206</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>7</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=dj8890'>dj8890</a></td>
<td align='center' bgcolor='#EEEEEE'>08/30/2006</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,194</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>8</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=adore58'>adore58</a></td>
<td align='center' bgcolor='#FFFFFF'>08/30/2006</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>1,170</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>9</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=kevinsinho'>kevinsinho</a></td>
<td align='center' bgcolor='#EEEEEE'>08/31/2006</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,083</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>10</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=naoca'>naoca</a></td>
<td align='center' bgcolor='#FFFFFF'>08/31/2006</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>1,050</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>11</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=shade9752'>shade9752</a></td>
<td align='center' bgcolor='#EEEEEE'>08/29/2006</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,026</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>12</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=peirce19'>peirce19</a></td>
<td align='center' bgcolor='#FFFFFF'>08/31/2006</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>996</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>13</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=mcr_freak_51'>mcr_freak_51</a></td>
<td align='center' bgcolor='#EEEEEE'>08/31/2006</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>984</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>14</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=danielle0808'>danielle0808</a></td>
<td align='center' bgcolor='#FFFFFF'>08/29/2006</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>981</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>15</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=j7j78'>j7j78</a></td>
<td align='center' bgcolor='#EEEEEE'>08/28/2006</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>969</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>16</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=awvex'>awvex</a></td>
<td align='center' bgcolor='#FFFFFF'>08/30/2006</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>969</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>17</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=mjf120'>mjf120</a></td>
<td align='center' bgcolor='#EEEEEE'>08/29/2006</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>960</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>18</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=audrey1belle2leland3'>audrey1belle2leland3</a></td>
<td align='center' bgcolor='#FFFFFF'>08/30/2006</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>960</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>19</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=pinkdog86'>pinkdog86</a></td>
<td align='center' bgcolor='#EEEEEE'>08/30/2006</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>945</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>20</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=lefty5'>lefty5</a></td>
<td align='center' bgcolor='#FFFFFF'>08/30/2006</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>879</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>21</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=howru01'>howru01</a></td>
<td align='center' bgcolor='#EEEEEE'>08/30/2006</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>816</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>22</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=traceymae13allday'>traceymae13allday</a></td>
<td align='center' bgcolor='#FFFFFF'>08/30/2006</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>654</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>23</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=little_luv101'>little_luv101</a></td>
<td align='center' bgcolor='#EEEEEE'>08/30/2006</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>585</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>24</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=bigfooter'>bigfooter</a></td>
<td align='center' bgcolor='#FFFFFF'>08/30/2006</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>540</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>25</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=punisher15'>punisher15</a></td>
<td align='center' bgcolor='#EEEEEE'>09/01/2006</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>531</td>
</tr>
</table></div></div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='footer'>
MILLSBERRY &reg;, characters, logos, product names and all related indicia are trademarks of Mills Online, Inc., &copy; 2004-2006.<BR> &reg; denotes Reg. US Pat. & TM Office. All rights reserved.<br>Use of this site signifies your acceptance of the <a href='/town_hall/terms.phtml'><b>Terms and Conditions</b></a>.<br>Please view our <a href='/town_hall/terms.phtml'><b>Privacy Policy</b></a>.
</div>
</div>
<div id='bottom'>&nbsp;</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='debug'>
</div>
</body>
</html>
