<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
<HEAD>
	<TITLE>Millsberry - Main</TITLE>
  <LINK REL="stylesheet" TYPE="text/css" HREF="http://www.millsberry.com/styles.css">
  </HEAD>
<BODY LEFTMARGIN=0 TOPMARGIN=0 MARGINWIDTH=0 MARGINHEIGHT=0 BACKGROUND='http://www.millsberry.com/images/site_gfx/tile_mill.gif'>
<TABLE BORDER="0" HEIGHT="100%" WIDTH="100%" ALIGN="LEFT" CELLSPACING="0" CELLPADDING="0">
  <TR>
    <TD ROWSPAN='2'><A HREF='http://www.millsberry.com'><IMG SRC="http://www.millsberry.com/images/site_gfx/logo.gif" onMouseOut="src='http://www.millsberry.com/images/site_gfx/logo.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/logo_over.gif';" BORDER="0" ALT="Back to MAIN"></A></TD>
    <TD WIDTH="650" HEIGHT="55" VALIGN="TOP" BGCOLOR='#000000'>
      <TABLE BORDER='0' CELLPADDING='0' CELLSPACING='0'>
        <TR>
          <TD>
            <A HREF="http://www.millsberry.com/home/?r=12730"><IMG SRC="http://www.millsberry.com/images/site_gfx/visit_home.gif" BORDER="0" ALT="Visit your Home!" onMouseOut="src='http://www.millsberry.com/images/site_gfx/visit_home.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/visit_home_over.gif';"></A>
          </TD>
          <TD>
            <A HREF="http://www.millsberry.com/main_map.phtml?location=downtown"><IMG SRC="http://www.millsberry.com/images/site_gfx/visit_shopping.gif" BORDER="0" ALT="Visit the Town Center!" onMouseOut="src='http://www.millsberry.com/images/site_gfx/visit_shopping.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/visit_shopping_over.gif';"></A>
          </TD>
          <TD>
            <A HREF="http://www.millsberry.com/gamepages/hiscores.phtml"><IMG SRC="http://www.millsberry.com/images/site_gfx/visit_hi_scores.gif" BORDER="0" ALT="Visit the Hi Scores!" onMouseOut="src='http://www.millsberry.com/images/site_gfx/visit_hi_scores.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/visit_hi_scores_over.gif';"></A>
          </TD>
          <TD>
            <A HREF="http://www.millsberry.com/town_hall/faq.phtml"><IMG SRC="http://www.millsberry.com/images/site_gfx/visit_faq.gif" BORDER="0" ALT="Visit the Help Pages!" onMouseOut="src='http://www.millsberry.com/images/site_gfx/visit_faq.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/visit_faq_over.gif';"></A>
          </TD>
        </TR>
        <FORM NAME='login' ACTION='http://www.millsberry.com/index.phtml' method='post'>
        <TR>
          <TD COLSPAN='4' VALIGN='bottom'>
            <FONT COLOR="#FFFFFF">
              <B>
                &nbsp;&nbsp;&nbsp;
                Username
                       <input type='text' name='login_username' SIZE='10'>
                       Password
                       <input type='password' name='login_pass' SIZE='10'>&nbsp;
                       <input type='image' src='http://www.millsberry.com/images/site_gfx/visit_log_in.gif' HEIGHT=20 name='login' value='go' border='0' align='top' onMouseOut="src='http://www.millsberry.com/images/site_gfx/visit_log_in.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/visit_log_in_over.gif';"> <A HREF='http://www.millsberry.com/town_hall/support.phtml?q=pw'><FONT COLOR='#FFFFFF' class='smallfont'>[ forgot your password? ]</FONT></A>              </B>
            </FONT>
          </TD>
        </TR>
        </FORM>
      </TABLE>
    </TD>
    <TD WIDTH="100%" BGCOLOR='#000000' COLSPAN='2'>
      
    </TD>
  </TR>
  <FORM NAME='search' ACTION='http://www.millsberry.com/site_search.phtml' method='get'>
  <TR>
    <TD COLSPAN='3' WIDTH="600" HEIGHT="25" VALIGN="TOP" ALIGN="LEFT" CLASS="header_stripe_TD"><TABLE WIDTH='100%' BORDER='0' CELLPADDING='0' CELLSPACING='0'><TR><TD><IMG SRC='http://www.millsberry.com/images/site_gfx/header_stripe.gif'><IMG SRC='http://www.millsberry.com/images/site_gfx/slice_11.gif'></TD><TD ALIGN='RIGHT' CLASS='header_stripe_TD'>Search:<INPUT TYPE='text' NAME='search'></TD><TD><input type='image' src='http://www.millsberry.com/images/site_gfx/visit_go.gif' HEIGHT='25' name='login' border='0' align='top' onMouseOut="src='http://www.millsberry.com/images/site_gfx/visit_go.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/visit_go_over.gif';" CLASS='checkbox'></TD></TR></TABLE></TD>
  </TR>
  </FORM>
  <TR>
    <TD WIDTH="150" VALIGN="TOP" HEIGHT="100%" CLASS="sidenav_TD" background="http://www.millsberry.com/images/site_gfx/left_side_nav_stripe.gif">
          <TABLE BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH='100%'>
        <TR>
          <TD ALIGN='CENTER' VALIGN='TOP'>
              
  <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" width="150" height="70">
  <param name="allowScriptAccess" value="sameDomain" />
  <param name=movie value="http://www.millsberry.com/images/site_gfx/sideNavButton_v1.swf?sideNavButtonXML=<button><name>sideNavButton_mc</name><label><text>%3CP%20ALIGN%3D%22CENTER%22%3E%3CFONT%20SIZE%3D%226%22%3E%3CP%3E%26nbsp%3B%3C%2FP%3E%3C%2FFONT%3E%3CFONT%20SIZE%3D%2240%22%20COLOR%3D%22%23FFFFFF%22%3EMap%3C%2FFONT%3E%3C%2FP%3E</text><dropShadow><x>3</x><y>3</y><colorTransform>0,0,0,0,0,0,50,0</colorTransform></dropShadow></label><url>http%3A%2F%2Fwww.millsberry.com%2Fmain_map.phtml</url><target>_self</target></button>">
  <param name=quality value=high>
  <param name=menu value=false>
  <param name="wmode" value="transparent" />
  <param name=scale value=noscale>
  <param name="salign" value="lt" />
  <embed src="http://www.millsberry.com/images/site_gfx/sideNavButton_v1.swf?sideNavButtonXML=<button><name>sideNavButton_mc</name><label><text>%3CP%20ALIGN%3D%22CENTER%22%3E%3CFONT%20SIZE%3D%226%22%3E%3CP%3E%26nbsp%3B%3C%2FP%3E%3C%2FFONT%3E%3CFONT%20SIZE%3D%2240%22%20COLOR%3D%22%23FFFFFF%22%3EMap%3C%2FFONT%3E%3C%2FP%3E</text><dropShadow><x>3</x><y>3</y><colorTransform>0,0,0,0,0,0,50,0</colorTransform></dropShadow></label><url>http%3A%2F%2Fwww.millsberry.com%2Fmain_map.phtml</url><target>_self</target></button>" quality="high" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" scale="exactfit" width="150" height="70" wmode="transparent">
  </embed>
  </object>
  <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" width="150" height="70">
  <param name="allowScriptAccess" value="sameDomain" />
  <param name=movie value="http://www.millsberry.com/images/site_gfx/sideNavButton_v1.swf?sideNavButtonXML=<button><name>sideNavButton_mc</name><label><text>%3CP%20ALIGN%3D%22CENTER%22%3E%3CFONT%20SIZE%3D%226%22%3E%3CP%3E%26nbsp%3B%3C%2FP%3E%3C%2FFONT%3E%3CFONT%20SIZE%3D%2240%22%20COLOR%3D%22%23FFFFFF%22%3EGames%3C%2FFONT%3E%3C%2FP%3E</text><dropShadow><x>3</x><y>3</y><colorTransform>0,0,0,0,0,0,50,0</colorTransform></dropShadow></label><url>http%3A%2F%2Fwww.millsberry.com%2Fgamepages%2Fgames_list.phtml</url><target>_self</target></button>">
  <param name=quality value=high>
  <param name=menu value=false>
  <param name="wmode" value="transparent" />
  <param name=scale value=noscale>
  <param name="salign" value="lt" />
  <embed src="http://www.millsberry.com/images/site_gfx/sideNavButton_v1.swf?sideNavButtonXML=<button><name>sideNavButton_mc</name><label><text>%3CP%20ALIGN%3D%22CENTER%22%3E%3CFONT%20SIZE%3D%226%22%3E%3CP%3E%26nbsp%3B%3C%2FP%3E%3C%2FFONT%3E%3CFONT%20SIZE%3D%2240%22%20COLOR%3D%22%23FFFFFF%22%3EGames%3C%2FFONT%3E%3C%2FP%3E</text><dropShadow><x>3</x><y>3</y><colorTransform>0,0,0,0,0,0,50,0</colorTransform></dropShadow></label><url>http%3A%2F%2Fwww.millsberry.com%2Fgamepages%2Fgames_list.phtml</url><target>_self</target></button>" quality="high" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" scale="exactfit" width="150" height="70" wmode="transparent">
  </embed>
  </object><object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" width="140" height="350" id="item_loader" align="middle">
<param name="allowScriptAccess" value="sameDomain" />
<param name="movie" value="http://www.millsberry.com/images/item_loader_v3.swf?itemLoaderXML=<?xml version='1.0' ?><message success='1' text = ''><item><frame>1</frame><objectName>item</objectName><url>http%3A%2F%2Fwww.millsberry.com%2Fimages%2Fsite_gfx%2Fprebuddy.swf</url></item><button><objectName>button</objectName><url>http%3A%2F%2Fwww.millsberry.com%2Fsignup.phtml</url><window>_self</window><useBorderAsRollover>1</useBorderAsRollover></button><border><objectName>border</objectName><lineColor>0x000099</lineColor><size>4</size></border><preloader><objectName>preloader</objectName><width>140</width><height>350</height></preloader></message>"/>
<param name="loop" value="false" />
<param name="menu" value="true" />
<param name="quality" value="high" />
<param name="wmode" value="transparent" />
<param name="devicefont" value="true" />
<param name="bgcolor" value="#666666" />
<embed src="http://www.millsberry.com/images/item_loader_v3.swf?itemLoaderXML=<?xml version='1.0' ?><message success='1' text = ''><item><frame>1</frame><objectName>item</objectName><url>http%3A%2F%2Fwww.millsberry.com%2Fimages%2Fsite_gfx%2Fprebuddy.swf</url></item><button><objectName>button</objectName><url>http%3A%2F%2Fwww.millsberry.com%2Fsignup.phtml</url><window>_self</window><useBorderAsRollover>1</useBorderAsRollover></button><border><objectName>border</objectName><lineColor>0x000099</lineColor><size>4</size></border><preloader><objectName>preloader</objectName><width>140</width><height>350</height></preloader></message>" width="140" height="350" wmode="transparent"/>
</object>

  <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" width="150" height="70">
  <param name="allowScriptAccess" value="sameDomain" />
  <param name=movie value="http://www.millsberry.com/images/site_gfx/sideNavButton_v1.swf?sideNavButtonXML=<button><name>sideNavButton_mc</name><label><text>%3CP%20ALIGN%3D%22CENTER%22%3E%3CFONT%20SIZE%3D%2215%22%3E%3CP%3E%26nbsp%3B%3C%2FP%3E%3C%2FFONT%3E%3CFONT%20SIZE%3D%2228%22%20COLOR%3D%22%23FFFFFF%22%3ESign%20Up%21%21%3C%2FFONT%3E%3C%2FP%3E</text><dropShadow><x>3</x><y>3</y><colorTransform>0,0,0,0,0,0,50,0</colorTransform></dropShadow></label><url>http%3A%2F%2Fwww.millsberry.com%2Fsignup.phtml</url><target>_self</target></button>">
  <param name=quality value=high>
  <param name=menu value=false>
  <param name="wmode" value="transparent" />
  <param name=scale value=noscale>
  <param name="salign" value="lt" />
  <embed src="http://www.millsberry.com/images/site_gfx/sideNavButton_v1.swf?sideNavButtonXML=<button><name>sideNavButton_mc</name><label><text>%3CP%20ALIGN%3D%22CENTER%22%3E%3CFONT%20SIZE%3D%2215%22%3E%3CP%3E%26nbsp%3B%3C%2FP%3E%3C%2FFONT%3E%3CFONT%20SIZE%3D%2228%22%20COLOR%3D%22%23FFFFFF%22%3ESign%20Up%21%21%3C%2FFONT%3E%3C%2FP%3E</text><dropShadow><x>3</x><y>3</y><colorTransform>0,0,0,0,0,0,50,0</colorTransform></dropShadow></label><url>http%3A%2F%2Fwww.millsberry.com%2Fsignup.phtml</url><target>_self</target></button>" quality="high" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" scale="exactfit" width="150" height="70" wmode="transparent">
  </embed>
  </object>          </TD>
        </TR>
      </TABLE>    </TD>
    <TD WIDTH="650" HEIGHT="100%" VALIGN="TOP" ALIGN='LEFT'><TABLE BORDER='0' CELLPADDING='0' CELLSPACING='5' WIDTH='100%' CLASS='content_TD'>
        <TR>
          <TD ROWSPAN='2' WIDTH='11' ALIGN='CENTER' BACKGROUND='http://www.millsberry.com/images/site_gfx/vertline.gif'>
            <IMG SRC='http://www.millsberry.com/images/site_gfx/vertline.gif'>
          </TD>
          <TD ALIGN='CENTER' WIDTH='300' VALIGN='TOP'><IMG SRC='http://www.millsberry.com/images/site_gfx/gazette_logo.gif'></TD>
          <TD ROWSPAN='2' WIDTH='11' ALIGN='CENTER' BACKGROUND='http://www.millsberry.com/images/site_gfx/vertline.gif'>
            <IMG SRC='http://www.millsberry.com/images/site_gfx/vertline.gif'>
          </TD>
          <TD ROWSPAN='2' WIDTH='100%' ALIGN='CENTER' VALIGN='TOP'>
            <TABLE BORDER='0' CELLPADDING='0' CELLSPACING='0' WIDTH='100%'>
              <TR>
                <TD ALIGN='CENTER'>
                  <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" width="250" height="168" id="item_loader" align="middle">
<param name="allowScriptAccess" value="sameDomain" />
<param name="movie" value="http://www.millsberry.com/images/item_loader_v3.swf?itemLoaderXML=<?xml version='1.0' ?><message success='1' text = ''><item><frame>1</frame><objectName>item</objectName><url>http%3A%2F%2Fwww.millsberry.com%2Fimages%2Fsite_gfx%2Finteriors%2Fint_metropark_v1.swf</url><scale>42</scale><_x>0</_x><_y>0</_y></item><preloader><objectName>preloader</objectName><width>250</width><height>168</height></preloader></message>"/>
<param name="loop" value="false" />
<param name="menu" value="true" />
<param name="quality" value="high" />
<param name="wmode" value="transparent" />
<param name="devicefont" value="true" />
<param name="bgcolor" value="#666666" />
<embed src="http://www.millsberry.com/images/item_loader_v3.swf?itemLoaderXML=<?xml version='1.0' ?><message success='1' text = ''><item><frame>1</frame><objectName>item</objectName><url>http%3A%2F%2Fwww.millsberry.com%2Fimages%2Fsite_gfx%2Finteriors%2Fint_metropark_v1.swf</url><scale>42</scale><_x>0</_x><_y>0</_y></item><preloader><objectName>preloader</objectName><width>250</width><height>168</height></preloader></message>" width="250" height="168" wmode="transparent"/>
</object>

                </TD>
              </TR>
              <TR>
                <TD ALIGN='LEFT' CLASS='header_stripe_TD'>
                  &nbsp;Home Tour:
                </TD>
              </TR>
              <TR>
                <TD ALIGN='LEFT' class='article_body'>1.) <A HREF='http://www.millsberry.com/home/?user=kaykk'>kaykk</A><BR>2.) <A HREF='http://www.millsberry.com/home/?user=amanda43'>amanda43</A><BR>3.) <A HREF='http://www.millsberry.com/home/?user=ashlyn'>ashlyn</A><BR>4.) <A HREF='http://www.millsberry.com/home/?user=aod911'>aod911</A><BR>5.) <A HREF='http://www.millsberry.com/home/?user=pinkvarsity17'>pinkvarsity17</A><BR>          </TD>
              </TR>
              <TR>
                <TD>
                  <hr size='1' noshade>
                </TD>
              </TR>        <TR>
                <TD ALIGN='CENTER'>
                  <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" width="250" height="168" id="item_loader" align="middle">
<param name="allowScriptAccess" value="sameDomain" />
<param name="movie" value="http://www.millsberry.com/images/item_loader_v3.swf?itemLoaderXML=<?xml version='1.0' ?><message success='1' text = ''><item><frame>1</frame><objectName>item</objectName><url>http%3A%2F%2Fwww.millsberry.com%2Fgamepages%2Fimages%2Finterior_19_v2.swf</url><scale>42</scale><_x>0</_x><_y>0</_y></item><button><objectName>button</objectName><url>http%3A%2F%2Fwww.millsberry.com%2Fgamepages%2Fflashgame_ctp.phtml%3Fgame_id%3D19</url><window>_self</window><useBorderAsRollover>1</useBorderAsRollover></button><border><objectName>border</objectName><lineColor>0x000099</lineColor><size>4</size></border><preloader><objectName>preloader</objectName><width>250</width><height>168</height></preloader></message>"/>
<param name="loop" value="false" />
<param name="menu" value="true" />
<param name="quality" value="high" />
<param name="wmode" value="transparent" />
<param name="devicefont" value="true" />
<param name="bgcolor" value="#666666" />
<embed src="http://www.millsberry.com/images/item_loader_v3.swf?itemLoaderXML=<?xml version='1.0' ?><message success='1' text = ''><item><frame>1</frame><objectName>item</objectName><url>http%3A%2F%2Fwww.millsberry.com%2Fgamepages%2Fimages%2Finterior_19_v2.swf</url><scale>42</scale><_x>0</_x><_y>0</_y></item><button><objectName>button</objectName><url>http%3A%2F%2Fwww.millsberry.com%2Fgamepages%2Fflashgame_ctp.phtml%3Fgame_id%3D19</url><window>_self</window><useBorderAsRollover>1</useBorderAsRollover></button><border><objectName>border</objectName><lineColor>0x000099</lineColor><size>4</size></border><preloader><objectName>preloader</objectName><width>250</width><height>168</height></preloader></message>" width="250" height="168" wmode="transparent"/>
</object>

                </TD>
              </TR>
              <TR>
                <TD ALIGN='LEFT' CLASS='header_stripe_TD'>
                  &nbsp;High Scores
                  <BR>
                  &nbsp;(Peabody Park Cleanup):
                </TD>
              </TR>
              <TR>
                <TD class='article_body'>
                  <TABLE BORDER='0' CELLPADDING='0' CELLSPACING='0' WIDTH='100%'>
                    <TR BGCOLOR='#EEEEEE'>
                      <TD>
                        <A HREF='http://www.millsberry.com/home/?user=sftbllfrkk'>sftbllfrkk</A>: 
                      </TD>
                      <TD ALIGN='LEFT'>
                       5298 pts
                      </TD>
                    </TR>
                    <TR BGCOLOR='#FFFFFF'>
                      <TD>
                        <A HREF='http://www.millsberry.com/home/?user=glampixie'>glampixie</A>: 
                      </TD>
                      <TD ALIGN='LEFT'>
                       4467 pts
                      </TD>
                    </TR>
                    <TR BGCOLOR='#EEEEEE'>
                      <TD>
                        <A HREF='http://www.millsberry.com/home/?user=kryptor'>kryptor</A>: 
                      </TD>
                      <TD ALIGN='LEFT'>
                       4065 pts
                      </TD>
                    </TR>
                    <TR BGCOLOR='#FFFFFF'>
                      <TD>
                        <A HREF='http://www.millsberry.com/home/?user=crzygrl279'>crzygrl279</A>: 
                      </TD>
                      <TD ALIGN='LEFT'>
                       3879 pts
                      </TD>
                    </TR>
                    <TR BGCOLOR='#EEEEEE'>
                      <TD>
                        <A HREF='http://www.millsberry.com/home/?user=joeman'>joeman</A>: 
                      </TD>
                      <TD ALIGN='LEFT'>
                       3849 pts
                      </TD>
                    </TR>       </TABLE>
                </TD>
              </TR>
              <TR>
                <TD>
                  <hr size='1' noshade>
                </TD>
              </TR>
              <TR>
                <TD ALIGN='CENTER'>
                  
  <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=<?=6?>,0,0,0" width="250" height="168">
  <param name="allowScriptAccess" value="sameDomain" />
  <param name=movie value="http://www.millsberry.com/images/buddy/buddy_featured_v2.swf?buddyScriptURL=http://www.millsberry.com/buddy/process_buddy.phtml&userName=Spax">
  <param name=quality value="high">
  <param name=menu value=false>
  <param name="wmode" value="transparent" />
  <param name=scale value="exactfit">
  <param name="salign" value="lt" />
  <embed src="http://www.millsberry.com/images/buddy/buddy_featured_v2.swf?buddyScriptURL=http://www.millsberry.com/buddy/process_buddy.phtml&userName=Spax" quality="high" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" scale="exactfit" width="250" height="168" wmode="transparent">
  </embed>
  </object>
                </TD>
              </TR>
              <TR>
                <TD ALIGN='LEFT' CLASS='header_stripe_TD'>
                  &nbsp;Featured Citizen:
                </TD>
              </TR>
              <TR>
                <TD class='article_body'>
<p>Have you met Alesam, Millsberry's number one actress?  You may have seen her hanging out at the park, her favorite place to read, 
listen to music, or even do one of those tough crossword puzzles in the Millsberry Weekly.  Or maybe you share a class with her at 
Millsberry Academy? She's the outgoing one with the beautiful voice in the Choir class and the truly talented thespian in the Drama 
department.  Of course, she's also the hungry one when it comes to lunch.
<p>Who wouldn't want to meet a girl as smart and creative as Millsberry's own Alesam?  Alesam loves to listen to music, 
although she also sings it as well.  She's always hanging out at the record store and listening to the latest jazz, classic rock, 
and show tunes! One of Alesam's favorite colors, black, is 
reflected in her clothes, most noticeably her signature black t-shirt bearing a red happy face.  Alesam is outgoing and charismatic, 
so be sure to say hello when you see her - or she will!
                <P>
                  Click <A HREF='./home/?vf=1&user=spax'>here</A> to find out more about her!
                </P>
                </TD>
              </TR>
              <TR>
                <TD>
                  <hr size='1' noshade>
                </TD>
              </TR>
            </TABLE>
          </TD>
          <TD ROWSPAN='2' WIDTH='11' ALIGN='CENTER' BACKGROUND='http://www.millsberry.com/images/site_gfx/vertline.gif'>
            <IMG SRC='http://www.millsberry.com/images/site_gfx/vertline.gif'>
          </TD>
        </TR>
        <TR>
          <TD WIDTH='300' ALIGN='CENTER' VALIGN='TOP'>
            <TABLE BORDER='0' CELLPADDING='0' CELLSPACING='0' WIDTH='100%'>
              <TR><TD VALIGN='TOP' HEIGHT='100%'><object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" width="300" height="200" id="item_loader" align="middle">
<param name="allowScriptAccess" value="sameDomain" />
<param name="movie" value="http://www.millsberry.com/images/item_loader_v3.swf?itemLoaderXML=<?xml version='1.0' ?><message success='1' text = ''><item><frame>1</frame><objectName>item</objectName><url>http%3A%2F%2Fwww.millsberry.com%2Fimages%2Fsite_gfx%2Finteriors%2Fint_welcome_v1.swf</url><scale>50</scale><_x>0</_x><_y>0</_y></item><button><objectName>button</objectName><url>http%3A%2F%2Fwww.millsberry.com%2Fsignup.phtml</url><window>_self</window><useBorderAsRollover>1</useBorderAsRollover></button><border><objectName>border</objectName><lineColor>0x000099</lineColor><size>4</size></border><preloader><objectName>preloader</objectName><width>300</width><height>200</height></preloader></message>"/>
<param name="loop" value="false" />
<param name="menu" value="true" />
<param name="quality" value="high" />
<param name="wmode" value="transparent" />
<param name="devicefont" value="true" />
<param name="bgcolor" value="#666666" />
<embed src="http://www.millsberry.com/images/item_loader_v3.swf?itemLoaderXML=<?xml version='1.0' ?><message success='1' text = ''><item><frame>1</frame><objectName>item</objectName><url>http%3A%2F%2Fwww.millsberry.com%2Fimages%2Fsite_gfx%2Finteriors%2Fint_welcome_v1.swf</url><scale>50</scale><_x>0</_x><_y>0</_y></item><button><objectName>button</objectName><url>http%3A%2F%2Fwww.millsberry.com%2Fsignup.phtml</url><window>_self</window><useBorderAsRollover>1</useBorderAsRollover></button><border><objectName>border</objectName><lineColor>0x000099</lineColor><size>4</size></border><preloader><objectName>preloader</objectName><width>300</width><height>200</height></preloader></message>" width="300" height="200" wmode="transparent"/>
</object>
</TD>
              </TR>
              <TR>
                <TD ALIGN='LEFT' VALIGN='TOP' CLASS='header_stripe_TD'>
                  &nbsp;Headline News:
                </TD>
              </TR>
              <TR>
                <TD ALIGN='LEFT' HEIGHT='100%' class='article_body'>
                  If you look over the hill, you’ll see the far edge of a small city called Millsberry. 
	  It used to be a small town, but recently, Millsberry has grown beyond its borders. 
	  Walk down the hill and you step into the outer neighborhoods. Just a little further, and you walk into the center of Town. 
	  <p>If you want to become a citizen, just click on the SIGN UP button to the left. 
	  <p>You'll get your own customizable home, 
	  access to the shopping district, and get to play a bunch of great games! It's completely free and only takes a second.
	  <p>Here in Millsberry, there are TONS of things to do!  Whether you want to spend your time decorating your home, 
cleaning up Peabody Park, or hanging out at Millsberry Academy -- it's all up to you!  You're in complete control!

<p>Be sure to save those Millsbucks, though!  There are loads of items to buy, including food, books, and clothes that 
your character can wear, but you'll need Millsbucks to get 'em!

<p>Don't know where to start?  Head on over to Town Hall and get acquainted with the laws here in Millsberry, or to the 
bank to activate your Millsbucks account!  There's so much to do here, so make the most out of it and go explore 
Millsberry today!</b>
                </TD>
              </TR>
            </TABLE>
          </TD>
        </TR>
      </TABLE>  </TD>
    <TD WIDTH="150" VALIGN="TOP" ALIGN='CENTER' HEIGHT="100%">
          </TD>
          <TD WIDTH='100%'>
            &nbsp;
          </TD>
  </TR>
  <TR>
    <TD COLSPAN="4" WIDTH="100%" ALIGN="CENTER" CLASS="footer_TD">
      <SPAN CLASS='footerfont'>
      MILLSBERRY, characters, logos, product names and all related indicia are trademarks of General Mills, Inc., © 2004.<BR> ® denotes Reg. US Pat. & TM Office. All rights reserved.
        <BR>
        Use of this site signifies your acceptance of the <A HREF='http://www.millsberry.com/town_hall/terms.phtml'>Terms and Conditions</A>.
        <BR>
        Please view our <A HREF='http://www.millsberry.com/town_hall/policy.phtml'>Privacy Policy</A>.
        <BR>
        Please send all comments and inquiries <A HREF='http://www.millsberry.com/town_hall/support.phtml'>here</A>.      </SPAN>
    </TD>
</TABLE>
</BODY>
</HTML>
