<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
<HEAD>
	<TITLE>Millsberry - Main</TITLE>
  <LINK REL="stylesheet" TYPE="text/css" HREF="http://www.millsberry.com/styles.css">
  </HEAD>
<BODY LEFTMARGIN=0 TOPMARGIN=0 MARGINWIDTH=0 MARGINHEIGHT=0 BACKGROUND='http://www.millsberry.com/images/site_gfx/tile_mill.gif'>
<TABLE BORDER="0" HEIGHT="100%" WIDTH="100%" ALIGN="LEFT" CELLSPACING="0" CELLPADDING="0">
  <TR>
    <TD ROWSPAN='2'><A HREF='http://www.millsberry.com'><IMG SRC="http://www.millsberry.com/images/site_gfx/logo.gif" onMouseOut="src='http://www.millsberry.com/images/site_gfx/logo.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/logo_over.gif';" BORDER="0" ALT="Back to MAIN"></A></TD>
    <TD WIDTH="650" HEIGHT="55" VALIGN="TOP" BGCOLOR='#000000'>
      <TABLE BORDER='0' CELLPADDING='0' CELLSPACING='0'>
        <TR>
          <TD>
            <A HREF="http://www.millsberry.com/home/"><IMG SRC="http://www.millsberry.com/images/site_gfx/visit_home.gif" BORDER="0" ALT="Visit your Home!" onMouseOut="src='http://www.millsberry.com/images/site_gfx/visit_home.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/visit_home_over.gif';"></A>
          </TD>
          <TD>
            <A HREF="http://www.millsberry.com/main_map.phtml?location=downtown"><IMG SRC="http://www.millsberry.com/images/site_gfx/visit_shopping.gif" BORDER="0" ALT="Visit the Town Center!" onMouseOut="src='http://www.millsberry.com/images/site_gfx/visit_shopping.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/visit_shopping_over.gif';"></A>
          </TD>
          <TD>
            <A HREF="http://www.millsberry.com/gamepages/hiscores.phtml"><IMG SRC="http://www.millsberry.com/images/site_gfx/visit_hi_scores.gif" BORDER="0" ALT="Visit the Hi Scores!" onMouseOut="src='http://www.millsberry.com/images/site_gfx/visit_hi_scores.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/visit_hi_scores_over.gif';"></A>
          </TD>
          <TD>
            <A HREF="http://www.millsberry.com/town_hall/faq.phtml"><IMG SRC="http://www.millsberry.com/images/site_gfx/visit_faq.gif" BORDER="0" ALT="Visit the Help Pages!" onMouseOut="src='http://www.millsberry.com/images/site_gfx/visit_faq.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/visit_faq_over.gif';"></A>
          </TD>
        </TR>
        <FORM NAME='login' ACTION='http://www.millsberry.com/index.phtml' method='post'>
        <TR>
          <TD COLSPAN='4' VALIGN='bottom'>
            <FONT COLOR="#FFFFFF">
              <B>
                &nbsp;&nbsp;&nbsp;
                Username
                       <input type='text' name='login_username' SIZE='10'>
                       Password
                       <input type='password' name='login_pass' SIZE='10'>&nbsp;
                       <input type='image' src='http://www.millsberry.com/images/site_gfx/visit_log_in.gif' HEIGHT=20 name='login' value='go' border='0' align='top' onMouseOut="src='http://www.millsberry.com/images/site_gfx/visit_log_in.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/visit_log_in_over.gif';"> <A HREF='http://www.millsberry.com/town_hall/support.phtml?q=pw'><FONT COLOR='#FFFFFF' class='smallfont'>[ forgot your password? ]</FONT></A>              </B>
            </FONT>
          </TD>
        </TR>
        </FORM>
      </TABLE>
    </TD>
    <TD WIDTH="100%" BGCOLOR='#000000' COLSPAN='2'>
      
    </TD>
  </TR>
  <FORM NAME='search' ACTION='http://www.millsberry.com/site_search.phtml' method='get'>
  <TR>
    <TD COLSPAN='3' WIDTH="600" HEIGHT="25" VALIGN="TOP" ALIGN="LEFT" CLASS="header_stripe_TD"><TABLE WIDTH='100%' BORDER='0' CELLPADDING='0' CELLSPACING='0'><TR><TD><IMG SRC='http://www.millsberry.com/images/site_gfx/header_stripe.gif'><IMG SRC='http://www.millsberry.com/images/site_gfx/slice_11.gif'></TD><TD ALIGN='RIGHT' CLASS='header_stripe_TD'>Phone Book:<INPUT TYPE='text' NAME='search'></TD><TD><input type='image' src='http://www.millsberry.com/images/site_gfx/visit_go.gif' HEIGHT='25' name='login' border='0' align='top' onMouseOut="src='http://www.millsberry.com/images/site_gfx/visit_go.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/visit_go_over.gif';" CLASS='checkbox'></TD></TR></TABLE></TD>
  </TR>
  </FORM>
  <TR>
    <TD WIDTH="150" VALIGN="TOP" HEIGHT="100%" CLASS="sidenav_TD" background="http://www.millsberry.com/images/site_gfx/left_side_nav_stripe.gif">
          <TABLE BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH='100%'>
        <TR>
          <TD ALIGN='CENTER' VALIGN='TOP'>
              <A HREF='http://www.millsberry.com/main_map.phtml'><IMG SRC='http://www.millsberry.com/images/site_gfx/mapbutton.gif' onMouseDown="src='http://www.millsberry.com/images/site_gfx/mapbutton_down.gif';" onMouseOut="src='http://www.millsberry.com/images/site_gfx/mapbutton.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/mapbutton_over.gif';" BORDER='0'></A><BR><A HREF='http://www.millsberry.com/gamepages/games_list.phtml'><IMG SRC='http://www.millsberry.com/images/site_gfx/gamesbutton.gif' onMouseDown="src='http://www.millsberry.com/images/site_gfx/gamesbutton_down.gif';" onMouseOut="src='http://www.millsberry.com/images/site_gfx/gamesbutton.gif';" onMouseOver="src='http://www.millsberry.com/images/site_gfx/gamesbutton_over.gif';" BORDER='0'></A><BR><A HREF='http://www.millsberry.com/signup.phtml'><IMG SRC='http://www.millsberry.com/images/site_gfx/prebuddy.gif' BORDER='1'></A><BR>
  <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" width="150" height="70">
  <param name="allowScriptAccess" value="sameDomain" />
  <param name=movie value="http://www.millsberry.com/images/site_gfx/sideNavButton_v1.swf?sideNavButtonXML=<button><name>sideNavButton_mc</name><label><text>%3CP%20ALIGN%3D%22CENTER%22%3E%3CFONT%20SIZE%3D%2215%22%3E%3CP%3E%26nbsp%3B%3C%2FP%3E%3C%2FFONT%3E%3CFONT%20SIZE%3D%2228%22%20COLOR%3D%22%23FFFFFF%22%3ESign%20Up%21%21%3C%2FFONT%3E%3C%2FP%3E</text><dropShadow><x>3</x><y>3</y><colorTransform>0,0,0,0,0,0,50,0</colorTransform></dropShadow></label><url>http%3A%2F%2Fwww.millsberry.com%2Fsignup.phtml</url><target>_self</target></button>">
  <param name=quality value=high>
  <param name=menu value=false>
  <param name="wmode" value="transparent" />
  <param name=scale value=noscale>
  <param name="salign" value="lt" />
  <embed src="http://www.millsberry.com/images/site_gfx/sideNavButton_v1.swf?sideNavButtonXML=<button><name>sideNavButton_mc</name><label><text>%3CP%20ALIGN%3D%22CENTER%22%3E%3CFONT%20SIZE%3D%2215%22%3E%3CP%3E%26nbsp%3B%3C%2FP%3E%3C%2FFONT%3E%3CFONT%20SIZE%3D%2228%22%20COLOR%3D%22%23FFFFFF%22%3ESign%20Up%21%21%3C%2FFONT%3E%3C%2FP%3E</text><dropShadow><x>3</x><y>3</y><colorTransform>0,0,0,0,0,0,50,0</colorTransform></dropShadow></label><url>http%3A%2F%2Fwww.millsberry.com%2Fsignup.phtml</url><target>_self</target></button>" quality="high" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" scale="exactfit" width="150" height="70" wmode="transparent">
  </embed>
  </object>          </TD>
        </TR>
      </TABLE>    </TD>
    <TD WIDTH="650" HEIGHT="100%" VALIGN="TOP" ALIGN='LEFT'><TABLE BORDER='0' CELLPADDING='0' CELLSPACING='5' WIDTH='100%' CLASS='content_TD'>
        <TR>
          <TD ROWSPAN='2' WIDTH='11' ALIGN='CENTER' BACKGROUND='http://www.millsberry.com/images/site_gfx/vertline.gif'>
            <IMG SRC='http://www.millsberry.com/images/site_gfx/vertline.gif'>
          </TD>
          <TD ALIGN='CENTER' WIDTH='300' VALIGN='TOP'><IMG SRC='http://www.millsberry.com/images/site_gfx/gazette_logo.gif'></TD>
          <TD ROWSPAN='2' WIDTH='11' ALIGN='CENTER' BACKGROUND='http://www.millsberry.com/images/site_gfx/vertline.gif'>
            <IMG SRC='http://www.millsberry.com/images/site_gfx/vertline.gif'>
          </TD>
          <TD ROWSPAN='2' WIDTH='100%' ALIGN='CENTER' VALIGN='TOP'>
            <TABLE BORDER='0' CELLPADDING='0' CELLSPACING='0' WIDTH='100%'>
              <TR>
                <TD ALIGN='CENTER'>
                  <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" width="250" height="168" id="item_loader" align="middle">
<param name="allowScriptAccess" value="sameDomain" />
<param name="movie" value="http://www.millsberry.com/images/item_loader_v5.swf?itemLoaderXML=<?xml version='1.0' ?><message success='1' text = ''><item><frame>1</frame><objectName>item</objectName><url>http%3A%2F%2Fwww.millsberry.com%2Fimages%2Fsite_gfx%2Finteriors%2Fint_ravenwood_v1.swf</url><scale>42</scale><x>0</x><y>0</y></item><preloader><objectName>preloader</objectName><width>250</width><height>168</height></preloader></message>"/>
<param name="loop" value="false" />
<param name="menu" value="true" />
<param name="quality" value="high" />
<param name="wmode" value="transparent" />
<param name="devicefont" value="true" />
<param name="bgcolor" value="#666666" />
<embed src="http://www.millsberry.com/images/item_loader_v5.swf?itemLoaderXML=<?xml version='1.0' ?><message success='1' text = ''><item><frame>1</frame><objectName>item</objectName><url>http%3A%2F%2Fwww.millsberry.com%2Fimages%2Fsite_gfx%2Finteriors%2Fint_ravenwood_v1.swf</url><scale>42</scale><x>0</x><y>0</y></item><preloader><objectName>preloader</objectName><width>250</width><height>168</height></preloader></message>" width="250" height="168" wmode="transparent"/>
</object>

                </TD>
              </TR>
              <TR>
                <TD ALIGN='LEFT' CLASS='header_stripe_TD'>
                  &nbsp;Home Tour:
                </TD>
              </TR>
              <TR>
                <TD ALIGN='LEFT' class='article_body'>1.) <A HREF='http://www.millsberry.com/home/?user=fryolla'>fryolla</A><BR>          </TD>
              </TR>
              <TR>
                <TD>
                  <hr size='1' noshade>
                </TD>
              </TR>        <TR>
                <TD ALIGN='CENTER'>
                  <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" width="250" height="168" id="item_loader" align="middle">
<param name="allowScriptAccess" value="sameDomain" />
<param name="movie" value="http://www.millsberry.com/images/item_loader_v5.swf?itemLoaderXML=<?xml version='1.0' ?><message success='1' text = ''><item><frame>1</frame><objectName>item</objectName><url>http%3A%2F%2Fwww.millsberry.com%2Fgamepages%2Fimages%2Finterior_12_v3.swf</url><scale>42</scale><x>0</x><y>0</y></item><button><objectName>button</objectName><url>http%3A%2F%2Fwww.millsberry.com%2Fgamepages%2Fflashgame_ctp.phtml%3Fgame_id%3D12</url><window>_self</window><useBorderAsRollover>1</useBorderAsRollover></button><border><objectName>border</objectName><lineColor>0x000099</lineColor><size>4</size></border><preloader><objectName>preloader</objectName><width>250</width><height>168</height></preloader></message>"/>
<param name="loop" value="false" />
<param name="menu" value="true" />
<param name="quality" value="high" />
<param name="wmode" value="transparent" />
<param name="devicefont" value="true" />
<param name="bgcolor" value="#666666" />
<embed src="http://www.millsberry.com/images/item_loader_v5.swf?itemLoaderXML=<?xml version='1.0' ?><message success='1' text = ''><item><frame>1</frame><objectName>item</objectName><url>http%3A%2F%2Fwww.millsberry.com%2Fgamepages%2Fimages%2Finterior_12_v3.swf</url><scale>42</scale><x>0</x><y>0</y></item><button><objectName>button</objectName><url>http%3A%2F%2Fwww.millsberry.com%2Fgamepages%2Fflashgame_ctp.phtml%3Fgame_id%3D12</url><window>_self</window><useBorderAsRollover>1</useBorderAsRollover></button><border><objectName>border</objectName><lineColor>0x000099</lineColor><size>4</size></border><preloader><objectName>preloader</objectName><width>250</width><height>168</height></preloader></message>" width="250" height="168" wmode="transparent"/>
</object>

                </TD>
              </TR>
              <TR>
                <TD ALIGN='LEFT' CLASS='header_stripe_TD'>
                  &nbsp;High Scores
                  <BR>
                  &nbsp;(Solver):
                </TD>
              </TR>
              <TR>
                <TD class='article_body'>
                  <TABLE BORDER='0' CELLPADDING='0' CELLSPACING='0' WIDTH='100%'>
                    <TR BGCOLOR='#EEEEEE'>
                      <TD>
                        <A HREF='http://www.millsberry.com/home/?user=sariana'>sariana</A>: 
                      </TD>
                      <TD ALIGN='LEFT'>
                       3732 pts
                      </TD>
                    </TR>
                    <TR BGCOLOR='#FFFFFF'>
                      <TD>
                        <A HREF='http://www.millsberry.com/home/?user=nikkheaven'>nikkheaven</A>: 
                      </TD>
                      <TD ALIGN='LEFT'>
                       3294 pts
                      </TD>
                    </TR>
                    <TR BGCOLOR='#EEEEEE'>
                      <TD>
                        <A HREF='http://www.millsberry.com/home/?user=ninadow'>ninadow</A>: 
                      </TD>
                      <TD ALIGN='LEFT'>
                       2476 pts
                      </TD>
                    </TR>
                    <TR BGCOLOR='#FFFFFF'>
                      <TD>
                        <A HREF='http://www.millsberry.com/home/?user=nikkidown'>nikkidown</A>: 
                      </TD>
                      <TD ALIGN='LEFT'>
                       2450 pts
                      </TD>
                    </TR>
                    <TR BGCOLOR='#EEEEEE'>
                      <TD>
                        <A HREF='http://www.millsberry.com/home/?user=admin'>admin</A>: 
                      </TD>
                      <TD ALIGN='LEFT'>
                       2432 pts
                      </TD>
                    </TR>       </TABLE>
                </TD>
              </TR>
              <TR>
                <TD>
                  <hr size='1' noshade>
                </TD>
              </TR>
              <TR>
                <TD ALIGN='CENTER'>
                  
  <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=<?=6?>,0,0,0" width="250" height="168">
  <param name="allowScriptAccess" value="sameDomain" />
  <param name=movie value="http://www.millsberry.com/images/buddy/buddy_featured_v6.swf?buddyScriptURL=http://www.millsberry.com/buddy/process_buddy.phtml&buddyTimeStamp=FEATURED_CACHE&userName=samalan">
  <param name=quality value="high">
  <param name=menu value=false>
  <param name="wmode" value="transparent" />
  <param name=scale value="exactfit">
  <param name="salign" value="lt" />
  <embed src="http://www.millsberry.com/images/buddy/buddy_featured_v6.swf?buddyScriptURL=http://www.millsberry.com/buddy/process_buddy.phtml&buddyTimeStamp=FEATURED_CACHE&userName=samalan" quality="high" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" scale="exactfit" width="250" height="168" wmode="transparent">
  </embed>
  </object>
                </TD>
              </TR>
              <TR>
                <TD ALIGN='LEFT' CLASS='header_stripe_TD'>
                  &nbsp;Featured Citizen:
                </TD>
              </TR>
              <TR>
                <TD class='article_body'>
LOOK!  It's Dewster!
<P>
If you haven't met this charismatic resident of Ravenwood, you're sure missing out!  Not only is Dewster a huge archaeology buff, but he's got a couple of magic tricks to show you… that is, if you play your cards right!  Dewster is always hanging out at the Internet café, surrounded by computers, another one of his many interests!
<P>Of course, if you can't find Dewster at the Internet café, you can be sure that his curiosity has led him to a new roller coaster at the amusement park, a cool video game at the arcade, or even to a cool-looking bug that he spotted in his own backyard!  Dewster is very curious and investigative, so if you're wondering about the world, go find Dewster and wonder with him!
<P>While Dewster seems like a bookworm, he most certainly isn't - in fact, he spends quite a lot of his free time reading comic books and listening to music!  If you happen to be in Ravenwood and you walk by 2632 Wolf Creek Way, you can be sure that Dewster will have some music blasting, whether it be reggae, show tunes, or classic rock!
<P>So, if you've never met Dewster, why not take a visit to Ravenwood and introduce yourself?  Dewster never rejects a new friend, which is what you're sure to be!
<P>Dewster lives at 2632 Wolf Creek Way in Ravenwood and has been a citizen since July 28, 2004. 
<P>Click <A HREF='./home/?vf=1&user=samalan'>here</A> to find out more about him!
                </TD>
              </TR>
              <TR>
                <TD>
                  <hr size='1' noshade>
                </TD>
              </TR>
            </TABLE>
          </TD>
          <TD ROWSPAN='2' WIDTH='11' ALIGN='CENTER' BACKGROUND='http://www.millsberry.com/images/site_gfx/vertline.gif'>
            <IMG SRC='http://www.millsberry.com/images/site_gfx/vertline.gif'>
          </TD>
        </TR>
        <TR>
          <TD WIDTH='300' ALIGN='CENTER' VALIGN='TOP'>
            <TABLE BORDER='0' CELLPADDING='0' CELLSPACING='0' WIDTH='100%'>
              <TR><TD VALIGN='TOP' HEIGHT='100%'><A HREF='http://www.millsberry.com/signup.phtml'><IMG SRC='http://www.millsberry.com/images/site_gfx/welcome_signup.gif' BORDER='1'></A></TD>
              </TR>
              <TR>
                <TD ALIGN='LEFT' VALIGN='TOP' CLASS='header_stripe_TD'>
                  &nbsp;Headline News:
                </TD>
              </TR>
              <TR>
                <TD ALIGN='LEFT' HEIGHT='100%' class='article_body'>
                  If you look over the hill, you’ll see the far edge of a small city called Millsberry. 
	  It used to be a small town, but recently, Millsberry has grown beyond its borders. 
	  Walk down the hill and you step into the outer neighborhoods. Just a little further, and you walk into the center of Town. 
	  <p>If you want to become a citizen, just click on the SIGN UP button to the left. 
	  <p>You'll get your own customizable home, 
	  access to the shopping district, and get to play a bunch of great games! It's completely free and only takes a second.
	  <p>Here in Millsberry, there are TONS of things to do!  Whether you want to spend your time decorating your home, 
cleaning up Peabody Park, or hanging out at Millsberry Academy -- it's all up to you!  You're in complete control!

<p>Be sure to save those Millsbucks, though!  There are loads of items to buy, including food, books, and clothes that 
your character can wear, but you'll need Millsbucks to get 'em!

<p>Don't know where to start?  Head on over to Town Hall and get acquainted with the laws here in Millsberry, or to the 
bank to activate your Millsbucks account!  There's so much to do here, so make the most out of it and go explore 
Millsberry today!</b>
                </TD>
              </TR>
            </TABLE>
          </TD>
        </TR>
      </TABLE></TD>
        <TD WIDTH='150' VALIGN='TOP' ALIGN='CENTER' HEIGHT='100%'>          </TD>
          <TD WIDTH='100%'>
            &nbsp;
          </TD>
  </TR>
  <TR>
    <TD COLSPAN="4" WIDTH="100%" ALIGN="CENTER" CLASS="footer_TD">
      <SPAN CLASS='footerfont'>
      MILLSBERRY, characters, logos, product names and all related indicia are trademarks of Mills Online, Inc., © 2004.<BR> ® denotes Reg. US Pat. & TM Office. All rights reserved.
        <BR>
        Use of this site signifies your acceptance of the <A HREF='http://www.millsberry.com/town_hall/terms.phtml'>Terms and Conditions</A>.
        <BR>
        Please view our <A HREF='http://www.millsberry.com/town_hall/policy.phtml'>Privacy Policy</A>.      </SPAN>
    </TD>
</TABLE>
</BODY>
</HTML>
