<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- 10.100.56.28 -->
<html>
<head>
<meta http-equiv='imagetoolbar' content='no'>
<meta name='keywords' content="Mills,Millsbury,Milsberry,Milsbury,Millberry,Millbury,Fun games,Spanish language games,Educational games,Active games,Citizen,Cool stuff,Arcade,Music Mix,Fun,Games,Explore,Adventure,Create,Character,Buddy,Care,Academy,School,Gym,Gymnasium,Solver,Science,Project,Town,Pets,Children's games,Games for kid,Kid games,Kids games,Kid's games,Children,Safe gaming">
<title>Millsberry - The Pet Palace</title>
<script type='text/javascript' src='/common.js?v=2'></script>
<link rel='shortcut icon' type='image/x-icon' href='/favicon.ico'>
<!-- Appending v=# to these files causes them to recache in the user's browser when # changes -->
<link rel='stylesheet' type='text/css' href='/css/theme/royal.css?v=2'>
<link rel='stylesheet' type='text/css' href='/css/template.css?v=5'>
<link rel='stylesheet' type='text/css' href='/css/global.css?v=2'>
<!--[if lt IE 7.00]>
<link rel='stylesheet' type='text/css' href='/css/template.ie.css?v=1'>
<link rel='stylesheet' type='text/css' href='/css/global.ie.css?v=1'>
<![endif]-->
</head>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<body>

<!--<div id='leaderboard'><h2>Leader Board</h2></div>-->
<div id='top'>
<a href='/'><span id='logo'>&nbsp;</span></a>
<div id='layout_head'>
	<div id='login_info'><form name='login' method='post' action='/shop.phtml?shop_id=9&p=7&msg=2'>
Username <input type='text' name='login_username' size='10'>&nbsp;&nbsp;
Password <input type='password' name='login_pass' size='10'>
<input type='submit' value='Go'>
</form></div>
	<div id='stripe'>
		<div id='stripe_shortcuts'>
			<table width='95' border='0' cellpadding='0' cellspacing='0'><tr>
				<td width='72'></td>
				<td width='23' valign='bottom'></td>
			</tr></table>
		</div>
		<div id='stripe_search'>
			<form name='search' action='/site_search.phtml' method='get'>
			<table width='340' border='0' cellpadding='0' cellspacing='0'><tr>
				<td width='135' align='right'>Address Book&nbsp;</td>
				<td width='105' align='left' valign='middle'><input type='text' name='search' size='15'></td>
				<td width='30' align='center' valign='bottom'><a href='javascript: document.search.submit();' class='stripe_button'><span id='search_button'>&nbsp;</span></a></td>
				<td width='60' align='right'><a href='/town_hall/faq.phtml'>Help</a></td>
			</tr></table>
			</form>
		</div>
	</div>
</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='body'>
<div id='layout_body'>
<div id='side_nav'>
<a href='/main_map.phtml' class='nav_button_hover'><span id='nav_the_city' class='nav_button'>&nbsp;</span></a>
<a href='/main_map.phtml?location=downtown' class='nav_button_hover'><span id='nav_downtown' class='nav_button'>&nbsp;</span></a>
<a href='/tour.phtml' class='nav_button_hover'><span id='nav_tour' class='nav_button'>&nbsp;</span></a>
<a href='/signup.phtml' class='nav_button_hover'><span id='nav_signup' class='nav_button'>&nbsp;</span></a>
<a href='/complex/arcade.phtml' class='nav_button_hover'><span id='nav_arcade' class='nav_button'>&nbsp;</span></a>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='main'>
<div id='interior'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '600', '400', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fsite_gfx%252Finteriors%252Fint_pet_palace_v7.swf%3C%2Furl%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E600%3C%2Fwidth%3E%3Cheight%3E400%3C%2Fheight%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&scream=&unixTimeStamp=1161745263&serverTimeOffset=28800', '7', 'noscale');</script></div>
<div id='interior_stripe'>The Pet Palace</div>
<div id='content'>
<div class='success'>Thanks for adopting a new pet! Remember to purchase food for your pet often so that it won't be returned to the Pet Palace!</div>
The Pet Palace is a great place to find just the right animal companion.  The owners, Frank and Rosie Ruiz, are animal-lovers and are very eager to find good homes for all of the animals in their shop.  They're always willing to explain the responsibilities and joys of pet ownership to interested customers, as well as offering tips on animal care.  So, whether you'd like a more traditional friend, like a dog or a cat, or a strange and exotic animal, like a sugar glider or an iguana, you're sure to find the perfect pet for your lifestyle at The Pet Palace.<br><br>Don't forget though, in addition to getting your new pet here, make sure to pick up food and any other supplies you may need... including a toy or two! You definitely want your new friend to feel happy and welcome into their new home! You can browse different kinds of items by clicking them above.<table align='center' border='0' cellpadding='0' cellspacing='0'><tr>
<td width='21' align='right' height='20'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='21' height='20'></td>
<td width='16' align='right' height='20'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='16' height='20'></td>
<td align='center' height='20' valign='top'><a href='shop.phtml?shop_id=9&p=1' class='page_link'>1</a><span class='page_spacer'>|</span><a href='shop.phtml?shop_id=9&p=2' class='page_link'>2</a><span class='page_spacer'>|</span><a href='shop.phtml?shop_id=9&p=3' class='page_link'>3</a><span class='page_spacer'>|</span><a href='shop.phtml?shop_id=9&p=4' class='page_link'>4</a><span class='page_spacer'>|</span><a href='shop.phtml?shop_id=9&p=5' class='page_link'>5</a><span class='page_spacer'>|</span><a href='shop.phtml?shop_id=9&p=6' class='page_link'>6</a><span class='page_spacer'>|</span><span class='page_selected'>7</span></td>
<td width='16' height='20' align='left'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='16' height='20'></td>
<td width='21' height='20' align='left'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='21' height='20'></td>
</tr></table>
<hr size='1' noshade>
<form method='post' action='process_shop.phtml' onSubmit='return can_submit (this);'>
<input type='hidden' name='submitted' value='false'>
<input type='hidden' name='shop_id' value='9'>
<input type='hidden' name='p' value='7'>
<table width='100% border='0' cellpadding='2' cellspacing='0'>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_6677_v2.swf%3C%2Furl%3E%3Cscale%3E100%3C%2Fscale%3E%3Cx%3E50%3C%2Fx%3E%3Cy%3E50%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1161745263&serverTimeOffset=28800', '7', 'noscale');</script></td>
<td><b>Iguana</b><br><i>Iguanas can grow to be 5 or 6 feet long and thrive on a steady diet of fruits and veggies!</i></td>
<td align='center'>355<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_6677:1fc482bf5d38fb5f27db63bd663e0426' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 355 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_6679_v2.swf%3C%2Furl%3E%3Cscale%3E70%3C%2Fscale%3E%3Cx%3E40%3C%2Fx%3E%3Cy%3E60%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1161745263&serverTimeOffset=28800', '7', 'noscale');</script></td>
<td><b>Peacock</b><br><i>Peacocks are beautiful birds, and they&#039;re more than happy to let you admire their lovely feathers!</i></td>
<td align='center'>270<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_6679:63681f75a22926e3f0331af82e16ecaf' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 270 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_6683.swf%3C%2Furl%3E%3Cscale%3E300%3C%2Fscale%3E%3Cx%3E40%3C%2Fx%3E%3Cy%3E40%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1161745263&serverTimeOffset=28800', '7', 'noscale');</script></td>
<td><b>Sugar Glider</b><br><i>Sugar Gliders come from Australia, and are smart, playful, and (of course) cute!</i></td>
<td align='center'>355<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_6683:b990939d5e980af07631b000fa9fd3d9' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 355 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_6684.swf%3C%2Furl%3E%3Cscale%3E300%3C%2Fscale%3E%3Cx%3E40%3C%2Fx%3E%3Cy%3E40%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1161745263&serverTimeOffset=28800', '7', 'noscale');</script></td>
<td><b>Chinchilla</b><br><i>This shy little South American rodent is very soft; just feel that coat!</i></td>
<td align='center'>355<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_6684:b2dcf7506c9cb7ef03701705838e02cc' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 355 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_6686.swf%3C%2Furl%3E%3Cscale%3E150%3C%2Fscale%3E%3Cx%3E40%3C%2Fx%3E%3Cy%3E40%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1161745263&serverTimeOffset=28800', '7', 'noscale');</script></td>
<td><b>Large Tortoise</b><br><i>Tortoises only eat plants, so be sure to feed them lots of fruits and leafy greens!</i></td>
<td align='center'>355<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_6686:e74898fb0bdbc9e05318cb1a0d8f2611' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 355 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_6690.swf%3C%2Furl%3E%3Cscale%3E150%3C%2Fscale%3E%3Cx%3E50%3C%2Fx%3E%3Cy%3E50%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1161745263&serverTimeOffset=28800', '7', 'noscale');</script></td>
<td><b>Iguana Food</b><br><i>This iguana food is full of all the fruits and vegetables that your iguana needs.</i></td>
<td align='center'>40<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_6690:cbd6d1d50309dba6c52b919d9da6c03e' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 40 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_6691.swf%3C%2Furl%3E%3Cscale%3E300%3C%2Fscale%3E%3Cx%3E50%3C%2Fx%3E%3Cy%3E50%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1161745263&serverTimeOffset=28800', '7', 'noscale');</script></td>
<td><b>Toucan Food</b><br><i>This healthy toucan food will keep your toucan&#039;s feathers glossy.</i></td>
<td align='center'>40<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_6691:4de84973a26339fc873ab3068538a493' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 40 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_6757.swf%3C%2Furl%3E%3Cscale%3E100%3C%2Fscale%3E%3Cx%3E50%3C%2Fx%3E%3Cy%3E60%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1161745263&serverTimeOffset=28800', '7', 'noscale');</script></td>
<td><b>Chinchilla Dust Bin</b><br><i>Giving your chinchilla a dust bath every week will make its fur even silkier.
</i></td>
<td align='center'>125<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_6757:0ca942a3ecd70ddb241109850d64bc48' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 125 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_6758.swf%3C%2Furl%3E%3Cscale%3E65%3C%2Fscale%3E%3Cx%3E50%3C%2Fx%3E%3Cy%3E75%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1161745263&serverTimeOffset=28800', '7', 'noscale');</script></td>
<td><b>Toucan Stand</b><br><i>The perfect perch for your pet toucan.</i></td>
<td align='center'>175<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_6758:075905e9cafacfbb5b7001890c3d8e4d' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 175 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_6759.swf%3C%2Furl%3E%3Cscale%3E100%3C%2Fscale%3E%3Cx%3E50%3C%2Fx%3E%3Cy%3E58%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1161745263&serverTimeOffset=28800', '7', 'noscale');</script></td>
<td><b>Chicken Coop</b><br><i>Your chickens will be comfy and warm in this chicken coop!</i></td>
<td align='center'>235<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_6759:e54721b3d305e01cef14bb6fcd76ac4d' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 235 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_6774.swf%3C%2Furl%3E%3Cscale%3E200%3C%2Fscale%3E%3Cx%3E55%3C%2Fx%3E%3Cy%3E65%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1161745263&serverTimeOffset=28800', '7', 'noscale');</script></td>
<td><b>Turtle Chow</b><br><i>Feed your turle this excellent brand of turtle chow.</i></td>
<td align='center'>40<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_6774:07154ffc0367e9e6ebfccb8d8cb2fe71' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 40 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_6775.swf%3C%2Furl%3E%3Cscale%3E300%3C%2Fscale%3E%3Cx%3E50%3C%2Fx%3E%3Cy%3E65%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1161745263&serverTimeOffset=28800', '7', 'noscale');</script></td>
<td><b>Chinchilla Food</b><br><i>Your chinchilla will stay healthy and happy with this chinchilla food.</i></td>
<td align='center'>40<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_6775:43086ead24dfcf7b0b17fac966ac10c8' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 40 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_6776.swf%3C%2Furl%3E%3Cscale%3E250%3C%2Fscale%3E%3Cx%3E40%3C%2Fx%3E%3Cy%3E50%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1161745263&serverTimeOffset=28800', '7', 'noscale');</script></td>
<td><b>Sugar Glider Food</b><br><i>Specially made and packaged just for your sugar glider.</i></td>
<td align='center'>40<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_6776:8b37ab9e78a799627af07264509e8c61' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 40 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_6777.swf%3C%2Furl%3E%3Cscale%3E200%3C%2Fscale%3E%3Cx%3E60%3C%2Fx%3E%3Cy%3E65%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1161745263&serverTimeOffset=28800', '7', 'noscale');</script></td>
<td><b>Chicken Feed</b><br><i>This bag of chicken feed should last you a while!</i></td>
<td align='center'>40<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_6777:51f4cc8e2d588759a19d9a2c717b7e6f' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 40 Millsbucks?');">
</td>
</tr>
</table>
</form>
<hr noshade size='1'><table align='center' border='0' cellpadding='0' cellspacing='0'><tr>
<td width='21' align='right' height='20'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='21' height='20'></td>
<td width='16' align='right' height='20'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='16' height='20'></td>
<td align='center' height='20' valign='top'><a href='shop.phtml?shop_id=9&p=1' class='page_link'>1</a><span class='page_spacer'>|</span><a href='shop.phtml?shop_id=9&p=2' class='page_link'>2</a><span class='page_spacer'>|</span><a href='shop.phtml?shop_id=9&p=3' class='page_link'>3</a><span class='page_spacer'>|</span><a href='shop.phtml?shop_id=9&p=4' class='page_link'>4</a><span class='page_spacer'>|</span><a href='shop.phtml?shop_id=9&p=5' class='page_link'>5</a><span class='page_spacer'>|</span><a href='shop.phtml?shop_id=9&p=6' class='page_link'>6</a><span class='page_spacer'>|</span><span class='page_selected'>7</span></td>
<td width='16' height='20' align='left'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='16' height='20'></td>
<td width='21' height='20' align='left'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='21' height='20'></td>
</tr></table>

</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='footer'>
MILLSBERRY &reg;, characters, logos, product names and all related indicia are trademarks of Mills Online, Inc., &copy; 2004-2006.<BR> &reg; denotes Reg. US Pat. & TM Office. All rights reserved.<br>
Use of this site signifies your acceptance of the <a href='/town_hall/terms.phtml'><b>Terms and Conditions</b></a>.
Please view our <a href='/town_hall/terms.phtml'><b>Privacy Policy</b></a>.
</div>
</div>
<div id='bottom'>&nbsp;</div>
</div>
</body>
</html>
