<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- iadgenmapp12.ood.ops -->
<html>
<head>
<meta http-equiv='imagetoolbar' content='no'>
<meta name='keywords' content="Mills,Millsbury,Milsberry,Milsbury,Millberry,Millbury,Fun games,Spanish language games,Educational games,Active games,Citizen,Cool stuff,Arcade,Music Mix,Fun,Games,Explore,Adventure,Create,Character,Buddy,Care,Academy,School,Gym,Gymnasium,Solver,Science,Project,Town,Pets,Children's games,Games for kid,Kid games,Kids games,Kid's games,Children,Safe gaming">
<title>Millsberry - Address Book</title>
<script type='text/javascript' src='/common.js?v=2'></script>
<link rel='shortcut icon' type='image/x-icon' href='/favicon.ico'>
<!-- Appending v=# to these files causes them to recache in the user's browser when # changes -->
<link rel='stylesheet' type='text/css' href='/css/theme/royal.css?v=2'>
<link rel='stylesheet' type='text/css' href='/css/template.css?v=5'>
<link rel='stylesheet' type='text/css' href='/css/global.css?v=2'>
<!--[if lt IE 7.00]>
<link rel='stylesheet' type='text/css' href='/css/template.ie.css?v=1'>
<link rel='stylesheet' type='text/css' href='/css/global.ie.css?v=1'>
<![endif]-->
</head>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<body>

<!--<div id='leaderboard'><h2>Leader Board</h2></div>-->
<div id='top'>
<a href='/'><span id='logo'>&nbsp;</span></a>
<div id='layout_head'>
	<div id='login_info'><form name='login' method='post' action='/site_search.phtml?search=wwe360&login.x=0&login.y=0'>
Username <input type='text' name='login_username' size='10'>&nbsp;&nbsp;
Password <input type='password' name='login_pass' size='10'>
<input type='submit' value='Go'>
</form></div>
	<div id='stripe'>
		<div id='stripe_shortcuts'>
			<table width='95' border='0' cellpadding='0' cellspacing='0'><tr>
				<td width='72'></td>
				<td width='23' valign='bottom'></td>
			</tr></table>
		</div>
		<div id='stripe_search'>
			<form name='search' action='/site_search.phtml' method='get'>
			<table width='340' border='0' cellpadding='0' cellspacing='0'><tr>
				<td width='135' align='right'>Address Book&nbsp;</td>
				<td width='105' align='left' valign='middle'><input type='text' name='search' size='15'></td>
				<td width='30' align='center' valign='bottom'><a href='javascript: document.search.submit();' class='stripe_button'><span id='search_button'>&nbsp;</span></a></td>
				<td width='60' align='right'><a href='/town_hall/faq.phtml'>Help</a></td>
			</tr></table>
			</form>
		</div>
	</div>
</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='body'>
<div id='layout_body'>
<div id='side_nav'>
<a href='/main_map.phtml' class='nav_button_hover'><span id='nav_the_city' class='nav_button'>&nbsp;</span></a>
<a href='/main_map.phtml?location=downtown' class='nav_button_hover'><span id='nav_downtown' class='nav_button'>&nbsp;</span></a>
<a href='/tour.phtml' class='nav_button_hover'><span id='nav_tour' class='nav_button'>&nbsp;</span></a>
<a href='/signup.phtml' class='nav_button_hover'><span id='nav_signup' class='nav_button'>&nbsp;</span></a>
<a href='/complex/arcade.phtml' class='nav_button_hover'><span id='nav_arcade' class='nav_button'>&nbsp;</span></a>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='main'>
<div id='interior'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/library/item_book_loader_v7.swf', '600', '400', 'scriptURL=http://www.millsberry.com/process_search.phtml&bookID=wwe360&IDS_NEXT=Next&IDS_PREVIOUS=Previous&IDS_LOADING_BOOK=Loading+Book...&unixTimeStamp=1166414290&serverTimeOffset=28800', '7', 'noscale');</script></div>
<div id='interior_stripe'>Address Book</div>
<div id='content'>
Your handy address book for the residents of Millsberry.
</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='footer'>
MILLSBERRY &reg;, characters, logos, product names and all related indicia are trademarks of Mills Online, Inc., &copy; 2004-2006.<BR> &reg; denotes Reg. US Pat. & TM Office. All rights reserved.<br>
Use of this site signifies your acceptance of the <a href='/town_hall/terms.phtml'><b>Terms and Conditions</b></a>.
Please view our <a href='/town_hall/terms.phtml'><b>Privacy Policy</b></a>.
</div>
</div>
<div id='bottom'>&nbsp;</div>
</div>
</body>
</html>
