
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/1999/REC-html401-19991224/loose.dtd">
<HTML>
	<HEAD>
		<title>The President's Challenge - Kids</title>
		<link href="/main.css" rel="stylesheet" type="text/css">
		<meta name="GENERATOR" content="Microsoft Visual Studio.NET 7.0">
		<meta name="CODE_LANGUAGE" content="Visual Basic 7.0">
		<meta name="vs_defaultClientScript" content="JavaScript">
		<meta name="vs_targetSchema" content="http://schemas.microsoft.com/intellisense/ie5">
		<script src="/includes/interrupter_a.js">
		</script>
	</HEAD>
	<body bgcolor="#ffffff" text="#666666" link="#990000" alink="#ffcc00" vlink="#660000" onload="isReturnVisit();"> <!--START CENTERING TABLE-->
		<table border="0" width="100%" cellspacing="0" cellpadding="0">
			<tr>
				<td width="100%" align="center"> <!--START COLORED BORDER TABLES-->
					<table border="0" cellspacing="0" cellpadding="8" bgcolor="#999999">
						<tr>
							<td>
								<table border="0" cellspacing="0" cellpadding="1" bgcolor="#ffffff">
									<tr>
										<td> <!--START HEADER INCLUDE-->
											
<table border="0" width="740" cellspacing="0" cellpadding="0">
	<tr>
		<td width="14" valign="bottom" bgcolor="#cccccc"><img src="/images/shared/spacer.gif" alt="" width="14" height="16" border="0"></td>
		<td width="216" valign="bottom" bgcolor="#cccccc"><a href="/index.aspx" title="Home"><img src="/images/shared/header/logo_top.gif" alt="Home" width="216" height="16" border="0"></a></td>
		<td width="496" valign="bottom" align="right" bgcolor="#cccccc" colspan="2"> <!--********** START USERNAME LOGIC **********-->
			<div align="right">
				<table border="0" cellspacing="0" cellpadding="2" align="right">
					<tr>
						<td align="right"><div class="smallredcopy" align="right"></div>
						</td>
					</tr>
				</table>
			</div> <!--********** STOP USERNAME LOGIC **********-->
		</td>
		<td width="14" valign="bottom" bgcolor="#cccccc"><img src="/images/shared/spacer.gif" alt="" width="14" height="16" border="0"></td>
	</tr>
	<tr>
		<td width="14" valign="top" bgcolor="#cccccc"><img src="/images/shared/spacer.gif" alt="" width="14" height="32" border="0"></td>
		<td width="216" valign="top" bgcolor="#cccccc"><a href="/index.aspx" title="Return to Home" onmouseover="homelogo.src='/images/shared/header/logo_bottom_on.gif'" onmouseout="homelogo.src='/images/shared/header/logo_bottom.gif'"><img src="/images/shared/header/logo_bottom.gif" alt="The President's &#13;&#10;Challenge" width="216" height="32" border="0" id="homelogo" name="homelogo"></a>
		</td>
		
		<td width="421" valign="top" bgcolor="#cccccc"><img src="/images/shared/header/main_bar.gif" alt="" width="421" height="32" border="0"></td>
		<td width="75" valign="top" bgcolor="#cccccc">
			
			<a href="/login/index.aspx" title="Log-in to the web site"><img src="/images/shared/header/log_in.gif" alt="Log-in" width="75" height="32" border="0"></a>
			
		</td>
		<td width="14" valign="top" bgcolor="#cccccc"><img src="/images/shared/spacer.gif" alt="" width="14" height="32" border="0"></td>
	</tr>
</table>

											<!--STOP HEADER INCLUDE--> <!--START MAIN CONTENT TABLE-->
											<table border="0" width="740" cellspacing="0" cellpadding="0">
												<tr>
													<td valign="top" colspan="5"><img src="/images/index/kids/color_header.gif" alt="KIDS - The fun starts here. Let's go!" width="740" height="103" border="0"></td>
												</tr>
												<tr>
													<td valign="top"><img src="/images/shared/spacer.gif" alt="" width="15" height="2" border="0"></td>
													<td valign="top" align="left"> <!--START LEFT MENU-->
														<table border="0" width="150" cellspacing="0" cellpadding="0">
															<tr>
																<td><img src="/images/shared/spacer.gif" alt="" width="150" height="10" border="0"></td>
															</tr>
															<tr>
																<td><a href="/the_challenge/index.aspx" title="The Challenge - More about the program and how to get started." onmouseover="challenge.src='/images/index/left_menu/challenge_on.gif'" onmouseout="challenge.src='/images/index/left_menu/challenge_off.gif'"><img src="/images/index/left_menu/challenge_off.gif" alt="The Challenge" width="150" height="43" border="0" name="challenge"></a></td>
															</tr>
															<tr>
																<td><img src="/images/index/left_menu/gray_bar.gif" alt="" width="150" height="1" border="0"></td>
															</tr>
															<tr>
																<td><a href="/earn_awards/index.aspx" title="Earn Awards - Earn awards for meeting your goals." onmouseover="awards.src='/images/index/left_menu/awards_on.gif'" onmouseout="awards.src='/images/index/left_menu/awards_off.gif'"><img src="/images/index/left_menu/awards_off.gif" alt="Earn Awards" width="150" height="43" border="0" name="awards"></a></td>
															</tr>
															<tr>
																<td><img src="/images/index/left_menu/gray_bar.gif" alt="" width="150" height="1" border="0"></td>
															</tr>
															<tr>
																<td><a href="/activity_log/index.aspx" title="My Activity Log - Track your progress online and see how you're doing." onmouseover="log.src='/images/index/left_menu/activity_log_on.gif'" onmouseout="log.src='/images/index/left_menu/activity_log_off.gif'"><img src="/images/index/left_menu/activity_log_off.gif" alt="My Activity Log" width="150" height="43" border="0" name="log"></a></td>
															</tr>
															<tr>
																<td><img src="/images/index/left_menu/gray_bar.gif" alt="" width="150" height="1" border="0"></td>
															</tr>
															<tr>
																<td><a href="/tools_to_help/index.aspx" title="Tools to Help - Fitness calculators &amp; fresh ideas to help you improve."  onmouseover="tools.src='/images/index/left_menu/tools_on.gif'" onmouseout="tools.src='/images/index/left_menu/tools_off.gif'"><img src="/images/index/left_menu/tools_off.gif" alt="Tools to Help" width="150" height="43" border="0" name="tools"></a></td>
															</tr>
															<tr>
																<td><img src="/images/index/left_menu/gray_bar.gif" alt="" width="150" height="1" border="0"></td>
															</tr>
															<tr>
																<td><a href="/the_presidents_council/index.aspx" title="The Presiden't Council - Chosen by the President to serve as ambassadors to fitness." onmouseover="council.src='/images/index/left_menu/council_on.gif'" onmouseout="council.src='/images/index/left_menu/council_off.gif'"><img src="/images/index/left_menu/council_off.gif" alt="The President's Council" width="150" height="43" border="0" name="council"></a></td>
															</tr>
															<tr>
																<td><img src="/images/index/left_menu/gray_bar.gif" alt="" width="150" height="1" border="0"></td>
															</tr>
															<tr>
																<td><a href="https://www.presidentschallenge.org/order_center/index.aspx" title="Order Center - Order awards, cool merchandise, and more." onmouseover="store.src='/images/index/left_menu/order_on.gif'" onmouseout="store.src='/images/index/left_menu/order_off.gif'"><img src="/images/index/left_menu/order_off.gif" alt="Order Center" width="150" height="43" border="0" name="store"></a></td>
															</tr>
														</table> <!--STOP LEFT MENU-->
														<br>
														<a href="/earn_awards/index.aspx"><img src="/images/index/kids/violator_win_awards.gif" alt="Earn awards! Track your progress &amp; order your awards." width="150" height="58" border="0"></a>
													</td>
													<td valign="top"><img src="/images/shared/spacer.gif" alt="" width="50" height="2" border="0"></td>
													<td valign="top" align="left"><img src="/images/index/teens/getting_started_header.gif" alt="Getting Started!" width="129" height="40" border="0"> <!--START CONTENT-->
														<div class="graycopy">Get into the program by jumping rope. Playing catch. Or 
															racing a friend. Even better, you can win awards for staying active - and track 
															your progress along with kids across America. The more you keep at it, the more 
															fun you'll have.</div>
														<br>
														<table border="0" width="315" cellspacing="0" cellpadding="0">
															<tr>
																<td width="50"><img src="/images/shared/spacer.gif" alt="" width="50" height="2" border="0"></td>
																<td width="265">
																	<div class="graycopy">
																		<div class="blueheader">Active Lifestyle</div>
																		Get up. Get out. Have fun. And win awards for finishing the program. <a href="/the_challenge/active_lifestyle.aspx">
																			&#187;&nbsp;find out more</a><br>
																		<br>
																		<div class="blueheader">Presidential Champions</div>
																		Challenge yourself - by staying active and going for the highest award you can 
																		get. <a href="/the_challenge/presidential_champions.aspx">&#187;&nbsp;find out more</a><br>
																		<br>
																		<div class="blueheader">Be a Part of a Group</div>
																		Ask someone to join you - a friend, mom, dad, or brothers and sisters. <a href="/the_challenge/joining_a_group.aspx">
																			&#187;&nbsp;find out more</a>
																	</div>
																</td>
															</tr>
														</table>
														<a href="/login/register_individual.aspx"><img src="/images/index/button_sign_me_up.gif" alt="Sign me up!" width="171" height="44" border="0"></a> <!--STOP CONTENT-->
													</td>
													<td valign="top"><img src="/images/index/kids/photo_bar.jpg" alt="Photos" width="210" height="265" border="0"></td>
												</tr>
												<tr>
													<td width="15"><img src="/images/shared/spacer.gif" alt="" width="15" height="15" border="0"></td>
													<td width="150"><img src="/images/shared/spacer.gif" alt="" width="150" height="15" border="0"></td>
													<td width="50"><img src="/images/shared/spacer.gif" alt="" width="50" height="15" border="0"></td>
													<td width="315"><img src="/images/shared/spacer.gif" alt="" width="315" height="15" border="0"></td>
													<td width="210"><img src="/images/shared/spacer.gif" alt="" width="210" height="15" border="0"></td>
												</tr>
											</table> <!--STOP MAIN CONTENT TABLE--> <!--START FOOTER INCLUDE-->
											
<table border="0" width="740" cellspacing="0" cellpadding="3" bgcolor="#CCCCCC">
	<tr>
		<td align="left" valign="center">
			&nbsp;<a href="/index.aspx" class="footergray">home</a> &nbsp; <a href="/misc/legal.aspx" class="footergray">
				legal/privacy</a> &nbsp; <a href="/misc/help.aspx" class="footergray">help</a>
			&nbsp; <a href="/misc/contact.aspx" class="footergray">contact us</a> &nbsp; <a href="/misc/downloads.aspx" class="footergray">
				downloads</a> &nbsp; <a href="/misc/links.aspx" class="footergray">links</a>
			&nbsp; <a href="/misc/disabilities.aspx" class="footergray">disabilities</a> &nbsp;
			<a href="/misc/news_research.aspx" class="footergray">news/research</a> <!--&nbsp; <a href="/misc/search.aspx" class="footergray">search</a>--></td>
	</tr>
</table>
<!--STOP FOOTER INCLUDE-->
										</td>
									</tr>
								</table>
							</td>
						</tr>
					</table> <!--STOP COLORED BORDER TABLES-->
				</td>
			</tr>
		</table> <!--STOP CENTERING TABLE-->
	</body>
</HTML>
