<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- 10.100.56.31 -->
<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
<meta http-equiv='imagetoolbar' content='no'>
<meta name='keywords' content="Mills,Millsbury,Milsberry,Milsbury,Millberry,Millbury,Fun games,Spanish language games,Educational games,Active games,Citizen,Cool stuff,Arcade,Music Mix,Fun,Games,Explore,Adventure,Create,Character,Buddy,Care,Academy,School,Gym,Gymnasium,Solver,Science,Project,Town,Pets,Children's games,Games for kid,Kid games,Kids games,Kid's games,Children,Safe gaming">
<title>Millsberry - Academy Student Store</title>
<!-- Appending v=# to these files causes them to recache in the user's browser when # changes -->
<link rel='stylesheet' type='text/css' href='/css/theme/royal.css?v=2'>
<link rel='stylesheet' type='text/css' href='/css/template.css?v=2'>
<!--[if lt IE 7.00]>
<link rel='stylesheet' type='text/css' href='/css/ie.css?v=1'>
<![endif]-->
<script type='text/javascript' src='/hidden.js?v=1'></script>
<script type='text/javascript'>
<!--
// Allows users to assign names to their shortcuts
function addShortcut (to_url, default_title) {
	assign_title = default_title;
	var user_title = prompt ("What name do you want to give this shortcut?\nLeave this blank to use the page's existing title.","");
	if (user_title.length > 0) {
		assign_title = base64_encode (utf8_encode (user_title));
	}
	window.location='/process_shortcut.phtml?action=add&url=' + to_url + '&name=' + assign_title;
}
//-->
</script>
<link rel='shortcut icon' href='/favicon.ico'>
</head>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<body>

<div id='top'>
<a href='/index.phtml'><span id='logo'>&nbsp;</span></a>
<div id='layout_head'>
	<div id='login_info'><form name='login' method='post' action='/shop.phtml?shop_id=10&p=1&msg=You+just+purchased+Millsberry+Academy+Backpack%21&class=success'>
Username <input type='text' name='login_username' size='10'>&nbsp;&nbsp;
Password <input type='password' name='login_pass' size='10'>
<input type='submit' value='Go'>
</form></div>
	<div id='stripe'>
		<div id='stripe_shortcuts'>
			<table width='95' border='0' cellpadding='0' cellspacing='0'><tr>
				<td width='72'></td>
				<td width='23' valign='bottom'></td>
			</tr></table>
		</div>
		<div id='stripe_search'>
			<form name='search' action='/site_search.phtml' method='get'>
			<table width='340' border='0' cellpadding='0' cellspacing='0'><tr>
				<td width='135' align='right'>Address Book&nbsp;</td>
				<td width='105' align='left' valign='middle'><input type='text' name='search' size='15'></td>
				<td width='30' align='center' valign='bottom'><a href='javascript: document.search.submit();' class='stripe_button'><span id='search_button'>&nbsp;</span></a></td>
				<td width='60' align='right'><a href='/town_hall/faq.phtml'>Help</a></td>
			</tr></table>
			</form>
		</div>
	</div>
</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='body'>
<div id='layout_body'>
<div id='side_nav'>

<!-- Exclude these from the stylesheet so they can be translated -->
<style type='text/css'>
#body #layout_body #side_nav .nav_button_hover #nav_signup {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_signup_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_start {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_start_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_the_city {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_the_city_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_downtown {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_downtown_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_arcade {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_arcade_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_my_stuff {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_my_stuff_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_my_home {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_my_place_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_customize {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_customize_1.png') no-repeat;
}
</style>
<!--[if lt IE 7.00]>
<style type='text/css'>
#body #layout_body #side_nav .nav_button_hover #nav_signup {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_signup_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_start {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_start_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_the_city {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_the_city_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_downtown {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_downtown_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_arcade {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_arcade_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_my_stuff {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_my_stuff_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_my_home {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_my_place_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_customize {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_customize_1.png');
}
</style>
<![endif]-->

<a href='/signup.phtml' class='nav_button_hover'><span id='nav_signup' class='nav_button'>&nbsp;</span></a>
<a href='/main_map.phtml' class='nav_button_hover'><span id='nav_the_city' class='nav_button'>&nbsp;</span></a>
<a href='/main_map.phtml?location=downtown' class='nav_button_hover'><span id='nav_downtown' class='nav_button'>&nbsp;</span></a>
<a href='/complex/arcade.phtml' class='nav_button_hover'><span id='nav_arcade' class='nav_button'>&nbsp;</span></a>
<br><img src='http://graphics.millsberry.com/site_gfx/prebuddy.gif' border='1'><div style='font-size: 3px; line-height: 3px;'>&nbsp;</div>

<table width='100%' border='0' cellpadding='5' cellspacing='0' id='side_nav_options'>
<tr>
	<td align='right'>Language</td>
	<td>
		<form name='language_form' method='post' action='/shop.phtml?shop_id=10&p=1&msg=You+just+purchased+Millsberry+Academy+Backpack%21&class=success'>
		<select name='lang' onChange='document.language_form.submit();' style='width: 70px;'>
			<option value='en' selected>English</option>
			<option value='es' >Espa&ntilde;ol</option>
		</select>
		</form>
	</td>
</tr>

</table>

</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='main'>

	<div id='interior'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '600', '400', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%20%3F%3E%3Cmessage%20success%3D%271%27%20text%20%3D%20%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fsite_gfx%252Finteriors%252Fint_school_store_v1.swf%3C%2Furl%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E600%3C%2Fwidth%3E%3Cheight%3E400%3C%2Fheight%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1153300271', '7', 'noscale');</script></div>
	<div id='interior_stripe'>Academy Student Store</div>
	<!--<a href='/shop.phtml?shop_id=10'>List All</a>-->
	<div id='content'>
	
	<div class='success'>You just purchased Millsberry Academy Backpack!</div>
The Student Store is the place to come for all of your Academy needs. School supplies, such as pencils, notebooks, and folders, are available to take care of all your study needs. The Student Store also carries a huge selection of Millsberry Academy logo clothing and backpacks, so that you can show your school spirit in style! And importantly, all Student Store profits will be used to improve Millsberry Academy. So hurry in, browse around, and support your school!<br><br>
<span style='font-weight: bold;'>During the months of summer vacation, the school store inventory will be limited. We can't wait to bring you the best Millsberry Academy merchandise when the new school year begins!</span><div align='center'><table align='center' border='0' cellpadding='0' cellspacing='0'><tr>
<td width='21' align='right' height='20'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='21' height='20'></td>
<td width='16' align='right' height='20'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='16' height='20'></td>
<td align='center' height='20' valign='top'><span class='page_selected'>1</span></td>
<td width='16' height='20' align='left'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='16' height='20'></td>
<td width='21' height='20' align='left'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='21' height='20'></td>
</tr></table>
</div><hr size='1' noshade>
<form method='post' action='process_shop.phtml' onSubmit='return can_submit (this);'>
<input type='hidden' name='submitted' value='false'>
<input type='hidden' name='shop_id' value='10'>
<input type='hidden' name='p' value='1'>
<table width='100% border='0' cellpadding='2' cellspacing='0'>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%20%3F%3E%3Cmessage%20success%3D%271%27%20text%20%3D%20%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_6513_v2.swf%3C%2Furl%3E%3Cscale%3E150%3C%2Fscale%3E%3Cx%3E50%3C%2Fx%3E%3Cy%3E50%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1153300271', '7', 'noscale');</script></td>
<td><b>Millsberry Academy Backpack</b><br><i>Display your school spirit by sporting this Millsberry Academy backpack!</i></td>
<td align='center'>55<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_6513:3d897c9e1288357d4b07883149642eff' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 55 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%20%3F%3E%3Cmessage%20success%3D%271%27%20text%20%3D%20%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_6515_v3.swf%3C%2Furl%3E%3Cscale%3E150%3C%2Fscale%3E%3Cx%3E50%3C%2Fx%3E%3Cy%3E50%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1153300271', '7', 'noscale');</script></td>
<td><b>Pencil Holder</b><br><i>This pencil holder is a handy place for pens, markers, scissors, and, of course, pencils!</i></td>
<td align='center'>35<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_6515:d7129be2d6fbce6940274dfb39852dfc' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 35 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%20%3F%3E%3Cmessage%20success%3D%271%27%20text%20%3D%20%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_6492_v3.swf%3C%2Furl%3E%3CColorTransform%3E0x660000%3C%2FColorTransform%3E%3Cscale%3E150%3C%2Fscale%3E%3Cx%3E50%3C%2Fx%3E%3Cy%3E50%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1153300271', '7', 'noscale');</script></td>
<td><b>Red and Orange Backpack </b><br><i>This backpack is stylish and roomy enough for all your school supplies.</i></td>
<td align='center'>35<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_6519:1f34bb478d6157822e4228da5029c7a3' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 35 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%20%3F%3E%3Cmessage%20success%3D%271%27%20text%20%3D%20%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_6492_v3.swf%3C%2Furl%3E%3CColorTransform%3E0xCCAA00%3C%2FColorTransform%3E%3Cscale%3E150%3C%2Fscale%3E%3Cx%3E50%3C%2Fx%3E%3Cy%3E50%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1153300271', '7', 'noscale');</script></td>
<td><b>Gold and Orange Backpack </b><br><i>This backpack is stylish and roomy enough for all your school supplies.</i></td>
<td align='center'>45<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_6520:0b854c5c31836122751127b235341147' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 45 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%20%3F%3E%3Cmessage%20success%3D%271%27%20text%20%3D%20%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_6528.swf%3C%2Furl%3E%3Cscale%3E200%3C%2Fscale%3E%3Cx%3E45%3C%2Fx%3E%3Cy%3E50%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1153300271', '7', 'noscale');</script></td>
<td><b>Wooden Ruler</b><br><i>This ruler lets you measure in inches and centimeters.</i></td>
<td align='center'>35<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_6528:9e658d9a24ea62b149465e59d84df101' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 35 Millsbucks?');">
</td>
</tr>
</table>
</form>
<hr noshade size='1'><div align='center'><table align='center' border='0' cellpadding='0' cellspacing='0'><tr>
<td width='21' align='right' height='20'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='21' height='20'></td>
<td width='16' align='right' height='20'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='16' height='20'></td>
<td align='center' height='20' valign='top'><span class='page_selected'>1</span></td>
<td width='16' height='20' align='left'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='16' height='20'></td>
<td width='21' height='20' align='left'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='21' height='20'></td>
</tr></table>
</div>
</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='footer'>
MILLSBERRY, characters, logos, product names and all related indicia are trademarks of Mills Online, Inc., &copy; 2004-2006.<BR> &reg; denotes Reg. US Pat. & TM Office. All rights reserved.<br>Use of this site signifies your acceptance of the <a href='/town_hall/terms.phtml'><b>Terms and Conditions</b></a>.<br>Please view our <a href='/town_hall/terms.phtml'><b>Privacy Policy</b></a>
</div>
</div>
<div id='bottom'>&nbsp;</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='debug'>
</div>
</body>
</html>
