<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- 10.100.56.31 -->
<html>
<head>
<meta http-equiv='imagetoolbar' content='no'>
<meta name='keywords' content="Mills,Millsbury,Milsberry,Milsbury,Millberry,Millbury,Fun games,Spanish language games,Educational games,Active games,Citizen,Cool stuff,Arcade,Music Mix,Fun,Games,Explore,Adventure,Create,Character,Buddy,Care,Academy,School,Gym,Gymnasium,Solver,Science,Project,Town,Pets,Children's games,Games for kid,Kid games,Kids games,Kid's games,Children,Safe gaming">
<title>Millsberry - The Pet Palace</title>
<script type='text/javascript' src='/common.js'></script>
<link rel='shortcut icon' type='image/x-icon' href='/favicon.ico'>
<!-- Appending v=# to these files causes them to recache in the user's browser when # changes -->
<link rel='stylesheet' type='text/css' href='/css/theme/royal.css?v=2'>
<link rel='stylesheet' type='text/css' href='/css/template.css?v=4'>
<link rel='stylesheet' type='text/css' href='/css/global.css?v=1'>
<!--[if lt IE 7.00]>
<link rel='stylesheet' type='text/css' href='/css/template.ie.css?v=1'>
<link rel='stylesheet' type='text/css' href='/css/global.ie.css?v=1'>
<![endif]-->
</head>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<body>

<!--<div id='leaderboard'><h2>Leader Board</h2></div>-->
<div id='top'>
<a href='/index.phtml'><span id='logo'>&nbsp;</span></a>
<div id='layout_head'>
	<div id='login_info'><form name='login' method='post' action='/shop.phtml?shop_id=9&p=4&msg=2'>
Username <input type='text' name='login_username' size='10'>&nbsp;&nbsp;
Password <input type='password' name='login_pass' size='10'>
<input type='submit' value='Go'>
</form></div>
	<div id='stripe'>
		<div id='stripe_shortcuts'>
			<table width='95' border='0' cellpadding='0' cellspacing='0'><tr>
				<td width='72'></td>
				<td width='23' valign='bottom'></td>
			</tr></table>
		</div>
		<div id='stripe_search'>
			<form name='search' action='/site_search.phtml' method='get'>
			<table width='340' border='0' cellpadding='0' cellspacing='0'><tr>
				<td width='135' align='right'>Address Book&nbsp;</td>
				<td width='105' align='left' valign='middle'><input type='text' name='search' size='15'></td>
				<td width='30' align='center' valign='bottom'><a href='javascript: document.search.submit();' class='stripe_button'><span id='search_button'>&nbsp;</span></a></td>
				<td width='60' align='right'><a href='/town_hall/faq.phtml'>Help</a></td>
			</tr></table>
			</form>
		</div>
	</div>
</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='body'>
<div id='layout_body'>
<div id='side_nav'>
<a href='/main_map.phtml' class='nav_button_hover'><span id='nav_the_city' class='nav_button'>&nbsp;</span></a>
<a href='/main_map.phtml?location=downtown' class='nav_button_hover'><span id='nav_downtown' class='nav_button'>&nbsp;</span></a>
<a href='/tour.phtml' class='nav_button_hover'><span id='nav_tour' class='nav_button'>&nbsp;</span></a>
<a href='/signup.phtml' class='nav_button_hover'><span id='nav_signup' class='nav_button'>&nbsp;</span></a>
<a href='/complex/arcade.phtml' class='nav_button_hover'><span id='nav_arcade' class='nav_button'>&nbsp;</span></a>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='main'>
<div id='interior'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '600', '400', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fsite_gfx%252Finteriors%252Fint_pet_palace_v5.swf%3C%2Furl%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E600%3C%2Fwidth%3E%3Cheight%3E400%3C%2Fheight%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1157086197&serverTimeOffset=28800', '7', 'noscale');</script></div>
<div id='interior_stripe'>The Pet Palace</div>
<div id='content'>
<div class='success'>Thanks for adopting a new pet! Remember to purchase food for your pet often so that it won't be returned to the Pet Palace!</div>
The Pet Palace is a great place to find just the right animal companion.  The owners, Frank and Rosie Ruiz, are animal-lovers and are very eager to find good homes for all of the animals in their shop.  They're always willing to explain the responsibilities and joys of pet ownership to interested customers, as well as offering tips on animal care.  So, whether you'd like a more traditional friend, like a dog or a cat, or a strange and exotic animal, like a sugar glider or an iguana, you're sure to find the perfect pet for your lifestyle at The Pet Palace.<br><br>Don't forget though, in addition to getting your new pet here, make sure to pick up food and any other supplies you may need... including a toy or two! You definitely want your new friend to feel happy and welcome into their new home! You can browse different kinds of items by clicking them above.<div align='center'><table align='center' border='0' cellpadding='0' cellspacing='0'><tr>
<td width='21' align='right' height='20'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='21' height='20'></td>
<td width='16' align='right' height='20'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='16' height='20'></td>
<td align='center' height='20' valign='top'><a href='shop.phtml?shop_id=9&p=1' class='page_link'>1</a><span class='page_spacer'>|</span><a href='shop.phtml?shop_id=9&p=2' class='page_link'>2</a><span class='page_spacer'>|</span><a href='shop.phtml?shop_id=9&p=3' class='page_link'>3</a><span class='page_spacer'>|</span><span class='page_selected'>4</span><span class='page_spacer'>|</span><a href='shop.phtml?shop_id=9&p=5' class='page_link'>5</a><span class='page_spacer'>|</span><a href='shop.phtml?shop_id=9&p=6' class='page_link'>6</a><span class='page_spacer'>|</span><a href='shop.phtml?shop_id=9&p=7' class='page_link'>7</a></td>
<td width='16' height='20' align='left'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='16' height='20'></td>
<td width='21' height='20' align='left'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='21' height='20'></td>
</tr></table>
</div><hr size='1' noshade>
<form method='post' action='process_shop.phtml' onSubmit='return can_submit (this);'>
<input type='hidden' name='submitted' value='false'>
<input type='hidden' name='shop_id' value='9'>
<input type='hidden' name='p' value='4'>
<table width='100% border='0' cellpadding='2' cellspacing='0'>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_140.swf%3C%2Furl%3E%3CColorTransform%3E0xEE00EE%3C%2FColorTransform%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1157086197&serverTimeOffset=28800', '7', 'noscale');</script></td>
<td><b>Simple Hamster Care Tips</b><br><i>This book contains handy tips about hamster care.</i></td>
<td align='center'>35<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_4767:b1bc0cd9af509449860e61684735f54e' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 35 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_5010.swf%3C%2Furl%3E%3Cscale%3E250%3C%2Fscale%3E%3Cx%3E40%3C%2Fx%3E%3Cy%3E40%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1157086197&serverTimeOffset=28800', '7', 'noscale');</script></td>
<td><b>Spotted Hamster</b><br><i>A little hamster is a fun friend to have!</i></td>
<td align='center'>60<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_5010:b72e75b99be85384ac11121075c85510' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 60 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_5011.swf%3C%2Furl%3E%3CColorTransform%3E0xAA8866%3C%2FColorTransform%3E%3Cscale%3E255%3C%2Fscale%3E%3Cx%3E40%3C%2Fx%3E%3Cy%3E40%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1157086197&serverTimeOffset=28800', '7', 'noscale');</script></td>
<td><b>Spotted Hamster</b><br><i>He is so cute with those spots!  The only question is what to name him!</i></td>
<td align='center'>70<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_5011:8d1009fea245b2fa337f972c3bf51bd7' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 70 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_5012.swf%3C%2Furl%3E%3CColorTransform%3E0xAA6644%3C%2FColorTransform%3E%3Cscale%3E200%3C%2Fscale%3E%3Cx%3E40%3C%2Fx%3E%3Cy%3E50%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1157086197&serverTimeOffset=28800', '7', 'noscale');</script></td>
<td><b>Spotted Rabbit</b><br><i>Rabbits make great pets, and you can eat your carrots together!</i></td>
<td align='center'>125<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_5012:228cdffc5b6e8545a46f41cfc91fac3e' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 125 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_5013.swf%3C%2Furl%3E%3Cscale%3E150%3C%2Fscale%3E%3Cx%3E30%3C%2Fx%3E%3Cy%3E50%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1157086197&serverTimeOffset=28800', '7', 'noscale');</script></td>
<td><b>Striped Cat</b><br><i>Here kitty, kitty, kitty!</i></td>
<td align='center'>175<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_5013:df279f8825157e5b3f96ce73aa68ce7e' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 175 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_5107.swf%3C%2Furl%3E%3CColorTransform%3E0xAA6600%3C%2FColorTransform%3E%3Cscale%3E200%3C%2Fscale%3E%3Cx%3E45%3C%2Fx%3E%3Cy%3E50%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1157086197&serverTimeOffset=28800', '7', 'noscale');</script></td>
<td><b>Guinea Pig</b><br><i>This little guy will love to burrow in his cage.  And his fur is so soft!</i></td>
<td align='center'>75<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_5107:5799d118cf487171bab92e54de3dd99b' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 75 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_5109.swf%3C%2Furl%3E%3Cscale%3E100%3C%2Fscale%3E%3Cx%3E45%3C%2Fx%3E%3Cy%3E50%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1157086197&serverTimeOffset=28800', '7', 'noscale');</script></td>
<td><b>Gold Fish</b><br><i>Here&#039;s a lovely little goldfish.  Please give him a good home!</i></td>
<td align='center'>40<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_5109:1ba15b7200c2bf3633c34362d9496d54' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 40 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_5149.swf%3C%2Furl%3E%3Cscale%3E150%3C%2Fscale%3E%3Cx%3E40%3C%2Fx%3E%3Cy%3E50%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1157086197&serverTimeOffset=28800', '7', 'noscale');</script></td>
<td><b>Kitty Toy</b><br><i>Give your new kitty something fun to play with!</i></td>
<td align='center'>20<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_5149:51a1a185f243037f29effc1c2e1f4d99' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 20 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_5167.swf%3C%2Furl%3E%3Cscale%3E150%3C%2Fscale%3E%3Cx%3E50%3C%2Fx%3E%3Cy%3E50%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1157086197&serverTimeOffset=28800', '7', 'noscale');</script></td>
<td><b>Goldfish Food</b><br><i>This handy container will feed your pet goldfish all the nutrition he needs for two weeks.</i></td>
<td align='center'>15<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_5167:8e756c08d69511908cd98b0d3154e410' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 15 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_5168.swf%3C%2Furl%3E%3Cscale%3E100%3C%2Fscale%3E%3Cx%3E40%3C%2Fx%3E%3Cy%3E50%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1157086197&serverTimeOffset=28800', '7', 'noscale');</script></td>
<td><b>Pot-Belly Pig Food </b><br><i>Don&#039;t forget to feed your pot-belly pig! This bowl contains enough food to last two weeks.</i></td>
<td align='center'>14<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_5168:209897ab2675a2089bb831e1cdc9a97c' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 14 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_5208_v2.swf%3C%2Furl%3E%3Cscale%3E210%3C%2Fscale%3E%3Cx%3E40%3C%2Fx%3E%3Cy%3E50%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1157086197&serverTimeOffset=28800', '7', 'noscale');</script></td>
<td><b>Spider Food:<br>  Flies</b><br><i>Just what every spider wants -- tasty flies!  This jar will last for two weeks.</i></td>
<td align='center'>16<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_5208:e445b440250499bd2bdae483a5b701f2' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 16 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_5209_v2.swf%3C%2Furl%3E%3Cscale%3E210%3C%2Fscale%3E%3Cx%3E55%3C%2Fx%3E%3Cy%3E60%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1157086197&serverTimeOffset=28800', '7', 'noscale');</script></td>
<td><b>Snake Food</b><br><i>This box provides plenty of nutrition for your pet snake...enough to last two weeks!</i></td>
<td align='center'>18<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_5209:8236f28f7e766d76cfbc7a9209290fda' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 18 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_5211.swf%3C%2Furl%3E%3Cscale%3E210%3C%2Fscale%3E%3Cx%3E40%3C%2Fx%3E%3Cy%3E50%3C%2Fy%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1157086197&serverTimeOffset=28800', '7', 'noscale');</script></td>
<td><b>Rabbit Food:<br> Bowl of Carrots</b><br><i>Don&#039;t forget to feed your rabbit these healthy carrots! This is enough food to last two weeks.</i></td>
<td align='center'>15<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_5211:5e048909d51905d66e83d9f28d727e22' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 15 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_140.swf%3C%2Furl%3E%3CColorTransform%3E0x668822%3C%2FColorTransform%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1157086197&serverTimeOffset=28800', '7', 'noscale');</script></td>
<td><b>Simple Guinea Pig Care Tips</b><br><i>This book contains handy tips about guinea pig care.</i></td>
<td align='center'>40<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_5347:1662d26fb7a114f76e993eb0f7d83572' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 40 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_140.swf%3C%2Furl%3E%3CColorTransform%3E0xCC6666%3C%2FColorTransform%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1157086197&serverTimeOffset=28800', '7', 'noscale');</script></td>
<td><b>Simple Mouse Care Tips</b><br><i>This book contains handy tips about mouse care.</i></td>
<td align='center'>40<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_5367:040d8a245483c08290d18a3b1e8e7843' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 40 Millsbucks?');">
</td>
</tr>
</table>
</form>
<hr noshade size='1'><div align='center'><table align='center' border='0' cellpadding='0' cellspacing='0'><tr>
<td width='21' align='right' height='20'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='21' height='20'></td>
<td width='16' align='right' height='20'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='16' height='20'></td>
<td align='center' height='20' valign='top'><a href='shop.phtml?shop_id=9&p=1' class='page_link'>1</a><span class='page_spacer'>|</span><a href='shop.phtml?shop_id=9&p=2' class='page_link'>2</a><span class='page_spacer'>|</span><a href='shop.phtml?shop_id=9&p=3' class='page_link'>3</a><span class='page_spacer'>|</span><span class='page_selected'>4</span><span class='page_spacer'>|</span><a href='shop.phtml?shop_id=9&p=5' class='page_link'>5</a><span class='page_spacer'>|</span><a href='shop.phtml?shop_id=9&p=6' class='page_link'>6</a><span class='page_spacer'>|</span><a href='shop.phtml?shop_id=9&p=7' class='page_link'>7</a></td>
<td width='16' height='20' align='left'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='16' height='20'></td>
<td width='21' height='20' align='left'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='21' height='20'></td>
</tr></table>
</div>
</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='footer'>
MILLSBERRY &reg;, characters, logos, product names and all related indicia are trademarks of Mills Online, Inc., &copy; 2004-2006.<BR> &reg; denotes Reg. US Pat. & TM Office. All rights reserved.<br>Use of this site signifies your acceptance of the <a href='/town_hall/terms.phtml'><b>Terms and Conditions</b></a>.<br>Please view our <a href='/town_hall/terms.phtml'><b>Privacy Policy</b></a>.
</div>
</div>
<div id='bottom'>&nbsp;</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='debug'>
</div>
</body>
</html>
