<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- 10.100.56.29 -->
<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
<meta http-equiv='imagetoolbar' content='no'>
<meta name='keywords' content="Mills,Millsbury,Milsberry,Milsbury,Millberry,Millbury,Fun games,Spanish language games,Educational games,Active games,Citizen,Cool stuff,Arcade,Music Mix,Fun,Games,Explore,Adventure,Create,Character,Buddy,Care,Academy,School,Gym,Gymnasium,Solver,Science,Project,Town,Pets,Children's games,Games for kid,Kid games,Kids games,Kid's games,Children,Safe gaming">
<title>Millsberry - Grocery Store</title>
<!-- Appending v=# to these files causes them to recache in the user's browser when # changes -->
<link rel='stylesheet' type='text/css' href='/css/theme/royal.css?v=2'>
<link rel='stylesheet' type='text/css' href='/css/template.css?v=2'>
<!--[if lt IE 7.00]>
<link rel='stylesheet' type='text/css' href='/css/ie.css?v=1'>
<![endif]-->
<script type='text/javascript' src='/hidden.js?v=1'></script>
<script type='text/javascript'>
<!--
// Allows users to assign names to their shortcuts
function addShortcut (to_url, default_title) {
	assign_title = default_title;
	var user_title = prompt ("What name do you want to give this shortcut?\nLeave this blank to use the page's existing title.","");
	if (user_title.length > 0) {
		assign_title = base64_encode (utf8_encode (user_title));
	}
	window.location='/process_shortcut.phtml?action=add&url=' + to_url + '&name=' + assign_title;
}
//-->
</script>
<link rel='shortcut icon' href='/favicon.ico'>
</head>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<body>

<div id='top'>
<a href='/index.phtml'><span id='logo'>&nbsp;</span></a>
<div id='layout_head'>
	<div id='login_info'><form name='login' method='post' action='/shop.phtml?shop_id=4&sortby=38&p=2'>
Username <input type='text' name='login_username' size='10'>&nbsp;&nbsp;
Password <input type='password' name='login_pass' size='10'>
<input type='submit' value='Go'>
</form></div>
	<div id='stripe'>
		<div id='stripe_shortcuts'>
			<table width='95' border='0' cellpadding='0' cellspacing='0'><tr>
				<td width='72'></td>
				<td width='23' valign='bottom'></td>
			</tr></table>
		</div>
		<div id='stripe_search'>
			<form name='search' action='/site_search.phtml' method='get'>
			<table width='340' border='0' cellpadding='0' cellspacing='0'><tr>
				<td width='135' align='right'>Address Book&nbsp;</td>
				<td width='105' align='left' valign='middle'><input type='text' name='search' size='15'></td>
				<td width='30' align='center' valign='bottom'><a href='javascript: document.search.submit();' class='stripe_button'><span id='search_button'>&nbsp;</span></a></td>
				<td width='60' align='right'><a href='/town_hall/faq.phtml'>Help</a></td>
			</tr></table>
			</form>
		</div>
	</div>
</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='body'>
<div id='layout_body'>
<div id='side_nav'>

<!-- Exclude these from the stylesheet so they can be translated -->
<style type='text/css'>
#body #layout_body #side_nav .nav_button_hover #nav_signup {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_signup_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_start {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_start_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_the_city {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_the_city_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_downtown {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_downtown_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_arcade {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_arcade_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_my_stuff {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_my_stuff_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_my_home {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_my_place_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_customize {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_customize_1.png') no-repeat;
}
</style>
<!--[if lt IE 7.00]>
<style type='text/css'>
#body #layout_body #side_nav .nav_button_hover #nav_signup {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_signup_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_start {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_start_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_the_city {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_the_city_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_downtown {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_downtown_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_arcade {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_arcade_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_my_stuff {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_my_stuff_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_my_home {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_my_place_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_customize {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_customize_1.png');
}
</style>
<![endif]-->

<a href='/signup.phtml' class='nav_button_hover'><span id='nav_signup' class='nav_button'>&nbsp;</span></a>
<a href='/main_map.phtml' class='nav_button_hover'><span id='nav_the_city' class='nav_button'>&nbsp;</span></a>
<a href='/main_map.phtml?location=downtown' class='nav_button_hover'><span id='nav_downtown' class='nav_button'>&nbsp;</span></a>
<a href='/complex/arcade.phtml' class='nav_button_hover'><span id='nav_arcade' class='nav_button'>&nbsp;</span></a>
<br><img src='http://graphics.millsberry.com/site_gfx/prebuddy.gif' border='1'><div style='font-size: 3px; line-height: 3px;'>&nbsp;</div>

<table width='100%' border='0' cellpadding='5' cellspacing='0' id='side_nav_options'>
<tr>
	<td align='right'>Language</td>
	<td>
		<form name='language_form' method='post' action='/shop.phtml?shop_id=4&sortby=38&p=2'>
		<select name='lang' onChange='document.language_form.submit();' style='width: 70px;'>
			<option value='en' selected>English</option>
			<option value='es' >Espa&ntilde;ol</option>
		</select>
		</form>
	</td>
</tr>

</table>

</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='main'>

	<div id='interior'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '600', '400', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%20%3F%3E%3Cmessage%20success%3D%271%27%20text%20%3D%20%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fsite_gfx%252Finteriors%252Fint_grocery_v29.swf%3C%2Furl%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E600%3C%2Fwidth%3E%3Cheight%3E400%3C%2Fheight%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1153029071', '7', 'noscale');</script></div>
	<div id='interior_stripe'>Grocery Store : <a href='shop.phtml?shop_id=4'>Show All</a></div>
	<!--<a href='/shop.phtml?shop_id=4'>List All</a>-->
	<div id='content'>
	
	If your stomach's growling, we've got the groceries!<br><br><i>Visit <a href='/refer.phtml?r_id=15' target='_blank' style='color: red;'>MyPyramid</a> to help you decide what to put on your grocery list!</i><TABLE BORDER='0' CELLPADDING='0' CELLSPACING='0' WIDTH='100%'><TR>
<TD WIDTH='20%'><IMG SRC='http://graphics.millsberry.com/site_gfx/choose_breakfast/bluebox.gif' WIDTH='20' HEIGHT='20' TITLE='Get your calcium-rich foods' ALT='Dairy'> = Dairy</TD>
<TD WIDTH='20%'><IMG SRC='http://graphics.millsberry.com/site_gfx/choose_breakfast/purplebox.gif' WIDTH='20' HEIGHT='20' TITLE='Go lean with protein' ALT='Meat'> = Protein</TD>
<TD WIDTH='20%'><IMG SRC='http://graphics.millsberry.com/site_gfx/choose_breakfast/orangebox.gif' WIDTH='20' HEIGHT='20' TITLE='Make half your grains whole' ALT='Grain'> = Grain</TD>
<TD WIDTH='20%'><IMG SRC='http://graphics.millsberry.com/site_gfx/choose_breakfast/greenbox.gif' WIDTH='20' HEIGHT='20' TITLE='Vary your veggies' ALT='Vegetables'> = Vegetable</TD>
<TD WIDTH='20%'><IMG SRC='http://graphics.millsberry.com/site_gfx/choose_breakfast/redbox.gif' WIDTH='20' HEIGHT='20' TITLE='Focus on fruits' ALT='Fruit'> = Fruit</TD>
</TR></TABLE>
<div align='center'><table align='center' border='0' cellpadding='0' cellspacing='0'><tr>
<td width='21' align='right' height='20'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='21' height='20'></td>
<td width='16' align='right' height='20'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='16' height='20'></td>
<td align='center' height='20' valign='top'><a href='shop.phtml?shop_id=4&sortby=38&p=1' class='page_link'>1</a><span class='page_spacer'>|</span><span class='page_selected'>2</span><span class='page_spacer'>|</span><a href='shop.phtml?shop_id=4&sortby=38&p=3' class='page_link'>3</a></td>
<td width='16' height='20' align='left'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='16' height='20'></td>
<td width='21' height='20' align='left'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='21' height='20'></td>
</tr></table>
</div><hr size='1' noshade>
<form method='post' action='process_shop.phtml' onSubmit='return can_submit (this);'>
<input type='hidden' name='submitted' value='false'>
<input type='hidden' name='shop_id' value='4'>
<input type='hidden' name='p' value='2'>
<input type='hidden' name='sortby' value='38'>
<table width='100% border='0' cellpadding='2' cellspacing='0'>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%20%3F%3E%3Cmessage%20success%3D%271%27%20text%20%3D%20%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_1785.swf%3C%2Furl%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1153029071', '7', 'noscale');</script></td>
<td><b>Slice of Bread</b><br><i>Perfect for making a sandwich.</i><br><IMG SRC='http://graphics.millsberry.com/site_gfx/choose_breakfast/orangebox.gif' WIDTH='20' HEIGHT='20' TITLE='Make half your grains whole' ALT='Grain'></td>
<td align='center'>15<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_1785:93affd32eeb40b5d219fc379d672db36' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 15 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%20%3F%3E%3Cmessage%20success%3D%271%27%20text%20%3D%20%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_2801.swf%3C%2Furl%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1153029071', '7', 'noscale');</script></td>
<td><b>Peanut Butter Toast Crunch&reg;</b><br><i>Wow! Peanut Butter! Made with whole grain! Goes great with fresh fruit!</i><br><IMG SRC='http://graphics.millsberry.com/site_gfx/choose_breakfast/orangebox.gif' WIDTH='20' HEIGHT='20' TITLE='Make half your grains whole' ALT='Grain'></td>
<td align='center'>65<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_2801:d90c7340db70b52ab71f2fd80f56f009' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 65 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%20%3F%3E%3Cmessage%20success%3D%271%27%20text%20%3D%20%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_3485_v2.swf%3C%2Furl%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1153029071', '7', 'noscale');</script></td>
<td><b>Boo Berry&reg; Cereal</b><br><i>Delicious berry cereal! And it&#039;s a good source of whole grain! Goes great with fresh fruit!</i><br><IMG SRC='http://graphics.millsberry.com/site_gfx/choose_breakfast/orangebox.gif' WIDTH='20' HEIGHT='20' TITLE='Make half your grains whole' ALT='Grain'></td>
<td align='center'>65<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_3485:7dc3ceb8016328d6e89fe8a679fb2562' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 65 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%20%3F%3E%3Cmessage%20success%3D%271%27%20text%20%3D%20%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_3506_v2.swf%3C%2Furl%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1153029071', '7', 'noscale');</script></td>
<td><b>Count Chocula&reg; Cereal</b><br><i>Delicious chocolatey cereal! And it&#039;s a good source of whole grain! Goes great with fresh fruit!</i><br><IMG SRC='http://graphics.millsberry.com/site_gfx/choose_breakfast/orangebox.gif' WIDTH='20' HEIGHT='20' TITLE='Make half your grains whole' ALT='Grain'></td>
<td align='center'>65<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_3506:b9bec2d84e08727d67bee912e49f548c' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 65 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%20%3F%3E%3Cmessage%20success%3D%271%27%20text%20%3D%20%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_3508_v2.swf%3C%2Furl%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1153029071', '7', 'noscale');</script></td>
<td><b>Frankenberry&reg; Cereal</b><br><i>Delicious berry cereal! And it&#039;s a good source of whole grain! Goes great with fresh fruit!</i><br><IMG SRC='http://graphics.millsberry.com/site_gfx/choose_breakfast/orangebox.gif' WIDTH='20' HEIGHT='20' TITLE='Make half your grains whole' ALT='Grain'></td>
<td align='center'>65<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_3508:6f72895e18acd34dab2230361b1cf9ba' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 65 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%20%3F%3E%3Cmessage%20success%3D%271%27%20text%20%3D%20%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_4809.swf%3C%2Furl%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1153029071', '7', 'noscale');</script></td>
<td><b>Slice of Whole Wheat Bread</b><br><i>Perfect for making a little sandwich.</i><br><IMG SRC='http://graphics.millsberry.com/site_gfx/choose_breakfast/orangebox.gif' WIDTH='20' HEIGHT='20' TITLE='Make half your grains whole' ALT='Grain'></td>
<td align='center'>10<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_4809:8ce18abc6c0934064da1b90b8952103e' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 10 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%20%3F%3E%3Cmessage%20success%3D%271%27%20text%20%3D%20%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_4907_v2.swf%3C%2Furl%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1153029071', '7', 'noscale');</script></td>
<td><b>Chocolate Lucky Charms&reg; Cereal</b><br><i>Very very chocolatey! And it&#039;s a good source of whole grain! Goes great with fresh fruit!</i><br><IMG SRC='http://graphics.millsberry.com/site_gfx/choose_breakfast/orangebox.gif' WIDTH='20' HEIGHT='20' TITLE='Make half your grains whole' ALT='Grain'></td>
<td align='center'>65<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_4907:a891494c8af186b418a5b0d4369a09fe' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 65 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%20%3F%3E%3Cmessage%20success%3D%271%27%20text%20%3D%20%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_5207.swf%3C%2Furl%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1153029071', '7', 'noscale');</script></td>
<td><b>Honey Nut Cheerios&reg;</b><br><i>A tasty part of breakfast from the hive
that&#039;s nuts about honey. Made with whole grain! Goes great with fresh fruit!</i><br><IMG SRC='http://graphics.millsberry.com/site_gfx/choose_breakfast/orangebox.gif' WIDTH='20' HEIGHT='20' TITLE='Make half your grains whole' ALT='Grain'></td>
<td align='center'>60<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_5207:e8a795a3ae43125d6415a32fe3e5a537' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 60 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%20%3F%3E%3Cmessage%20success%3D%271%27%20text%20%3D%20%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_6009.swf%3C%2Furl%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1153029071', '7', 'noscale');</script></td>
<td><b>Orange Half</b><br><i>Oranges are a great source of Vitamin C, which is highly beneficial to your health.
</i><br><IMG SRC='http://graphics.millsberry.com/site_gfx/choose_breakfast/redbox.gif' WIDTH='20' HEIGHT='20' TITLE='Focus on fruits' ALT='Fruit'></td>
<td align='center'>18<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_6009:0bb018394e13a4bbe09d4920ebb1736e' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 18 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%20%3F%3E%3Cmessage%20success%3D%271%27%20text%20%3D%20%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_6010.swf%3C%2Furl%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1153029071', '7', 'noscale');</script></td>
<td><b>Yogurt</b><br><i>A fantastic source of calcium and protein that tastes great, too.
</i><br><IMG SRC='http://graphics.millsberry.com/site_gfx/choose_breakfast/bluebox.gif' WIDTH='20' HEIGHT='20' TITLE='Get your calcium-rich foods' ALT='Dairy'></td>
<td align='center'>45<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_6010:8eeb908a4b2a4577a74208d7201a937d' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 45 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%20%3F%3E%3Cmessage%20success%3D%271%27%20text%20%3D%20%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_6027.swf%3C%2Furl%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1153029071', '7', 'noscale');</script></td>
<td><b>Plain Bagel</b><br><i>Delicious whether topped with butter, cream cheese, jam or another delicious spread.</i><br><IMG SRC='http://graphics.millsberry.com/site_gfx/choose_breakfast/orangebox.gif' WIDTH='20' HEIGHT='20' TITLE='Make half your grains whole' ALT='Grain'></td>
<td align='center'>45<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_6027:91012de4d5757752bd6ccce4a66134b3' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 45 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%20%3F%3E%3Cmessage%20success%3D%271%27%20text%20%3D%20%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_6028.swf%3C%2Furl%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1153029071', '7', 'noscale');</script></td>
<td><b>Grapefruit Half</b><br><i>This excellent source of Vitamin C is an ideal addition to any breakfast.
</i><br><IMG SRC='http://graphics.millsberry.com/site_gfx/choose_breakfast/redbox.gif' WIDTH='20' HEIGHT='20' TITLE='Focus on fruits' ALT='Fruit'></td>
<td align='center'>18<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_6028:7335580fc5de5e087de72f3f1d451269' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 18 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%20%3F%3E%3Cmessage%20success%3D%271%27%20text%20%3D%20%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_6029.swf%3C%2Furl%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1153029071', '7', 'noscale');</script></td>
<td><b>Fried Egg</b><br><i>Perfect with a slice or two of toast!</i><br><IMG SRC='http://graphics.millsberry.com/site_gfx/choose_breakfast/purplebox.gif' WIDTH='20' HEIGHT='20' TITLE='Go lean with protein' ALT='Meat'></td>
<td align='center'>15<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_6029:c47e271d82e840bb097ac4d19aca58ac' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 15 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%20%3F%3E%3Cmessage%20success%3D%271%27%20text%20%3D%20%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_6030.swf%3C%2Furl%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1153029071', '7', 'noscale');</script></td>
<td><b>Hard Boiled Egg</b><br><i>Eggs are an excellent source of protein, perfect for starting your day.</i><br><IMG SRC='http://graphics.millsberry.com/site_gfx/choose_breakfast/purplebox.gif' WIDTH='20' HEIGHT='20' TITLE='Go lean with protein' ALT='Meat'></td>
<td align='center'>14<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_6030:89bc7efe50fdd78fd47cd4f2602fdec6' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 14 Millsbucks?');">
</td>
</tr>
<tr>
<td width='100' height='125' align='center'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '100', '100', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%20%3F%3E%3Cmessage%20success%3D%271%27%20text%20%3D%20%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fitems%252Fitem_6031.swf%3C%2Furl%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E100%3C%2Fwidth%3E%3Cheight%3E100%3C%2Fheight%3E%3Csteps%3E10%3C%2Fsteps%3E%3Cdelay%3E50%3C%2Fdelay%3E%3Cvisible%3E1%3C%2Fvisible%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1153029071', '7', 'noscale');</script></td>
<td><b>Kix&reg; Cereal</b><br><i>Kid tested and mother approved, these corn puffs stay crispier in milk than regular flakes. Goes great with fresh fruit!</i><br><IMG SRC='http://graphics.millsberry.com/site_gfx/choose_breakfast/orangebox.gif' WIDTH='20' HEIGHT='20' TITLE='Make half your grains whole' ALT='Grain'></td>
<td align='center'>60<br>Millsbucks</td>
<td width='45' align='center'><input type='image' name='buy_6031:4af6f4c0bc069bb1ceb9b865b8f02064' src='http://graphics.millsberry.com/site_gfx/buy_icon.gif' border='0' alt='Buy!' title='Buy!' onClick="return confirm ('Are you SURE you wish to buy this for 60 Millsbucks?');">
</td>
</tr>
</table>
</form>
<hr noshade size='1'><div align='center'><table align='center' border='0' cellpadding='0' cellspacing='0'><tr>
<td width='21' align='right' height='20'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='21' height='20'></td>
<td width='16' align='right' height='20'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='16' height='20'></td>
<td align='center' height='20' valign='top'><a href='shop.phtml?shop_id=4&sortby=38&p=1' class='page_link'>1</a><span class='page_spacer'>|</span><span class='page_selected'>2</span><span class='page_spacer'>|</span><a href='shop.phtml?shop_id=4&sortby=38&p=3' class='page_link'>3</a></td>
<td width='16' height='20' align='left'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='16' height='20'></td>
<td width='21' height='20' align='left'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='21' height='20'></td>
</tr></table>
</div>
</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='footer'>
<span style='font-size: 11px;'>THIS PAGE CONTAINS ADVERTISEMENTS</span><br>
MILLSBERRY, characters, logos, product names and all related indicia are trademarks of Mills Online, Inc., &copy; 2004-2006.<BR> &reg; denotes Reg. US Pat. & TM Office. All rights reserved.<br>Use of this site signifies your acceptance of the <a href='/town_hall/terms.phtml'><b>Terms and Conditions</b></a>.<br>Please view our <a href='/town_hall/terms.phtml'><b>Privacy Policy</b></a>
</div>
</div>
<div id='bottom'>&nbsp;</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='debug'>
</div>
</body>
</html>
