<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- www.millsberry.com -->
<html>
<head>
<meta http-equiv='imagetoolbar' content='no'>
<meta name='keywords' content="Mills,Millsbury,Milsberry,Milsbury,Millberry,Millbury,Fun games,Spanish language games,Educational games,Active games,Citizen,Cool stuff,Arcade,Music Mix,Fun,Games,Explore,Adventure,Create,Character,Buddy,Care,Academy,School,Gym,Gymnasium,Solver,Science,Project,Town,Pets,Children's games,Games for kid,Kid games,Kids games,Kid's games,Children,Safe gaming">
<title>Millsberry - Featured Story</title>
<script type='text/javascript' src='/common.js?v=2'></script>
<script type="text/javascript" src="/js/swfobject.js"></script>
<link rel='shortcut icon' type='image/x-icon' href='/favicon.ico'>
<!-- Appending v=# to these files causes them to recache in the user's browser when # changes -->
<link rel='stylesheet' type='text/css' href='/css/theme/royal.css?v=2'>
<link rel='stylesheet' type='text/css' href='/css/template.css?v=5'>
<link rel='stylesheet' type='text/css' href='/css/global.css?v=2'>
<!--[if lt IE 7.00]>
<link rel='stylesheet' type='text/css' href='/css/template.ie.css?v=1'>
<link rel='stylesheet' type='text/css' href='/css/global.ie.css?v=1'>
<![endif]-->
</head>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<body>
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript"> _uacct = "UA-1272972-1"; urchinTracker();</script>
<div id='top'>
    <a href='/'><span id='logo'>&nbsp;</span></a>
    <div id='layout_head'>
       <div id='login_info'>
           4,845 citizens online now&nbsp;|&nbsp; <a href='/town_hall/faq.phtml'>HELP</a>
       </div> <!--login_info-->
       <div id='stripe'>
           <script type='text/javascript'>flash_object ('http://graphics.millsberry.com/template/top_nav.swf', '747', '36', '&url=http%3A%2F%2Fwww.millsberry.com%2Ftop_nav_xml.phtml&unixTimeStamp=1193457118&serverTimeOffset=28800', '7', 'noscale', 'transparent');</script> 
       </div> <!-- stripe -->
    </div> <!-- layout_head -->
</div> <!-- top -->
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='body'>
<div id='layout_body'>
<div id='side_nav'>
<script type='text/javascript'>flash_object ('http://graphics.millsberry.com/template/side_nav.swf', '150', '1250', '&url=http%3A%2F%2Fwww.millsberry.com%2Fside_nav_xml.phtml%3Fpage_relative_url%3D%252Ffeatured_story.phtml%253Fdate%253D20071025%26login_status%3D0%26now%3D1193457118&unixTimeStamp=1193457118&serverTimeOffset=28800', '7', 'noscale', 'transparent');</script></div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='main'>
<div id='gazette_banner'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '580', '75', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fsite_gfx%252Fgazette_banner.swf%3C%2Furl%3E%3Cscale%3E100%3C%2Fscale%3E%3Cx%3E0%3C%2Fx%3E%3Cy%3E0%3C%2Fy%3E%3CstopItemAnimation%3E1%3C%2FstopItemAnimation%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E580%3C%2Fwidth%3E%3Cheight%3E75%3C%2Fheight%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1193457118&serverTimeOffset=28800', '7', 'noscale', 'transparent');</script></div><div id='content'>
<div id='gazette_story'>
<div align='center'><font size='4'><b>THE 3RD ANNUAL MILLSBERRY COMMUNITY CENTER HALLOWEEN CHALLENGE</b></font><br>
<img src='http://graphics.millsberry.com/site_gfx/interiors/gazette/gazette_20071025.jpg' border='1'>
</div>
<br>
<b>Thursday, October 25, 2007</b> &mdash; It&#039;s a tradition in Millsberry, and one I look forward to every year. That&#039;s right: the Millsberry Community Center Halloween Challenge is on now, so join in the fun.<br><br>Just use the new navigation bar at the top of the My Place page to move around town and visit your friends and neighbors. Every time you arrive at a neighbor&#039;s home, you&#039;ll see a new doorbell out in front. Ring the bell and right away you&#039;ll receive a treat. <br><br>There will be lots of tasty snacks to tickle your taste buds and some really fun (and rare) prizes, too. You never know what you&#039;ll get, so visit as many friends and neighbors as you can to increase your winnings. <br><br><br>
<br>
And the more homes you visit, the better your chances of winning a trophy. We&#039;ll award a gold, silver and bronze trophy to the first, second and third place winners in the Challenge. <br><br>What better way is there to celebrate the Halloween season? Get your costume and start collecting your treats today!<br></div>
</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='footer'>
MILLSBERRY &reg;, characters, logos, product names and all related indicia are trademarks of Mills Online, Inc., &copy; 2004-2006.<BR> &reg; denotes Reg. US Pat. & TM Office. All rights reserved.<br>
Use of this site signifies your acceptance of the <a href='/town_hall/terms.phtml'><b>Terms and Conditions</b></a>.
Please view our <a href='/town_hall/terms.phtml'><b>Privacy Policy</b></a>.
</div>
</div>
<div id='bottom'>&nbsp;</div>
</div>
</body>
</html>
