<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- www.millsberry.com -->
<html>
<head>
<meta http-equiv='imagetoolbar' content='no'>
<meta name='keywords' content="Mills,Millsbury,Milsberry,Milsbury,Millberry,Millbury,Fun games,Spanish language games,Educational games,Active games,Citizen,Cool stuff,Arcade,Music Mix,Fun,Games,Explore,Adventure,Create,Character,Buddy,Care,Academy,School,Gym,Gymnasium,Solver,Science,Project,Town,Pets,Children's games,Games for kid,Kid games,Kids games,Kid's games,Children,Safe gaming">
<title>Millsberry - Citizen of the Week</title>
<script type='text/javascript' src='/common.js?v=2'></script>
<script type="text/javascript" src="/js/swfobject.js"></script>
<link rel='shortcut icon' type='image/x-icon' href='/favicon.ico'>
<!-- Appending v=# to these files causes them to recache in the user's browser when # changes -->
<link rel='stylesheet' type='text/css' href='/css/theme/royal.css?v=2'>
<link rel='stylesheet' type='text/css' href='/css/template.css?v=5'>
<link rel='stylesheet' type='text/css' href='/css/global.css?v=2'>
<!--[if lt IE 7.00]>
<link rel='stylesheet' type='text/css' href='/css/template.ie.css?v=1'>
<link rel='stylesheet' type='text/css' href='/css/global.ie.css?v=1'>
<![endif]-->
</head>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<body>
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript"> _uacct = "UA-1272972-1"; urchinTracker();</script>
<div id='top'>
    <a href='/'><span id='logo'>&nbsp;</span></a>
    <div id='layout_head'>
       <div id='login_info'>
           3,142 citizens online now&nbsp;|&nbsp; <a href='/town_hall/faq.phtml'>HELP</a>
       </div> <!--login_info-->
       <div id='stripe'>
           <script type='text/javascript'>flash_object ('http://graphics.millsberry.com/template/top_nav.swf', '747', '36', '&url=http%3A%2F%2Fwww.millsberry.com%2Ftop_nav_xml.phtml&unixTimeStamp=1192070895&serverTimeOffset=28800', '7', 'noscale', 'transparent');</script> 
       </div> <!-- stripe -->
    </div> <!-- layout_head -->
</div> <!-- top -->
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='body'>
<div id='layout_body'>
<div id='side_nav'>
<script type='text/javascript'>flash_object ('http://graphics.millsberry.com/template/side_nav.swf', '150', '1250', '&url=http%3A%2F%2Fwww.millsberry.com%2Fside_nav_xml.phtml%3Fpage_relative_url%3D%252Fcotw.phtml%253Fuser%253Dmstokuca%26login_status%3D0%26now%3D1192070895&unixTimeStamp=1192070895&serverTimeOffset=28800', '7', 'noscale', 'transparent');</script></div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='main'>
<div id='gazette_banner'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '580', '75', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fsite_gfx%252Fgazette_banner.swf%3C%2Furl%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E580%3C%2Fwidth%3E%3Cheight%3E75%3C%2Fheight%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1192070895&serverTimeOffset=28800', '7', 'noscale', 'transparent');</script></div><div id='content'>
<span style='float: right; width: 280px; height: 187px; margin: 0 0 5px 5px; border: 1px solid black;'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/buddy/buddy_featured.swf', '280', '187', 'userName=mstokuca&buddyTimeStamp=20071004&buddyScriptURL=http%3A%2F%2Fwww.millsberry.com%2Fbuddy%2Fprocess_buddy.phtml&unixTimeStamp=1192070895&serverTimeOffset=28800', '', 'exactfit', 'transparent');</script></span>
Meet <b>Samantha</b>, our Millsberry Citizen of the Week!<br><br>Samantha moved to Millsberry in November, 2005 and lives at <a href='/home/?user=mstokuca'>66023 Panther Road</a> in Westridge.<br><br>She just loves a good mystery and one tour around her house will tell you that. She's got some ancient rock paintings of Sylvie and a beautiful treasure map on display there. But it's no mystery how she's become such a good athlete: she eats well and has her 2007 Nutrition Month Certificate to show for it.<br><br>Samantha loves Modern Rock, Disco and Pop music. And her DJ room is just the place to practice to spin some discs. Boy, does she know how to mix those tunes. You'll be dancing all afternoon! Later on, you can relax in the game room and play a bit on her vintage hockey dome game, throw some darts or just read a book. <br><br>Congratulations to you, Samantha, for being name our Millsberry Citizen of the Week. We're proud to have you for our neighbor.<br></div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='footer'>
MILLSBERRY &reg;, characters, logos, product names and all related indicia are trademarks of Mills Online, Inc., &copy; 2004-2006.<BR> &reg; denotes Reg. US Pat. & TM Office. All rights reserved.<br>
Use of this site signifies your acceptance of the <a href='/town_hall/terms.phtml'><b>Terms and Conditions</b></a>.
Please view our <a href='/town_hall/terms.phtml'><b>Privacy Policy</b></a>.
</div>
</div>
<div id='bottom'>&nbsp;</div>
</div>
</body>
</html>
