
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- www.millsberry.com -->
<html>
<!--[if lt IE 7]>
        <script type="text/javascript" src="/js/unitpngfix/unitpngfix.js"></script>
<![endif]--> 
<head>


    <meta http-equiv="imagetoolbar" content="no">
    <meta name="keywords" content="Mills,Millsbury,Milsberry,Milsbury,Millberry,Millbury,Fun games,Spanish language games,Educational games,Active games,Citizen,Cool stuff,Arcade,Music Mix,Fun,Games,Explore,Adventure,Create,Character,Buddy,Care,Academy,School,Gym,Gymnasium,Solver,Science,Project,Town,Pets,Children's games,Games for kid,Kid games,Kids games,Kid's games,Children,Safe gaming">
    <meta name="description" content="Explore the virtual world of Millsberry with your own customized buddy. Design a home, play games, grow a farm that helps those in need, and much more!">
    <title>Millsberry - Featured Story</title>
    
    
    <script type="text/javascript" src="/common.js?v=3"></script>
    <script type="text/javascript" src="/js/swfobject.js"></script>
    <script type="text/javascript" src="/js/jquery/jquery-1.3.2.min.js"></script>
    <script type="text/javascript" src="/js/jquery/jquery-ui-1.7.2.custom.min.js"></script>
    <script type="text/javascript" src="/js/jquery/jquery-millsberry.js"></script>

    <link rel="stylesheet" type="text/css" href="/css/theme/royal.phtml?v=3">
    <link rel="stylesheet" type="text/css" href="/css/template.css?v=6">
    <link rel="stylesheet" type="text/css" href="/css/global.css?v=3">
    <link rel="stylesheet" type="text/css" href="/css/jquery/jquery-custom.css">
    <link rel="stylesheet" type="text/css" href="/css/jquery/jquery-millsberry-css.phtml">

    <!--[if lt IE 7.00]>
        <link rel="stylesheet" type="text/css" href="/css/template.ie.css?v=2">
        <link rel="stylesheet" type="text/css" href="/css/global.ie.css?v=2">
        <link rel="stylesheet" type="text/css" href="/css/jquery/jquery-millsberry-css.ie.phtml">
        <![endif]-->

</head>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<body  >

<script src="http://www.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript"> _uacct = "UA-1272972-1"; urchinTracker();</script>
<!-- BEGIN: LOGIN POPUP -->
<div id="login_popup" class="dlg_modal" style="width:535px; height:295px; display:none;">
	<div id="close_overlay" class="close_overlay" onclick="closeDialogWindow('login_popup')" style="position:relative;left:465px;top:-10px;"></div>
	<div align="left" style="display:block; position:relative; top:55px; left:103px; width:320px">
		
		<form action='' method="post">
			<fieldset style="border:none">
				<div id="login_name_container" class="input_container input_container_inactive " style="width:157px; height:32px; text-align: center; ">
					<div id="login_name" style="position:relative; top:5px;">
						<input width="76" type="text" name="login_username" id="login_username" class="jq_input_field text ui-widget-content ui-corner-all input_field" />
					</div>
				</div>
				<div id="login_password_container" class="input_container input_container_inactive " style="width:157px; height:32px; text-align: center; ">
					<div id="login_password" style="position:relative; top:5px;">
						<input width="76" type="password" name="login_pass" id="login_pass" value="" class="jq_input_field text ui-widget-content ui-corner-all input_field" />
					</div>
				</div>
				<!-- width="76" height="27"-->
				<div style="position:relative; top:7px; left:-100px; width:255px; height:27px; " >
										<div style="float:right; ">
						<input type="image" value="Login" src="http://graphics.millsberry.com/site_gfx/login/go-button.gif">						
					</div>
						
				</div>
				
			</fieldset>
		</form>	

		<div style="float:left; position:relative; top:-29px; left:265px">
			<a href="/signup.phtml"><img src="http://graphics.millsberry.com/site_gfx/login/start-button.gif" width="97" height="27" border="0" name="start" /></a>					
		</div>
		
	</div>
</div>
<!-- END: LOGIN POPUP -->


<div id='top'>
	    <a href='/'><span id='logo'>&nbsp;</span></a>
    
    <div id='layout_head'>
		<div id='login_info'>
			3,740 citizens online now&nbsp;|&nbsp; <a href='/town_hall/faq.phtml'>HELP</a>
		</div> <!--login_info-->
		<div id='stripe'>
			     <div id="top_nav_flashcontent">
     <!--default content-->
	 </div>

	<script type="text/javascript">
		// <![CDATA[
        
        // redirect to the upgrade page if flash is installed, but version is too low
		var version = deconcept.SWFObjectUtil.getPlayerVersion();
        if(version["major"] < 8 && version["major"] > 0) {
            window.location='/flash.phtml';
        } else {
            writeFlashContent();
        }
        
        function writeFlashContent() {
            var so = new SWFObject("http://graphics.millsberry.com/template/top_nav_v2.swf?url=http%3A%2F%2Fwww.millsberry.com%2Ftop_nav_xml.phtml", "top_nav", "750", "45", "8");
            so.addParam("wmode", "transparent");
            so.addParam("scale", "noscale");
            so.addParam("AllowScriptAccess", "always");
            so.useExpressInstall('http://graphics.millsberry.com/expressinstall.swf');
            so.write("top_nav_flashcontent");
        }
		
		// ]]>
	</script>
		</div> <!-- stripe -->
    </div> <!-- layout_head -->
</div> <!-- top -->

<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='body'>
	<div id='layout_body'>		
		<div id='side_nav'>
			<script type='text/javascript'>flash_object ('http://graphics.millsberry.com/template/side_nav_v3.swf', '155', '1300', '&url=http%3A%2F%2Fwww.millsberry.com%2Fside_nav_xml.phtml%3Fpage_relative_url%3D%252Ffeatured_story.phtml%253Fdate%253D20100325%26now%3D1269810574&unixTimeStamp=1269810574&serverTimeOffset=28800', '8', 'noscale', 'transparent');</script>		</div>
		<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
		<div id='main'>		
			<div id='content'>
<div id='gazette_story'>
    <div align='center'>
        <font size='4'><b>Big Nate at Bookends!</b></font><br>
                                <img src='http://graphics.millsberry.com/site_gfx/interiors/gazette/gazette_20100325.jpg' border='1' width='280' height='200'>
                        </div>
        <div id='gazette_byline'><em>By Audrey Smythe-Wei<br>Editor-in-Chief</em></div>
        <b>Thursday, March 25, 2010</b> &mdash;
    Big Nate has come to Millsberry. The 11-year-old recently stopped by <a href="http://millsberry.com/shop.phtml?shop_id=2">Bookends</a> to drop off advance copies of his new book, Big Nate: In a Class by Himself. While there, he said &#039;hi&#039; to some of the shoppers and told a few pretty funny stories.<br><br>When asked what brought him to Millsberry, Nate said, &quot;My <a href="http://millsberry.com/shop.phtml?shop_id=2">new book&#039;s</a> coming out soon and I wanted to be sure everybody here got a chance to read it.&quot; He went on to explain that the book is about his school and his friends as well as his teacher, Mrs. Godfrey.<br><br><a href="http://millsberry.com/shop.phtml?shop_id=2">Big Nate</a> said he&#039;d be in town for a bit, and mentioned he&#039;d love to play some games in the arcade. When asked about school, Nate shrugged. &quot;I&#039;m not the world record holder for detentions for nothing.&quot; <br>
<br>
Along with his book, Nate also brought some of his favorite things to share, including his favorite soccer. You can get it in <a href="http://millsberry.com/shop.phtml?shop_id=2">Bookends</a> too for your avatar! <a href="http://millsberry.com/shop.phtml?shop_id=2">Check it out today</a>&mdash;you may even see Big Nate there!
    </div>

        </div>
		</div>
		<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
		<div id='footer'>
		    
<div id="ad_spot">
    <a href="javascript:void(0);"  onMouseOver="showspot(); return false;" onMouseOut="hidespot(); return false;" >
        <img src="http://graphics.millsberry.com/site_gfx/adSpot_icon.gif" width="30" height="25"  border="0"/>
    </a>
</div>
<div id="warning" style="position:absolute; visibility:hidden;">
    <img src="http://graphics.millsberry.com/site_gfx/adSpot_popup.gif" hspace="10" width="258" height="49" alt="" border="0"/>
</div>

MILLSBERRY &reg;, characters, logos, product names 
and all related indicia are trademarks of Mills Online, Inc., &copy; 
2004-2010.<BR> &reg; denotes Reg. US Pat. & TM Office. All rights 
reserved.<br>
Use of this site signifies your acceptance of the <a href='/town_hall/terms.phtml'><b>Terms and Conditions</b></a>.
Please view our <a href='/town_hall/terms.phtml'><b>Privacy Policy</b></a>.<br>
<br>

		</div>
	</div>
	<div id='bottom'>&nbsp;</div>
</div>


</body>
</html>