<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- 10.100.56.28 -->
<html>
<head>
<meta http-equiv='imagetoolbar' content='no'>
<meta name='keywords' content="Mills,Millsbury,Milsberry,Milsbury,Millberry,Millbury,Fun games,Spanish language games,Educational games,Active games,Citizen,Cool stuff,Arcade,Music Mix,Fun,Games,Explore,Adventure,Create,Character,Buddy,Care,Academy,School,Gym,Gymnasium,Solver,Science,Project,Town,Pets,Children's games,Games for kid,Kid games,Kids games,Kid's games,Children,Safe gaming">
<title>Millsberry - Community Pool</title>
<script type='text/javascript' src='/common.js?v=2'></script>
<link rel='shortcut icon' type='image/x-icon' href='/favicon.ico'>
<!-- Appending v=# to these files causes them to recache in the user's browser when # changes -->
<link rel='stylesheet' type='text/css' href='/css/theme/royal.css?v=2'>
<link rel='stylesheet' type='text/css' href='/css/template.css?v=5'>
<link rel='stylesheet' type='text/css' href='/css/global.css?v=2'>
<!--[if lt IE 7.00]>
<link rel='stylesheet' type='text/css' href='/css/template.ie.css?v=1'>
<link rel='stylesheet' type='text/css' href='/css/global.ie.css?v=1'>
<![endif]-->
</head>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<body>

<!--<div id='leaderboard'><h2>Leader Board</h2></div>-->
<div id='top'>
<a href='/'><span id='logo'>&nbsp;</span></a>
<div id='layout_head'>
	<div id='login_info'><form name='login' method='post' action='/communitycenter/pool.phtml'>
Username <input type='text' name='login_username' size='10'>&nbsp;&nbsp;
Password <input type='password' name='login_pass' size='10'>
<input type='submit' value='Go'>
</form></div>
	<div id='stripe'>
		<div id='stripe_shortcuts'>
			<table width='95' border='0' cellpadding='0' cellspacing='0'><tr>
				<td width='72'></td>
				<td width='23' valign='bottom'></td>
			</tr></table>
		</div>
		<div id='stripe_search'>
			<form name='search' action='/site_search.phtml' method='get'>
			<table width='340' border='0' cellpadding='0' cellspacing='0'><tr>
				<td width='135' align='right'>Address Book&nbsp;</td>
				<td width='105' align='left' valign='middle'><input type='text' name='search' size='15'></td>
				<td width='30' align='center' valign='bottom'><a href='javascript: document.search.submit();' class='stripe_button'><span id='search_button'>&nbsp;</span></a></td>
				<td width='60' align='right'><a href='/town_hall/faq.phtml'>Help</a></td>
			</tr></table>
			</form>
		</div>
	</div>
</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='body'>
<div id='layout_body'>
<div id='side_nav'>
<a href='/main_map.phtml' class='nav_button_hover'><span id='nav_the_city' class='nav_button'>&nbsp;</span></a>
<a href='/main_map.phtml?location=downtown' class='nav_button_hover'><span id='nav_downtown' class='nav_button'>&nbsp;</span></a>
<a href='/tour.phtml' class='nav_button_hover'><span id='nav_tour' class='nav_button'>&nbsp;</span></a>
<a href='/signup.phtml' class='nav_button_hover'><span id='nav_signup' class='nav_button'>&nbsp;</span></a>
<a href='/complex/arcade.phtml' class='nav_button_hover'><span id='nav_arcade' class='nav_button'>&nbsp;</span></a>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='main'>

<div id='interior'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/site_gfx/interiors/int_pool_v1.swf', '600', '400', '&unixTimeStamp=1165314547&serverTimeOffset=28800', '7', 'noscale');</script></div>
<div id='interior_stripe'>Community Pool</div>
<div id='content'>
Welcome to the Millsberry public pool! The pool is free to all, and open year-round, in all but the coldest weather. Swim some laps, play some water polo, or practice your diving under the watchful eye of Life Guard Peter Trofimov. You could even play a round of bumper boats with a friend.
<br><br>
<h4>Pool Safety Tips</h4>
<ul class='list'>
<li>Never swim in a pool where there is not a lifeguard on duty or an adult present.</li>
<li>Never go swimming by yourself.</li>
<li>Never run near a swimming pool. If the ground around the pool is wet, you could fall and hit your head.</li>
<li>Never dive into a pool headfirst unless there are signs posted that say it is safe to do so.</li>
<li>Inflatable toys and water-wings are not life preservers.</li>
<li>If you are swimming in an outdoor pool, be sure to reapply your sunscreen every hour.</li>
<li>If possible, take swimming lessons before going swimming in a pool.</li>
<li>Be sure that there is a phone nearby in case of an emergency.</li>
<li>Try not to swallow the pool water. It can have chemicals and germs in it that could make you sick.</li>
<li>When swimming in a public pool, shower before and after you go in the water.</li>
<li>Make sure that you follow all of the rules posted at a public pool.</li>
<li>Never take a glass container near a swimming pool.</li>
</ul>
<br>
<hr noshade size='1'>
<table border='0' cellpadding='2' cellspacing='0' width='100%'>
<tr><td width='155' height='112' align='center'><a href='/gamepages/flashgame_ctp.phtml?game_id=440'><img src='http://graphics.millsberry.com/game_interiors/thumbnails/interior_440.gif' width='150' height='100' border='1'></a></td>
<td><b>Bumper Boats</b><br>Bump your opponents out of the ring!<br>
<img src='http://graphics.millsberry.com/site_gfx/stat_fit_v1.gif' width='25' height='20' border='0'></td>
<td align='center' width='60'><a href='/gamepages/hiscores.phtml?game_id=440'>High<br>Scores</a></td></tr>
<tr><td colspan='3' height='6'><span style='font-size: 1px; line-height: 1px;'>&nbsp;</span></td></tr>
</table>
</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='footer'>
<span style='font-size: 11px;'>THIS PAGE CONTAINS ADVERTISEMENTS</span><br>
MILLSBERRY &reg;, characters, logos, product names and all related indicia are trademarks of Mills Online, Inc., &copy; 2004-2006.<BR> &reg; denotes Reg. US Pat. & TM Office. All rights reserved.<br>
Use of this site signifies your acceptance of the <a href='/town_hall/terms.phtml'><b>Terms and Conditions</b></a>.
Please view our <a href='/town_hall/terms.phtml'><b>Privacy Policy</b></a>.
</div>
</div>
<div id='bottom'>&nbsp;</div>
</div>
</body>
</html>
