<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- www.millsberry.com -->
<html>
<head>
<meta http-equiv='imagetoolbar' content='no'>
<meta name='keywords' content="Mills,Millsbury,Milsberry,Milsbury,Millberry,Millbury,Fun games,Spanish language games,Educational games,Active games,Citizen,Cool stuff,Arcade,Music Mix,Fun,Games,Explore,Adventure,Create,Character,Buddy,Care,Academy,School,Gym,Gymnasium,Solver,Science,Project,Town,Pets,Children's games,Games for kid,Kid games,Kids games,Kid's games,Children,Safe gaming">
<title>Millsberry - Citizen of the Week</title>
<script type='text/javascript' src='/common.js?v=2'></script>
<script type="text/javascript" src="/js/swfobject.js"></script>
<link rel='shortcut icon' type='image/x-icon' href='/favicon.ico'>
<!-- Appending v=# to these files causes them to recache in the user's browser when # changes -->
<link rel='stylesheet' type='text/css' href='/css/theme/royal.css?v=2'>
<link rel='stylesheet' type='text/css' href='/css/template.css?v=5'>
<link rel='stylesheet' type='text/css' href='/css/global.css?v=2'>
<!--[if lt IE 7.00]>
<link rel='stylesheet' type='text/css' href='/css/template.ie.css?v=1'>
<link rel='stylesheet' type='text/css' href='/css/global.ie.css?v=1'>
<![endif]-->
</head>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<body>
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript"> _uacct = "UA-1272972-1"; urchinTracker();</script>
<div id='top'>
    <a href='/'><span id='logo'>&nbsp;</span></a>
    <div id='layout_head'>
       <div id='login_info'>
           2,043 citizens online now&nbsp;|&nbsp; <a href='/town_hall/faq.phtml'>HELP</a>
       </div> <!--login_info-->
       <div id='stripe'>
           <script type='text/javascript'>flash_object ('http://graphics.millsberry.com/template/top_nav.swf', '747', '36', '&url=http%3A%2F%2Fmillsberry.com%2Ftop_nav_xml.phtml&unixTimeStamp=1193059672&serverTimeOffset=28800', '7', 'noscale', 'transparent');</script> 
       </div> <!-- stripe -->
    </div> <!-- layout_head -->
</div> <!-- top -->
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='body'>
<div id='layout_body'>
<div id='side_nav'>
<script type='text/javascript'>flash_object ('http://graphics.millsberry.com/template/side_nav.swf', '150', '1250', '&url=http%3A%2F%2Fmillsberry.com%2Fside_nav_xml.phtml%3Fpage_relative_url%3D%252Fcotw.phtml%253Fuser%253Dabefroman%26login_status%3D0%26now%3D1193059672&unixTimeStamp=1193059672&serverTimeOffset=28800', '7', 'noscale', 'transparent');</script></div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='main'>
<div id='gazette_banner'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/item_loader_v5.swf', '580', '75', 'itemLoaderXML=%3C%3Fxml%20version%3D%271.0%27%3F%3E%3Cmessage%20success%3D%271%27%20text%3D%27%27%3E%3Citem%3E%3Cframe%3E1%3C%2Fframe%3E%3CobjectName%3Eitem%3C%2FobjectName%3E%3Curl%3Ehttp%253A%252F%252Fgraphics.millsberry.com%252Fsite_gfx%252Fgazette_banner.swf%3C%2Furl%3E%3C%2Fitem%3E%3Cpreloader%3E%3CobjectName%3Epreloader%3C%2FobjectName%3E%3Cwidth%3E580%3C%2Fwidth%3E%3Cheight%3E75%3C%2Fheight%3E%3C%2Fpreloader%3E%3C%2Fmessage%3E&unixTimeStamp=1193059672&serverTimeOffset=28800', '7', 'noscale', 'transparent');</script></div><div id='content'>
<span style='float: right; width: 280px; height: 187px; margin: 0 0 5px 5px; border: 1px solid black;'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/buddy/buddy_featured.swf', '280', '187', 'userName=abefroman&buddyTimeStamp=20040802&buddyScriptURL=http%3A%2F%2Fmillsberry.com%2Fbuddy%2Fload_buddy_xml.phtml&unixTimeStamp=1193059672&serverTimeOffset=28800', '', 'exactfit', 'transparent');</script></span>
Meet <b>TheHumongous</b>! <br><br>TheHumongous got his nickname from his friends - named after his HUMONGOUS appetite and his HUMONGOUS comic book collection. He loves pies, stews, soups, hamburgers, hot dogs and just about anything else he can get his hands on. If you ever see him, you'll always see him eating something! <br><br>He's also got a ton of comic books. He heads down to the comic book store every Wednesday, picking up all the new titles. He collects a little bit of everything: super hero comics, horror comics, funny comics. As long as it's a comic book, he reads it. <br><br>He also loves science fiction and spends a lot of his time at his art desk. He wants to become a comic book artist one day, so he spends all his free time practicing. <br><br>So, if you've got some time, be sure to drop by and visit TheHumongous! You never know what he might be up to these days.</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='footer'>
MILLSBERRY &reg;, characters, logos, product names and all related indicia are trademarks of Mills Online, Inc., &copy; 2004-2006.<BR> &reg; denotes Reg. US Pat. & TM Office. All rights reserved.<br>
Use of this site signifies your acceptance of the <a href='/town_hall/terms.phtml'><b>Terms and Conditions</b></a>.
Please view our <a href='/town_hall/terms.phtml'><b>Privacy Policy</b></a>.
</div>
</div>
<div id='bottom'>&nbsp;</div>
</div>
</body>
</html>
