<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- chinpweb09.millsberry.com -->
<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
<meta http-equiv='imagetoolbar' content='no'>
<meta name='keywords' content="Mills,Millsbury,Milsberry,Milsbury,Millberry,Millbury,Fun games,Spanish language games,Educational games,Active games,Citizen,Cool stuff,Arcade,Music Mix,Fun,Games,Explore,Adventure,Create,Character,Buddy,Care,Academy,School,Gym,Gymnasium,Solver,Science,Project,Town,Pets,Children's games,Games for kid,Kid games,Kids games,Kid's games,Children,Safe gaming">
<title>Millsberry - Americas Second Harvest</title>
<link rel='stylesheet' type='text/css' href='/css/theme/royal.css'>
<link rel='stylesheet' type='text/css' href='/css/template.css'>
<!--[if lt IE 7.00]>
<link rel='stylesheet' type='text/css' href='/css/ie.css'>
<![endif]-->
<script type='text/javascript' src='/hidden.js'></script>
<script type='text/javascript'>
<!--
// Allows users to assign names to their shortcuts
function addShortcut (to_url, default_title) {
	assign_title = default_title;
	var user_title = prompt ("What name do you want to give this shortcut?\nLeave this blank to use the page's existing title.","");
	if (user_title.length > 0) {
		assign_title = base64_encode (utf8_encode (user_title));
	}
	window.location='/process_shortcut.phtml?action=add&url=' + to_url + '&name=' + assign_title;
}
-->
</script>
<link rel='shortcut icon' href='/favicon.ico'>
</head>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<body >

<div id='top'>
<a href='/index.phtml'><span id='logo'>&nbsp;</span></a>
<div id='layout_head'>
	<div id='login_info'><form name='login' method='post' action='/communitycenter/second_harvest.phtml'>
Username <input type='text' name='login_username' size='10'>&nbsp;&nbsp;
Password <input type='password' name='login_pass' size='10'>
<input type='submit' value='Go'>
</form></div>
	<div id='stripe'>
		<div id='stripe_shortcuts'>
			<table width='95' border='0' cellpadding='0' cellspacing='0'><tr>
				<td width='72'></td>
				<td width='23' valign='bottom'></td>
			</tr></table>
		</div>
		<div id='stripe_search'>
			<form name='search' action='/site_search.phtml' method='get'>
			<table width='340' border='0' cellpadding='0' cellspacing='0'><tr>
				<td width='135' align='right'>Address Book&nbsp;</td>
				<td width='105' align='left' valign='middle'><input type='text' name='search' size='15'></td>
				<td width='30' align='center' valign='bottom'><a href='javascript: document.search.submit();' class='stripe_button'><span id='search_button'>&nbsp;</span></a></td>
				<td width='60' align='right'><a href='/town_hall/faq.phtml'>Help</a></td>
			</tr></table>
			</form>
		</div>
	</div>
</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='body'>
<div id='layout_body'>
<div id='side_nav'>

<!-- Exclude these from the stylesheet so they can be translated -->
<style type='text/css'>
#body #layout_body #side_nav .nav_button_hover #nav_signup {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_signup_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_start {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_start_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_the_city {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_the_city_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_downtown {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_downtown_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_arcade {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_arcade_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_my_stuff {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_my_stuff_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_my_home {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_my_crib_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_customize {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_customize_1.png') no-repeat;
}
</style>
<!--[if lt IE 7.00]>
<style type='text/css'>
#body #layout_body #side_nav .nav_button_hover #nav_signup {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_signup_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_start {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_start_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_the_city {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_the_city_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_downtown {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_downtown_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_arcade {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_arcade_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_my_stuff {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_my_stuff_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_my_home {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_my_crib_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_customize {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_customize_1.png');
}
</style>
<![endif]-->

<a href='/signup.phtml' class='nav_button_hover'><span id='nav_signup' class='nav_button'>&nbsp;</span></a>
<a href='/main_map.phtml' class='nav_button_hover'><span id='nav_the_city' class='nav_button'>&nbsp;</span></a>
<a href='/main_map.phtml?location=downtown' class='nav_button_hover'><span id='nav_downtown' class='nav_button'>&nbsp;</span></a>
<a href='/complex/arcade.phtml' class='nav_button_hover'><span id='nav_arcade' class='nav_button'>&nbsp;</span></a>
<br><img src='http://graphics.millsberry.com/site_gfx/prebuddy.gif' border='1'>
<table width='100%' border='0' cellpadding='5' cellspacing='0' id='side_nav_options'>
<tr>
	<td align='right'>Language</td>
	<td>
		<form name='language_form' method='post' action='/communitycenter/second_harvest.phtml'>
		<select name='lang' onChange='document.language_form.submit();' style='width: 75px;'>
			<option value='en' selected>English</option>
			<option value='es' >Espa&ntilde;ol</option>
		</select>
		</form>
	</td>
</tr>

</table>

</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='main'>
<div id='content'>
  <TABLE ALIGN='CENTER' BORDER='0' WIDTH='550' HEIGHT='300' CELLPADDING='0' CELLSPACING='0'>
    <TR>
      <TD NOWRAP WIDTH='100%' HEIGHT='300' ALIGN='CENTER' BACKGROUND='http://graphics.millsberry.com/site_gfx/sponsors_art/counter_bg.gif'>
        <TABLE BORDER='0' CELLPADDING='0' CELLSPACING='0' WIDTH='100%' HEIGHT='100%'>
          <TR>
            <TD COLSPAN='3' HEIGHT='145'>&nbsp;</TD>
          </TR>
          <TR>
            <TD WIDTH='180'></TD>
            <TD ALIGN='CENTER'>
              <IMG SRC='http://graphics.millsberry.com/site_gfx/sponsors_art/number_2.gif'><IMG SRC='http://graphics.millsberry.com/site_gfx/sponsors_art/number_5.gif'><IMG SRC='http://graphics.millsberry.com/site_gfx/sponsors_art/number_3.gif'><IMG SRC='http://graphics.millsberry.com/site_gfx/sponsors_art/number_comma.gif'><IMG SRC='http://graphics.millsberry.com/site_gfx/sponsors_art/number_6.gif'><IMG SRC='http://graphics.millsberry.com/site_gfx/sponsors_art/number_2.gif'><IMG SRC='http://graphics.millsberry.com/site_gfx/sponsors_art/number_9.gif'>            </TD>
            <TD WIDTH='180'></TD>
          </TR>
        </TABLE>
      </TD>
    </TR>
  </TABLE>
<br>
"Thank you, Millsberry Citizens! You did it, and you made a positive difference," said Mayor Trumble at a press conference about the Millsberry Food Drive, which ended this week.<br><br>The Food Drive has been declared a complete success. Working in partnership with America's Second Harvest&nbsp;The Nation's Food Bank Network and General Mills, Inc., the citizens of Millsberry, have contributed over 250,000 meals to fight against hunger!<br><br>"Through your generous donations, you've helped make sure that kids just like you don't have to go to bed hungry," said Mayor Trumble. "By displaying your trophies and donating food, you've helped raise awareness of this issue and proven that something can be done about it."<br><br>Many Millsberry residents agreed that, because of the food drive, they have become better informed about the widespread problem of hunger across America, and that they will continue working toward the goal of a hunger-free America.
         

</div>
<DIV ALIGN='CENTER'>
<P><FONT SIZE='+2'><U><B>Learn More:</B></U></FONT></P>

<A HREF='JavaScript: openWin("second_harvest_facts.phtml?fid=3",  600, 400, true);'><IMG SRC='http://graphics.millsberry.com/site_gfx/button_book_kidshelp.gif' BORDER='0'></A><A HREF='JavaScript: openWin("second_harvest_facts.phtml?fid=1",  600, 400, true);'><IMG SRC='http://graphics.millsberry.com/site_gfx/button_book_hunger.gif' BORDER='0'></A><A HREF='JavaScript: openWin("second_harvest_facts.phtml?fid=2",  600, 400, true);'><IMG SRC='http://graphics.millsberry.com/site_gfx/button_book_foodflow.gif' BORDER='0'></A></DIV>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='footer'>
MILLSBERRY, characters, logos, product names and all related indicia are trademarks of Mills Online, Inc., &copy; 2004-2006.<BR> &reg; denotes Reg. US Pat. & TM Office. All rights reserved.<br>Use of this site signifies your acceptance of the <a href='/town_hall/terms.phtml'><b>Terms and Conditions</b></a>.<br>Please view our <a href='/town_hall/terms.phtml'><b>Privacy Policy</b></a>
</div>
</div>
<div id='bottom'>&nbsp;</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='debug'>
</div>
</body>
</html>
