_level0.IDS_loadingthedictionary = "Loading Game Dictionary: ";
_root.IDS_playgame = "<p align=\'center\'><font color=\'#ffffff\' size = \'18\'>Play Game</font></p>";
_root.IDS_view_instructions = "<p align=\'center\'><font color=\'#ffffff\' size = \'18\'>View Instructions</font></p>";
_root.IDS_back_txt = "<p align=\'center\'><font color=\'#ffffff\' size = \'18\'>Back</font></p>";
_root.IDS_RESTART_TXT = "<p align=\'center\'><font color=\'#ffffff\' size = \'18\'>Restart Game</font></p>";
_root.IDS_SENDSCORE_TXT = "<p align=\'center\'><font color=\'#ffffff\' size = \'18\'>Send Score</font></p>";
_root.IDS_INSTRUCTIONS_TXT = "<P ALIGN=\'CENTER\'><FONT SIZE=\'18\'  COLOR=\'#fFFFFFF\' >Game Instructions</FONT></P><P ALIGN=\'LEFT\'><FONT SIZE=\'16\' COLOR=\'#fFFFFFF\' >     Do you love to solve mysteries and crack secret codes? In this game, word clues are coded and you must help decode them. Each six-letter code has been scrambled. Discover as many words as possible that can be made from those letters within a two minute time limit (getting the original six-letter word will give you the highest points!) You can select a letter by either clicking it with your mouse, or by entering the letter with your keyboard. Use the Space Bar to re-scramble the letters, Tab to clear the answer, Backspace to clear the last letter, and Enter to submit your answer. Failing to solve enough words in a given round will end gameplay. In each round, \'Points Required\' indicates the number of points you need to advance.</FONT></P>";
_root.IDS_MINI_INSTRUCTIONS = "<P ALIGN=\'CENTER\'><FONT SIZE=\'16\'  COLOR=\'#000000\' >Instructions</FONT></P><P ALIGN=\'LEFT\'><FONT SIZE=\'14\'  COLOR=\'#000000\' >Mouse - Click the letter to select it. To submit a word, press the \'Enter Word\' button.<BR><BR>Keyboard - Type the letter with your keyboard. To submit a word, press the ENTER key.</FONT></P>";
_root.IDS_TIPONE_TXT = "You Can Enter Words With The Keyboard , Too!";
_root.IDS_TIPTWO_TXT = "Use The Enter Key To Enter A Word.";
_root.IDS_TIPTHREE_TXT = "Pressing The Spacebar Scrambles The Letters. ";
_root.IDS_TIPFOUR_TXT = "Use The Backspace Key To Clear A Letter.";
_root.IDS_ROUND_HDR_TXT = "ROUND ";
_root.IDS_START_HDR_TXT = " START!";
_root.IDS_GET_HDR_TXT = "GET ";
_root.IDS_PTS_HDR_TXT = " Points In 2 Minutes To Advance";
_root.IDS_TIP_HDR_TXT = "*TIP: ";
_root.IDS_CLEAR_HDR_TXT = " CLEAR!";
_root.IDS_NXT_ROUND_TXT = "<U>Begin Next Round</U>";
_root.IDS_GOTALL_TXT = "Congratulations! You Got Them All!.";
_root.IDS_UNANSWERED_TXT = "Any Unanswered Codes Are Revealed Below";
_root.IDS_REVEALED_TXT = "You Revealed ";
_root.IDS_OUTOF_TXT = " Out Of ";
_root.IDS_ENDREVEAL_TXT = " Codes.\nThe Codes Will Not Be Revealed For This Clue.";
_root.IDS_NOT_REVEALED_TXT = "The Clues Will Not Be Revealed For This Code.";
_root.IDS_GAMEOVER_TXT = "GAME OVER";
_root.IDS_NOTENOUGH_TXT = "You Didn\'t Decode Enough Clues To Advance. ";
_root.IDS_YOUNEEDED_TXT = "You Needed ";
_root.IDS_POINTS_TXT = "More Points";
_root.IDS_CLICKENDGAME_TXT = "Please Click \'End Game\' To\nSend Your Score Or Restart The Game.";
_root.IDS_GREATJOB_TXT = "GREAT JOB!";
_root.IDS_ISCODE_TXT = " Is One Of The Codes !";
_root.IDS_SORRY_TXT = "SORRY!";
_root.IDS_ALREADYANSWERED_TXT = " Has Already Been Answered";
_root.IDS_NOTWORD_TXT = " Is Not In Our Dictionary";
_root.IDS_ENTER_BTN_TXT = "<P ALIGN=\'CENTER\'><FONT SIZE=\'15\' COLOR=\'#000000\'>ENTER WORD</FONT></P>";
_root.IDS_SCRAMBLE_BTN_TXT = "<P ALIGN=\'CENTER\'><FONT SIZE=\'13\' COLOR=\'#000000\'>SCRAMBLE LETTERS</FONT></P>";
_root.IDS_CANCEL_BTN_TXT = "<P ALIGN=\'CENTER\'><FONT SIZE=\'13\' COLOR=\'#000000\'>CANCEL</FONT></P>";
_root.IDS_ENDGAME_BTN_TXT = "<P ALIGN=\'CENTER\'><FONT SIZE=\'13\' COLOR=\'#000000\'>END GAME</FONT></P>";
_root.IDS_NEXTLEVEL_BTN_TXT = "<P ALIGN=\'CENTER\'><FONT SIZE=\'13\' COLOR=\'#000000\'>NEXT LEVEL</FONT></P>";
_root.IDS_ROUND_SB_TXT = "ROUND: ";
_root.IDS_SCORE_SB_TXT = "SCORE: ";
_root.IDS_REQ_SB_TXT = "POINTS REQUIRED: ";
_root.IDS_TIME_SB_TXT = "TIME: ";
_root.IDS_YOU_REACHED_LEVEL_TXT = "You Reached Level ";
_root.IDS_YOURSCORE_TXT = "Your Score";
_root.IDS_BAD_MSG = "You need more practice. Keep Trying!";
_root.IDS_GOOD_MSG = "Good Job!\'";
_root.IDS_BETTER_MSG = "Great Job!";
