<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- chinpweb07.millsberry.com -->
<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
<meta http-equiv='imagetoolbar' content='no'>
<meta name='keywords' content="Mills,Millsbury,Milsberry,Milsbury,Millberry,Millbury,Fun games,Spanish language games,Educational games,Active games,Citizen,Cool stuff,Arcade,Music Mix,Fun,Games,Explore,Adventure,Create,Character,Buddy,Care,Academy,School,Gym,Gymnasium,Solver,Science,Project,Town,Pets,Children's games,Games for kid,Kid games,Kids games,Kid's games,Children,Safe gaming">
<title>Millsberry - Arcade</title>
<link rel='stylesheet' type='text/css' href='/css/theme/royal.css'>
<link rel='stylesheet' type='text/css' href='/css/template.css'>
<!--[if IE]>
<link rel='stylesheet' type='text/css' href='/css/ie.css'>
<![endif]-->
<script type='text/javascript' src='/hidden.js'></script>
<script type='text/javascript'>
<!--
// Allows users to assign names to their shortcuts
function addShortcut (to_url, default_title) {
	assign_title = default_title;
	var user_title = prompt ("What name do you want to give this shortcut?\nLeave this blank to use the page's existing title.","");
	if (user_title.length > 0) {
		assign_title = base64_encode (utf8_encode (user_title));
	}
	window.location='/process_shortcut.phtml?action=add&url=' + to_url + '&name=' + assign_title;
}
-->
</script>
<link rel='shortcut icon' href='/favicon.ico'>
</head>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<body >

<div id='top'>
<a href='/index.phtml'><span id='logo'>&nbsp;</span></a>
<div id='layout_head'>
	<div id='login_info'><form name='login' method='post' action='/complex/arcade.phtml?logout=1'>
Username <input type='text' name='login_username' size='10'>&nbsp;&nbsp;
Password <input type='password' name='login_pass' size='10'>
<input type='submit' value='Go'>
</form></div>
	<div id='stripe'>
		<div id='stripe_shortcuts'>
			<table width='95' border='0' cellpadding='0' cellspacing='0'><tr>
				<td width='72'></td>
				<td width='23' valign='bottom'></td>
			</tr></table>
		</div>
		<div id='stripe_search'>
			<form name='search' action='/site_search.phtml' method='get'>
			<table width='340' border='0' cellpadding='0' cellspacing='0'><tr>
				<td width='135' align='right'>Address Book&nbsp;</td>
				<td width='105' align='left' valign='middle'><input type='text' name='search' size='15'></td>
				<td width='30' align='center' valign='bottom'><a href='javascript: document.search.submit();' class='stripe_button'><div id='search_button'></div></a></td>
				<td width='60' align='right'><a href='/town_hall/faq.phtml'>Help</a></td>
			</tr></table>
			</form>
		</div>
	</div>
</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='body'>
<div id='layout_body'>
<div id='side_nav'>

<!-- Exclude these from the stylesheet so they can be translated -->
<style type='text/css'>
#body #layout_body #side_nav .nav_button_hover #nav_signup {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_signup_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_start {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_start_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_the_city {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_the_city_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_downtown {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_downtown_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_arcade {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_arcade_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_my_stuff {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_my_stuff_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_my_home {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_my_home_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_customize {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_customize_1.png') no-repeat;
}
</style>
<!--[if lt IE 7.00]>
<style type='text/css'>
#body #layout_body #side_nav .nav_button_hover #nav_signup {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_signup_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_start {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_start_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_the_city {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_the_city_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_downtown {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_downtown_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_arcade {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_arcade_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_my_stuff {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_my_stuff_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_my_home {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_my_home_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_customize {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_customize_1.png');
}
</style>
<![endif]-->

<a href='/signup.phtml' class='nav_button_hover'><span id='nav_signup' class='nav_button'>&nbsp;</span></a>
<a href='/main_map.phtml' class='nav_button_hover'><span id='nav_the_city' class='nav_button'>&nbsp;</span></a>
<a href='/main_map.phtml?location=downtown' class='nav_button_hover'><span id='nav_downtown' class='nav_button'>&nbsp;</span></a>
<a href='/complex/arcade.phtml' class='nav_button_hover'><span id='nav_arcade' class='nav_button'>&nbsp;</span></a>
<br><img src='http://graphics.millsberry.com/site_gfx/prebuddy.gif' border='1'>
<table width='100%' border='0' cellpadding='5' cellspacing='0' id='side_nav_options'>
<tr>
	<td align='right'>Language</td>
	<td>
		<form name='language_form' method='post' action='/complex/arcade.phtml?logout=1'>
		<select name='lang' onChange='document.language_form.submit();' style='width: 75px;'>
			<option value='en' selected>English</option>
			<option value='es' >Espa&ntilde;ol</option>
		</select>
		</form>
	</td>
</tr>

</table>

</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='main'>

<div id='interior'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/site_gfx/interiors/int_arcade_v3.swf', 600, 400, 'unixTimeStamp=1144723325', 6);</script></div>
<div id='interior_stripe'>Millsberry Arcade</div>
<div id='content'>
	<!--Don't show up without some change!-->
	<b>Find more cool games and activities at <a href="../refer.phtml?r_id=27" target="_new" style="color:red">VerbNow</a>!</b>
	<br><br>
<!--
<div align='center' style='width: 80%; background: white; padding: 5px;'>
	<b>A quick message from the Ubah Brothers:</b><br><br>
	Hey everyone! We just wanted to let you know that the Lucky Charms&#174; Charmed Life game is getting some maintenance at the moment and will be making its return just as soon as we get the machine back into tip-top shape. In the meantime, we hope you enjoy all of the other fun and challenging games we have to offer.
</div>
-->
	
<table width='80%' align='center' border='0' cellpadding='5' cellspacing='0'>
<!--<tr><td colspan='4' align='center'></td></tr>-->
<tr>
	<td width='25%' align='center'>
		<a href='/complex/arcade.phtml?show=fit'><img src='http://graphics.millsberry.com/site_gfx/stat_fit_v1.gif' border='0'><br>Fitness</a>
	</td>
	<td width='25%' align='center'>
		<a href='/complex/arcade.phtml?show=civ'><img src='http://graphics.millsberry.com/site_gfx/stat_civ_v1.gif' border='0'><br>Civics</a>
	</td>
	<td width='25%' align='center'>
		<a href='/complex/arcade.phtml?show=int'><img src='http://graphics.millsberry.com/site_gfx/stat_int_v1.gif' border='0'><br>Intelligence</a>
	</td>
	<td width='25%' align='center'>
		<a href='/complex/arcade.phtml?show=item'><img src='http://graphics.millsberry.com/site_gfx/stat_gift_v1.gif' border='0'><br>Reward</a>
	</td>
</tr></table>
<hr noshade size='1'>
	
<table border='0' cellpadding='2' cellspacing='0' width='100%'>
<tr><td width='155' align='center'><a href='/gamepages/flashgame_ctp.phtml?game_id=380'><img src='http://graphics.millsberry.com/game_interiors/thumbnails/interior_380.gif' width='150' height='100' border='1'><br>Sudoku</a></td>
<td><b>Description:</b><br>Arrange  marshmallows on grids of various dimensions so that there is only one instance of each marshmallow in each row, column, and cell.<br>
<img src='http://graphics.millsberry.com/site_gfx/stat_int_v1.gif' width='25' height='20' border='0'></td>
<td align='center' width='60'><a href='/gamepages/hiscores.phtml?game_id=380'>View<br>Hi Scores</a></td></tr>
<tr><td colspan='3' height='6'><font style='font-size: 1px; line-height: 1px;'>&nbsp;</font></td></tr>
<tr><td width='155' align='center'><a href='/gamepages/flashgame_ctp.phtml?game_id=360'><img src='http://graphics.millsberry.com/game_interiors/thumbnails/interior_360.gif' width='150' height='100' border='1'><br>Slap Shot Shootout</a></td>
<td><b>Description:</b><br>Shoot the puck into the goal to score a goal. Score at least 5 goals per period to advance to the next level. Each period is 60 seconds long.<br>
<img src='http://graphics.millsberry.com/site_gfx/stat_fit_v1.gif' width='25' height='20' border='0'></td>
<td align='center' width='60'><a href='/gamepages/hiscores.phtml?game_id=360'>View<br>Hi Scores</a></td></tr>
<tr><td colspan='3' height='6'><font style='font-size: 1px; line-height: 1px;'>&nbsp;</font></td></tr>
<tr><td width='155' align='center'><a href='/gamepages/flashgame_ctp.phtml?game_id=340'><img src='http://graphics.millsberry.com/game_interiors/thumbnails/interior_340.gif' width='150' height='100' border='1'><br>Wave Blaster</a></td>
<td><b>Description:</b><br>Collect powerups to increase your blast power, to restore your shield and to increase your speed. Avoid or blast challengers. Getting rid of all challengers in a group rewards bonus points.<br>
<img src='http://graphics.millsberry.com/site_gfx/stat_gift_v1.gif' width='25' height='20' border='0'></td>
<td align='center' width='60'><a href='/gamepages/hiscores.phtml?game_id=340'>View<br>Hi Scores</a></td></tr>
<tr><td colspan='3' height='6'><font style='font-size: 1px; line-height: 1px;'>&nbsp;</font></td></tr>
<tr><td width='155' align='center'><a href='/gamepages/flashgame_ctp.phtml?game_id=320'><img src='http://graphics.millsberry.com/game_interiors/thumbnails/interior_320.gif' width='150' height='100' border='1'><br>Archery Challenge</a></td>
<td><b>Description:</b><br>Shoot the balloons before they hit the trees at the top of the screen!<br>
<img src='http://graphics.millsberry.com/site_gfx/stat_fit_v1.gif' width='25' height='20' border='0'></td>
<td align='center' width='60'><a href='/gamepages/hiscores.phtml?game_id=320'>View<br>Hi Scores</a></td></tr>
<tr><td colspan='3' height='6'><font style='font-size: 1px; line-height: 1px;'>&nbsp;</font></td></tr>
<tr><td width='155' align='center'><a href='/gamepages/flashgame_ctp.phtml?game_id=300'><img src='http://graphics.millsberry.com/game_interiors/thumbnails/interior_300.gif' width='150' height='100' border='1'><br>Lucky Charms&reg; Charmed Life</a></td>
<td><b>Description:</b><br>Collect all of the bowls of Lucky Charms and use magical charms to exit the forest maze without getting caught by the kids!<br>
<img src='http://graphics.millsberry.com/site_gfx/stat_int_v1.gif' width='25' height='20' border='0'></td>
<td align='center' width='60'><a href='/gamepages/hiscores.phtml?game_id=300'>View<br>Hi Scores</a></td></tr>
<tr><td colspan='3' height='6'><font style='font-size: 1px; line-height: 1px;'>&nbsp;</font></td></tr>
<tr><td width='155' align='center'><a href='/gamepages/flashgame_ctp.phtml?game_id=260'><img src='http://graphics.millsberry.com/game_interiors/thumbnails/interior_260.gif' width='150' height='100' border='1'><br>Reese's&reg; Puffs&reg; Cereal Snowboard Slalom</a></td>
<td><b>Description:</b><br>Snowboard down the course in under a minute. Along the way, be sure to go through the slalom flags while avoiding trees and rocks. Jump off ramps to do tricks that will earn you extra points!<br>
<img src='http://graphics.millsberry.com/site_gfx/stat_fit_v1.gif' width='25' height='20' border='0'></td>
<td align='center' width='60'><a href='/gamepages/hiscores.phtml?game_id=260'>View<br>Hi Scores</a></td></tr>
<tr><td colspan='3' height='6'><font style='font-size: 1px; line-height: 1px;'>&nbsp;</font></td></tr>
<tr><td width='155' align='center'><a href='/gamepages/flashgame_ctp.phtml?game_id=240'><img src='http://graphics.millsberry.com/game_interiors/thumbnails/interior_240.gif' width='150' height='100' border='1'><br>Millsberry Hide & Seek</a></td>
<td><b>Description:</b><br>Flip over the cards two at a time, and try to find a match.<br />
Remember, you are playing against the clock; if time runs out, it's game over!<br>
<img src='http://graphics.millsberry.com/site_gfx/stat_int_v1.gif' width='25' height='20' border='0'></td>
<td align='center' width='60'><a href='/gamepages/hiscores.phtml?game_id=240'>View<br>Hi Scores</a></td></tr>
<tr><td colspan='3' height='6'><font style='font-size: 1px; line-height: 1px;'>&nbsp;</font></td></tr>
<tr><td width='155' align='center'><a href='/gamepages/flashgame_ctp.phtml?game_id=180'><img src='http://graphics.millsberry.com/game_interiors/thumbnails/interior_180.gif' width='150' height='100' border='1'><br>Galactic Defender Adventure</a></td>
<td><b>Description:</b><br>Defend planets from the bouncing asteroids!<br>
<img src='http://graphics.millsberry.com/site_gfx/stat_civ_v1.gif' width='25' height='20' border='0'></td>
<td align='center' width='60'><a href='/gamepages/hiscores.phtml?game_id=180'>View<br>Hi Scores</a></td></tr>
<tr><td colspan='3' height='6'><font style='font-size: 1px; line-height: 1px;'>&nbsp;</font></td></tr>
<tr><td width='155' align='center'><a href='/gamepages/flashgame_ctp.phtml?game_id=160'><img src='http://graphics.millsberry.com/game_interiors/thumbnails/interior_160.gif' width='150' height='100' border='1'><br>Sherman Home Run Derby</a></td>
<td><b>Description:</b><br>It's Home Run Derby time!<br>
<img src='http://graphics.millsberry.com/site_gfx/stat_fit_v1.gif' width='25' height='20' border='0'></td>
<td align='center' width='60'><a href='/gamepages/hiscores.phtml?game_id=160'>View<br>Hi Scores</a></td></tr>
<tr><td colspan='3' height='6'><font style='font-size: 1px; line-height: 1px;'>&nbsp;</font></td></tr>
<tr><td width='155' align='center'><a href='/gamepages/flashgame_ctp.phtml?game_id=140'><img src='http://graphics.millsberry.com/game_interiors/thumbnails/interior_140.gif' width='150' height='100' border='1'><br>Sink The Three!</a></td>
<td><b>Description:</b><br>Swish the ball through the hoop and earn Millsbucks!<br>
<img src='http://graphics.millsberry.com/site_gfx/stat_fit_v1.gif' width='25' height='20' border='0'></td>
<td align='center' width='60'><a href='/gamepages/hiscores.phtml?game_id=140'>View<br>Hi Scores</a></td></tr>
<tr><td colspan='3' height='6'><font style='font-size: 1px; line-height: 1px;'>&nbsp;</font></td></tr>
<tr><td width='155' align='center'><a href='/gamepages/flashgame_ctp.phtml?game_id=100'><img src='http://graphics.millsberry.com/game_interiors/thumbnails/interior_100.gif' width='150' height='100' border='1'><br>Rope Race</a></td>
<td><b>Description:</b><br>Get climbing!<br>
<img src='http://graphics.millsberry.com/site_gfx/stat_fit_v1.gif' width='25' height='20' border='0'></td>
<td align='center' width='60'><a href='/gamepages/hiscores.phtml?game_id=100'>View<br>Hi Scores</a></td></tr>
<tr><td colspan='3' height='6'><font style='font-size: 1px; line-height: 1px;'>&nbsp;</font></td></tr>
<tr><td width='155' align='center'><a href='/gamepages/flashgame_ctp.phtml?game_id=80'><img src='http://graphics.millsberry.com/game_interiors/thumbnails/interior_80.gif' width='150' height='100' border='1'><br>Countdown!</a></td>
<td><b>Description:</b><br>Rocket your way into the mathosphere with Countdown!, a great new game that combines<br />
solving math problems with fast-paced, intergalactic excitement.<br>
<img src='http://graphics.millsberry.com/site_gfx/stat_int_v1.gif' width='25' height='20' border='0'></td>
<td align='center' width='60'><a href='/gamepages/hiscores.phtml?game_id=80'>View<br>Hi Scores</a></td></tr>
<tr><td colspan='3' height='6'><font style='font-size: 1px; line-height: 1px;'>&nbsp;</font></td></tr>
<tr><td width='155' align='center'><a href='/gamepages/flashgame_ctp.phtml?game_id=60'><img src='http://graphics.millsberry.com/game_interiors/thumbnails/interior_60.gif' width='150' height='100' border='1'><br>Peabody Park Half-Pipe Competition</a></td>
<td><b>Description:</b><br>Peabody Park Half-Pipe Competition!<br>
<img src='http://graphics.millsberry.com/site_gfx/stat_fit_v1.gif' width='25' height='20' border='0'></td>
<td align='center' width='60'><a href='/gamepages/hiscores.phtml?game_id=60'>View<br>Hi Scores</a></td></tr>
<tr><td colspan='3' height='6'><font style='font-size: 1px; line-height: 1px;'>&nbsp;</font></td></tr>
<tr><td width='155' align='center'><a href='/peabody_park/pond/'><img src='http://graphics.millsberry.com/game_interiors/thumbnails/interior_40.gif' width='150' height='100' border='1'><br>Peabody Park Fishing</a></td>
<td><b>Description:</b><br>Grab your fishing poles!<br>
<img src='http://graphics.millsberry.com/site_gfx/stat_gift_v1.gif' width='25' height='20' border='0'></td>
<td align='center' width='60'><a href='/gamepages/hiscores.phtml?game_id=40'>View<br>Hi Scores</a></td></tr>
<tr><td colspan='3' height='6'><font style='font-size: 1px; line-height: 1px;'>&nbsp;</font></td></tr>
<tr><td width='155' align='center'><a href='/gamepages/flashgame_ctp.phtml?game_id=19'><img src='http://graphics.millsberry.com/game_interiors/thumbnails/interior_19.gif' width='150' height='100' border='1'><br>Peabody Park Cleanup</a></td>
<td><b>Description:</b><br>The Peabody Park Rangers are cleaning up the park, but squirrels keep getting in the way! Can you help them get all the trash to the recycle bins before the squirrels do the same to you?<br>
<img src='http://graphics.millsberry.com/site_gfx/stat_civ_v1.gif' width='25' height='20' border='0'></td>
<td align='center' width='60'><a href='/gamepages/hiscores.phtml?game_id=19'>View<br>Hi Scores</a></td></tr>
<tr><td colspan='3' height='6'><font style='font-size: 1px; line-height: 1px;'>&nbsp;</font></td></tr>
<tr><td width='155' align='center'><a href='/gamepages/flashgame_ctp.phtml?game_id=18'><img src='http://graphics.millsberry.com/game_interiors/thumbnails/interior_18.gif' width='150' height='100' border='1'><br>Peanut Butter Toast Crunch Swirl</a></td>
<td><b>Description:</b><br>Some games require more skill than luck. This game isn't one of them! Drop Peanut Butter Toast Crunch pieces and win points!<br>
<img src='http://graphics.millsberry.com/site_gfx/stat_gift_v1.gif' width='25' height='20' border='0'></td>
<td align='center' width='60'><a href='/gamepages/hiscores.phtml?game_id=18'>View<br>Hi Scores</a></td></tr>
<tr><td colspan='3' height='6'><font style='font-size: 1px; line-height: 1px;'>&nbsp;</font></td></tr>
<tr><td width='155' align='center'><a href='/gamepages/flashgame_ctp.phtml?game_id=16'><img src='http://graphics.millsberry.com/game_interiors/thumbnails/interior_16.gif' width='150' height='100' border='1'><br>Millsberry's Match Wanted</a></td>
<td><b>Description:</b><br>A gang of robbers has snuck into the Millberry Mercantile Bank, and you have to catch them before they've stolen every citizen's Millsbucks.<br>
<img src='http://graphics.millsberry.com/site_gfx/stat_civ_v1.gif' width='25' height='20' border='0'></td>
<td align='center' width='60'><a href='/gamepages/hiscores.phtml?game_id=16'>View<br>Hi Scores</a></td></tr>
<tr><td colspan='3' height='6'><font style='font-size: 1px; line-height: 1px;'>&nbsp;</font></td></tr>
<tr><td width='155' align='center'><a href='/gamepages/flashgame_ctp.phtml?game_id=13'><img src='http://graphics.millsberry.com/game_interiors/thumbnails/interior_13.gif' width='150' height='100' border='1'><br>Hop-N-Drop</a></td>
<td><b>Description:</b><br>If you don't have a trampoline in your back yard, try using gym cushions instead! Remove all of the gym cushions by jumping on them.<br>
<img src='http://graphics.millsberry.com/site_gfx/stat_fit_v1.gif' width='25' height='20' border='0'></td>
<td align='center' width='60'><a href='/gamepages/hiscores.phtml?game_id=13'>View<br>Hi Scores</a></td></tr>
<tr><td colspan='3' height='6'><font style='font-size: 1px; line-height: 1px;'>&nbsp;</font></td></tr>
<tr><td width='155' align='center'><a href='/gamepages/flashgame_ctp.phtml?game_id=12'><img src='http://graphics.millsberry.com/game_interiors/thumbnails/interior_12.gif' width='150' height='100' border='1'><br>Solver</a></td>
<td><b>Description:</b><br>Mrs. Seashore's favorite spelling game is called "Solver." How many words can you find?<br>
<img src='http://graphics.millsberry.com/site_gfx/stat_int_v1.gif' width='25' height='20' border='0'></td>
<td align='center' width='60'><a href='/gamepages/hiscores.phtml?game_id=12'>View<br>Hi Scores</a></td></tr>
<tr><td colspan='3' height='6'><font style='font-size: 1px; line-height: 1px;'>&nbsp;</font></td></tr>
</table>
</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='footer'>
<font style='font-size: 8pt'>THIS PAGE CONTAINS ADVERTISEMENTS</font><br>
MILLSBERRY, characters, logos, product names and all related indicia are trademarks of Mills Online, Inc., &copy; 2004-2006.<BR> &reg; denotes Reg. US Pat. & TM Office. All rights reserved.<br>Use of this site signifies your acceptance of the <a href='/town_hall/terms.phtml'><b>Terms and Conditions</b></a>.<br>Please view our <a href='/town_hall/terms.phtml'><b>Privacy Policy</b></a>
</div>
</div>
<div id='bottom'>&nbsp;</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='debug'>
</div>
</body>
</html>
