<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- 10.100.56.30 -->
<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
<meta http-equiv='imagetoolbar' content='no'>
<meta name='keywords' CONTENT="Mills,Millsbury,Milsberry,Milsbury,Millberry,Millbury,Fun games,Spanish language games,Educational games,Active games,Citizen,Cool stuff,Arcade,Music Mix,Fun,Games,Explore,Adventure,Create,Character,Buddy,Care,Academy,School,Gym,Gymnasium,Solver,Science,Project,Town,Pets,Children's games,Games for kid,Kid games,Kids games,Kid's games,Children,Safe gaming">
<title>Millsberry - View Painting</title>
<link rel='stylesheet' type='text/css' href='/css/global.css'>
<link rel="shortcut icon" href="/favicon.ico">
<script src='/common_js.inc'></script>
</head>
<body leftmargin='0' topmargin='0' marginwidth='0' marginheight='0' bgcolor='#FFFFCC' background='' >
<TABLE BORDER='0' CELLPADDING='5' CELLSPACING='0' WIDTH='100%' HEIGHT='100%'>
<TR>
	<TD HEIGHT='175' ALIGN='CENTER' BGCOLOR='#000000'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/museum/pic_1.swf', '261', '315', '&unixTimeStamp=1156970265', '7', 'noscale');</script></TD>
</TR>
<TR>
	<TD VALIGN='TOP'>
		<DIV ALIGN='CENTER' STYLE='font-size: 14px; font-weight: bold; color: black;'>Lala Deen Dayal: Fatehsingh Rao Gaikwad of Baroda (1891)</DIV>
    Lala Raja Deen Dayal was a pioneer in 19th century Indian photography. During his career, Lala Deen Dayal captured the essence of life in British-colonized India. His portfolio included photographs of British officials and their families, but more striking are his pictures of native Indians. This photograph is a portrait of a member of the Indian nobility, Fatehsingh Rao Gaikwad of Baroda, and is a perfect example of Lala Deen Dayal's ability to beautifully portray the opulence and richness of Indian culture. Though many of his photographs have been lost, those that remain are truly a window into India's past.  </TD>
</TR>
</TABLE>
</body>
</html>
