<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- 10.100.56.24 -->
<html>
<head>
<meta http-equiv='imagetoolbar' content='no'>
<meta name='keywords' content="Mills,Millsbury,Milsberry,Milsbury,Millberry,Millbury,Fun games,Spanish language games,Educational games,Active games,Citizen,Cool stuff,Arcade,Music Mix,Fun,Games,Explore,Adventure,Create,Character,Buddy,Care,Academy,School,Gym,Gymnasium,Solver,Science,Project,Town,Pets,Children's games,Games for kid,Kid games,Kids games,Kid's games,Children,Safe gaming">
<title>Millsberry - View Painting</title>
<script type='text/javascript' src='/common.js'></script>
<link rel='shortcut icon' type='image/x-icon' href='/favicon.ico'>
<!-- Appending v=# to these files causes them to recache in the user's browser when # changes -->
<link rel='stylesheet' type='text/css' href='/css/theme/royal.css?v=2'>
<link rel='stylesheet' type='text/css' href='/css/global.css?v=2'>
<!--[if lt IE 7.00]>
<link rel='stylesheet' type='text/css' href='/css/global.ie.css?v=1'>
<![endif]-->
</head>
<body style='margin: 0; padding: 0; background-color: #FFFFCC;'>
<table width='100%' height='100%' border='0' cellpadding='5' cellspacing='0'>
<tr><td height='150' align='center' bgcolor='#000000'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/museum/MLK.swf', '216', '270', '&unixTimeStamp=1172028102&serverTimeOffset=28800', '', 'exactfit');</script></td></tr>
<tr><td valign='top' align='center'><strong>Martin Luther King, Jr.</strong></td></tr>
<tr><td>This major figure in the Civil Rights Movement was a minister with a vision of a society free of racism. Born in 1929, he became the youngest person to ever receive the Nobel Peace Prize. He practiced nonviolence and was inspired by Mahatma Gandhi to protest peacefully for his cause. Gandhi had successfully used the principles of truth and nonviolence to unite his fellow Indians to seek independence from British rule. King's famous <em>I Have a Dream</em> speech told of his wish for all races to co-exist without hatred or prejudice. Yet his brave quest for equality was cut short by his assassination in 1968. After his death, his wife, Coretta Scott King, continued to spread his message until her death in 2006. Without a doubt, Martin Luther King, Jr. is one of the most celebrated and revered figures in 20th century American history. Today, all 50 states celebrate Martin Luther King Day on the third Monday of every January.</td></tr>
</table>
</body>
</html>
