<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- iadgenmapp13.ood.ops -->
<html>
<head>
<meta http-equiv='imagetoolbar' content='no'>
<meta name='keywords' content="Mills,Millsbury,Milsberry,Milsbury,Millberry,Millbury,Fun games,Spanish language games,Educational games,Active games,Citizen,Cool stuff,Arcade,Music Mix,Fun,Games,Explore,Adventure,Create,Character,Buddy,Care,Academy,School,Gym,Gymnasium,Solver,Science,Project,Town,Pets,Children's games,Games for kid,Kid games,Kids games,Kid's games,Children,Safe gaming">
<title>Millsberry - View Painting</title>
<script type='text/javascript' src='/common.js'></script>
<link rel='shortcut icon' type='image/x-icon' href='/favicon.ico'>
<!-- Appending v=# to these files causes them to recache in the user's browser when # changes -->
<link rel='stylesheet' type='text/css' href='/css/theme/royal.css?v=2'>
<link rel='stylesheet' type='text/css' href='/css/global.css?v=2'>
<!--[if lt IE 7.00]>
<link rel='stylesheet' type='text/css' href='/css/global.ie.css?v=1'>
<![endif]-->
</head>
<body style='margin: 0; padding: 0; background-color: #FFFFCC;'>
<table width='100%' height='100%' border='0' cellpadding='5' cellspacing='0'>
<tr><td height='150' align='center' bgcolor='#000000'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/museum/MX.swf', '216', '270', '&unixTimeStamp=1171853231&serverTimeOffset=28800', '', 'exactfit');</script></td></tr>
<tr><td valign='top' align='center'><strong>Malcolm X</strong></td></tr>
<tr><td>Born Malcolm Little in 1925, this historical figure joined the Nation of Islam after a turbulent youth spent in foster homes. His run-ins with the law landed him in prison, but when he emerged and embraced the Muslim faith, he converted many people to the cause of Islam, including Cassius Clay, who would change his name to Muhammad Ali. As a Black Muslim minister, Malcolm X was extremely influential, and also advocated black pride and human rights. But, as his relationship with the Nation of Islam grew strained, his life was constantly threatened, and he was eventually assassinated in 1965. Yet he remains an inspiration to many who admired his determination to eradicate racial problems, and will not soon be forgotten.</td></tr>
</table>
</body>
</html>
