<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
<HEAD>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<TITLE>Millsberry - Community Center</TITLE>
  <LINK REL="stylesheet" TYPE="text/css" HREF="http://www.millsberry.com/styles.css">
  <LINK REL="SHORTCUT ICON" HREF="http://www.millsberry.com/favicon.ico">
  </HEAD>
<SCRIPT LANGUAGE="JavaScript" SRC="http://www.millsberry.com/commonJS.js"></SCRIPT>
<BODY LEFTMARGIN=0 TOPMARGIN=0 MARGINWIDTH=0 MARGINHEIGHT=0 BACKGROUND='http://graphics.millsberry.com/site_gfx/tile_mill.gif' >
<TABLE BORDER="0" HEIGHT="100%" WIDTH="100%" ALIGN="LEFT" CELLSPACING="0" CELLPADDING="0">
  <TR>
    <TD ROWSPAN='2'><A HREF='http://www.millsberry.com'><IMG SRC="http://graphics.millsberry.com/site_gfx/logo.gif" onMouseOut="src='http://graphics.millsberry.com/site_gfx/logo.gif';" onMouseOver="src='http://graphics.millsberry.com/site_gfx/logo_over.gif';" BORDER="0" ALT="Back to MAIN"></A></TD>
    <TD WIDTH="650" HEIGHT="55" VALIGN="TOP" BGCOLOR='#000000'>
      <TABLE BORDER='0' CELLPADDING='0' CELLSPACING='0'>
        <TR>
          <TD>
            <A HREF="http://www.millsberry.com/home/"><IMG SRC="http://graphics.millsberry.com/site_gfx/visit_home.gif" BORDER="0" ALT="Visit your Home!" onMouseOut="src='http://graphics.millsberry.com/site_gfx/visit_home.gif';" onMouseOver="src='http://graphics.millsberry.com/site_gfx/visit_home_over.gif';"></A>
          </TD>
          <TD>
            <A HREF="http://www.millsberry.com/main_map.phtml?location=downtown"><IMG SRC="http://graphics.millsberry.com/site_gfx/visit_shopping.gif" BORDER="0" ALT="Visit the Town Center!" onMouseOut="src='http://graphics.millsberry.com/site_gfx/visit_shopping.gif';" onMouseOver="src='http://graphics.millsberry.com/site_gfx/visit_shopping_over.gif';"></A>
          </TD>
          <TD>
            <A HREF="http://www.millsberry.com/gamepages/hiscores.phtml"><IMG SRC="http://graphics.millsberry.com/site_gfx/visit_hi_scores.gif" BORDER="0" ALT="Visit the Hi Scores!" onMouseOut="src='http://graphics.millsberry.com/site_gfx/visit_hi_scores.gif';" onMouseOver="src='http://graphics.millsberry.com/site_gfx/visit_hi_scores_over.gif';"></A>
          </TD>
          <TD>
            <A HREF="http://www.millsberry.com/town_hall/faq.phtml"><IMG SRC="http://graphics.millsberry.com/site_gfx/visit_faq.gif" BORDER="0" ALT="Visit the Help Pages!" onMouseOut="src='http://graphics.millsberry.com/site_gfx/visit_faq.gif';" onMouseOver="src='http://graphics.millsberry.com/site_gfx/visit_faq_over.gif';"></A>
          </TD>
        </TR>
        <FORM NAME='login' ACTION='http://www.millsberry.com/index.phtml' method='post'>
        <TR>
          <TD COLSPAN='4' VALIGN='bottom'>
            <FONT COLOR="#FFFFFF">
              <B>
                &nbsp;&nbsp;&nbsp;
                Username
                       <input type='text' name='login_username' SIZE='10'>
                       Password
                       <input type='password' name='login_pass' SIZE='10'>&nbsp;
                       <input type='image' src='http://graphics.millsberry.com/site_gfx/visit_log_in.gif' HEIGHT=20 name='login' value='go' border='0' align='top' onMouseOut="src='http://graphics.millsberry.com/site_gfx/visit_log_in.gif';" onMouseOver="src='http://graphics.millsberry.com/site_gfx/visit_log_in_over.gif';"> <A HREF='http://www.millsberry.com/town_hall/support.phtml?q=pw'><FONT COLOR='#FFFFFF' class='smallfont'>[ forgot your password? ]</FONT></A>              </B>
            </FONT>
          </TD>
        </TR>
        </FORM>
      </TABLE>
    </TD>
    <TD WIDTH="100%" BGCOLOR='#000000' COLSPAN='2'>
      
    </TD>
  </TR>
  <FORM NAME='search' ACTION='http://www.millsberry.com/site_search.phtml' method='get'>
  <TR>
    <TD COLSPAN='3' WIDTH="600" HEIGHT="25" VALIGN="TOP" ALIGN="LEFT" CLASS="header_stripe_TD"><TABLE WIDTH='100%' BORDER='0' CELLPADDING='0' CELLSPACING='0'><TR><TD><IMG SRC='http://graphics.millsberry.com/site_gfx/header_stripe.gif'><IMG SRC='http://graphics.millsberry.com/site_gfx/slice_11.gif'></TD><TD ALIGN='RIGHT' CLASS='header_stripe_TD'>Address Book<INPUT TYPE='text' NAME='search'></TD><TD><input type='image' src='http://graphics.millsberry.com/site_gfx/visit_go.gif' HEIGHT='25' name='login' border='0' align='top' onMouseOut="src='http://graphics.millsberry.com/site_gfx/visit_go.gif';" onMouseOver="src='http://graphics.millsberry.com/site_gfx/visit_go_over.gif';" CLASS='checkbox'></TD></TR></TABLE></TD>
  </TR>
  </FORM>
  <TR>
    <TD WIDTH="150" VALIGN="TOP" HEIGHT="100%" CLASS="sidenav_TD" background="http://graphics.millsberry.com/site_gfx/left_side_nav_stripe.gif">
    <TABLE BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH='100%'>
<TR>
<TD ALIGN='CENTER' VALIGN='TOP'>
<A HREF='http://www.millsberry.com/main_map.phtml'><IMG SRC='http://graphics.millsberry.com/site_gfx/mapbutton.gif' onMouseDown="src='http://graphics.millsberry.com/site_gfx/mapbutton_down.gif';" onMouseOut="src='http://graphics.millsberry.com/site_gfx/mapbutton.gif';" 
onMouseOver="src='http://graphics.millsberry.com/site_gfx/mapbutton_over.gif';" BORDER='0'></A><BR>
<A HREF='http://www.millsberry.com/complex/arcade.phtml'><IMG SRC='http://graphics.millsberry.com/site_gfx/gamesbutton.gif' onMouseDown="src='http://graphics.millsberry.com/site_gfx/gamesbutton_down.gif';" onMouseOut="src='http://graphics.millsberry.com/site_gfx/gamesbutton.gif';" 
onMouseOver="src='http://graphics.millsberry.com/site_gfx/gamesbutton_over.gif';" BORDER='0'></A><BR>
<A HREF='http://www.millsberry.com/signup.phtml'><IMG SRC='http://graphics.millsberry.com/site_gfx/prebuddy.gif' BORDER='1'></A><BR>
  <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" width="150" height="70">
  <param name="allowScriptAccess" value="sameDomain" />
  <param name="movie" value="http://graphics.millsberry.com/site_gfx/sideNavButton_v2.swf?sideNavButtonXML=<button><name>sideNavButton_mc</name><label><text>%3CP%20ALIGN%3D%22CENTER%22%3E%3CFONT%20SIZE%3D%2215%22%3E%3CP%3E%26nbsp%3B%3C%2FP%3E%3C%2FFONT%3E%3CFONT%20SIZE%3D%2228%22%20COLOR%3D%22%23FFFFFF%22%3ESign%20Up%21%21%3C%2FFONT%3E%3C%2FP%3E</text><dropShadow><x>3</x><y>3</y><colorTransform>0,0,0,0,0,0,50,0</colorTransform></dropShadow></label><url>http%3A%2F%2Fwww.millsberry.com%2Fsignup.phtml</url><target>_self</target></button>" />
  <param name="quality" value="high" />
  <param name="menu" value="false" />
  <param name="wmode" value="transparent" />
  <param name="scale" value="noscale">
  <param name="salign" value="lt" />
  <PARAM NAME="FlashVars" VALUE="unixTimeStamp=1116292767">
  <embed FlashVars="unixTimeStamp=1116292767" src="http://graphics.millsberry.com/site_gfx/sideNavButton_v2.swf?sideNavButtonXML=<button><name>sideNavButton_mc</name><label><text>%3CP%20ALIGN%3D%22CENTER%22%3E%3CFONT%20SIZE%3D%2215%22%3E%3CP%3E%26nbsp%3B%3C%2FP%3E%3C%2FFONT%3E%3CFONT%20SIZE%3D%2228%22%20COLOR%3D%22%23FFFFFF%22%3ESign%20Up%21%21%3C%2FFONT%3E%3C%2FP%3E</text><dropShadow><x>3</x><y>3</y><colorTransform>0,0,0,0,0,0,50,0</colorTransform></dropShadow></label><url>http%3A%2F%2Fwww.millsberry.com%2Fsignup.phtml</url><target>_self</target></button>" quality="high" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" scale="exactfit" width="150" height="70" wmode="transparent">
  </embed>
  </object></TD>
</TR>
</TABLE>    </TD>
    <TD WIDTH="650" HEIGHT="100%" VALIGN="TOP" ALIGN='LEFT'><object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" width="600" height="400"><param name=movie value="http://graphics.millsberry.com/site_gfx/interiors/int_ext_com_center.swf"><param name=quality value=high><param name=menu value=true><param name="wmode" value="transparent" /><param name=scale value=exactfit><PARAM NAME="FlashVars" VALUE="unixTimeStamp=1116292767"><embed FlashVars="unixTimeStamp=1116292767" src="http://graphics.millsberry.com/site_gfx/interiors/int_ext_com_center.swf" wmode="transparent" quality="high" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" scale="exactfit" width="600" height="400"></embed></object><TABLE BORDER='0' CELLPADDING='0' CELLSPACING='0' WIDTH='600'>
    <TR>
      <TD ALIGN='LEFT' CLASS='header_stripe_TD'>
        Community Center
      </TD>
    </TR>
    <TR>
      <TD ALIGN='LEFT' COLSPAN='3'>
        <strong>
        After months of anticipation, the Millsberry Community Center proudly opens its doors to the public.  
        The Center, funded in large part by private <A HREF='../'>donations</A> from Millsberry's citizens, is expected to provide 
        townspeople with a great place to meet, interact and participate in various programs available to all 
        in the community.
        <P>
        Have a look around and see what the Millsberry Community Center has to offer!
        </strong>
      </TD>
    </TR>
</TABLE></TD>
        <TD WIDTH='150' VALIGN='TOP' ALIGN='CENTER' HEIGHT='100%'>          </TD>
          <TD WIDTH='100%'>
            &nbsp;
          </TD>
  </TR>
  <TR>
    <TD COLSPAN="4" WIDTH="100%" ALIGN="CENTER" CLASS="footer_TD">
      <SPAN CLASS='footerfont'>
      MILLSBERRY, characters, logos, product names and all related indicia are trademarks of Mills Online, Inc., &copy; 2004.<BR> &reg; denotes Reg. US Pat. & TM Office. All rights reserved.
        <BR>
        Use of this site signifies your acceptance of the <A HREF='http://www.millsberry.com/town_hall/terms.phtml'>Terms and Conditions</A>.
        <BR>
        Please view our <A HREF='http://www.millsberry.com/town_hall/terms.phtml'>Privacy Policy</A>.      </SPAN>
    </TD>
</TABLE>
</BODY>
</HTML>
