<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- dev.millsberry.com -->
<html>
<head>
    <meta http-equiv="imagetoolbar" content="no">
    <meta name="keywords" content="Mills,Millsbury,Milsberry,Milsbury,Millberry,Millbury,Fun games,Spanish language games,Educational games,Active games,Citizen,Cool stuff,Arcade,Music Mix,Fun,Games,Explore,Adventure,Create,Character,Buddy,Care,Academy,School,Gym,Gymnasium,Solver,Science,Project,Town,Pets,Children's games,Games for kid,Kid games,Kids games,Kid's games,Children,Safe gaming">
    <title>Millsberry - High Scores</title>
    <script type="text/javascript" src="/common.js?v=2"></script>
    <script type="text/javascript" src="/js/swfobject.js"></script>

    <link rel="stylesheet" type="text/css" href="/css/theme/royal.css?v=2">
    <link rel="stylesheet" type="text/css" href="/css/template.css?v=5">
    <link rel="stylesheet" type="text/css" href="/css/global.css?v=2">
    <link rel="stylesheet" type="text/css" href="/css/gamepages/hiscores.css?v=1">

    <!--[if lt IE 7.00]>
        <link rel="stylesheet" type="text/css" href="/css/template.ie.css?v=1">
        <link rel="stylesheet" type="text/css" href="/css/global.ie.css?v=1">
        <![endif]-->

</head>
</head>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<body>
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript"> _uacct = "UA-1272972-1"; urchinTracker();</script>
<div id='top'>
    <a href='/'><span id='logo'>&nbsp;</span></a>
    <div id='layout_head'>
       <div id='login_info'>
           1,889 citizens online now&nbsp;|&nbsp; <a href='/town_hall/faq.phtml'>HELP</a>
       </div> <!--login_info-->
       <div id='stripe'>
                <div id="top_nav_flashcontent">
     <!--default content-->
	 </div>

	<script type="text/javascript">
		// <![CDATA[
        
        // redirect to the upgrade page if flash is installed, but version is too low
		var version = deconcept.SWFObjectUtil.getPlayerVersion();
        if(version["major"] < 8 && version["major"] > 0) {
            window.location='/flash.phtml';
        } else {
            writeFlashContent();
        }
        
        function writeFlashContent() {
            var so = new SWFObject("http://devgraphics.millsberry.com/template/top_nav.swf?url=http%3A%2F%2Fdev.millsberry.com%2Ftop_nav_xml.phtml", "top_nav", "750", "36", "8");
            so.addParam("wmode", "transparent");
            so.addParam("scale", "noscale");
            so.addParam("AllowScriptAccess", "always");
            so.useExpressInstall('http://devgraphics.millsberry.com/expressinstall.swf');
            so.write("top_nav_flashcontent");
        }
		
		// ]]>
	</script>
 
       </div> <!-- stripe -->
    </div> <!-- layout_head -->
</div> <!-- top -->
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='body'>
<div id='layout_body'>
<div id='side_nav'>
<script type='text/javascript'>flash_object ('http://devgraphics.millsberry.com/template/side_nav_v1.swf', '150', '1280', '&url=http%3A%2F%2Fdev.millsberry.com%2Fside_nav_xml.phtml%3Fpage_relative_url%3D%252Fgamepages%252Fhiscores.phtml%253Fgame_id%253D260%26login_status%3D0%26now%3D1209998816&unixTimeStamp=1209998816&serverTimeOffset=28800', '8', 'noscale', 'transparent');</script></div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='main'>

<div id='interior'><script type='text/javascript'>flash_object ('http://devgraphics.millsberry.com/game_interiors/interior_260_v6.swf', '600', '400', '&unixTimeStamp=1209998816&serverTimeOffset=28800', '7', 'noscale', 'transparent');</script></div>
<div id='interior_stripe'>High Scores : <a href='flashgame_ctp.phtml?game_id=260'>Reese's&reg; Puffs&reg; Cereal Snowboard Slalom</a></div>
<div id='content'>

<table id='high_scores' width='100%' border='0' cellpadding='5' cellspacing='0'>
<tr>
<td class='high_score_header' width='10%' align='center' bgcolor='silver'>Rank</td>
<td class='high_score_header' align='center' bgcolor='silver'>Username</td>
<td class='high_score_header' align='center' bgcolor='silver'>Date</td>
<td class='high_score_header' width='20%' align='center' bgcolor='silver'>Score</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>1</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=irish323'>irish323</a></td>
<td align='center' bgcolor='#EEEEEE'>05/05/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,778</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>2</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=auntnay923'>auntnay923</a></td>
<td align='center' bgcolor='#FFFFFF'>05/04/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>1,576</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>3</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=aarongon1234'>aarongon1234</a></td>
<td align='center' bgcolor='#EEEEEE'>05/04/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,266</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>4</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=cuteltleangel'>cuteltleangel</a></td>
<td align='center' bgcolor='#FFFFFF'>05/01/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>1,260</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>5</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=hottie_chic123'>hottie_chic123</a></td>
<td align='center' bgcolor='#EEEEEE'>05/02/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,260</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>6</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=fra9898'>fra9898</a></td>
<td align='center' bgcolor='#FFFFFF'>05/05/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>1,259</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>7</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=kellybel9890'>kellybel9890</a></td>
<td align='center' bgcolor='#EEEEEE'>05/02/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,256</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>8</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=dami1998'>dami1998</a></td>
<td align='center' bgcolor='#FFFFFF'>05/04/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>1,255</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>9</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=jessebrown32'>jessebrown32</a></td>
<td align='center' bgcolor='#EEEEEE'>05/01/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,252</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>10</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=8702000'>8702000</a></td>
<td align='center' bgcolor='#FFFFFF'>05/03/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>1,252</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>11</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=stellarstella81'>stellarstella81</a></td>
<td align='center' bgcolor='#EEEEEE'>05/02/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,248</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>12</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=the_most_awesome'>the_most_awesome</a></td>
<td align='center' bgcolor='#FFFFFF'>05/04/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>1,248</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>13</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=nightwolf210'>nightwolf210</a></td>
<td align='center' bgcolor='#EEEEEE'>05/04/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,248</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>14</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=singpong'>singpong</a></td>
<td align='center' bgcolor='#FFFFFF'>05/02/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>1,245</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>15</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=kranich1902'>kranich1902</a></td>
<td align='center' bgcolor='#EEEEEE'>05/02/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,245</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>16</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=standgurl001'>standgurl001</a></td>
<td align='center' bgcolor='#FFFFFF'>05/02/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>1,244</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>17</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=kitkatlover5335'>kitkatlover5335</a></td>
<td align='center' bgcolor='#EEEEEE'>05/04/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,244</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>18</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=pinkdot947'>pinkdot947</a></td>
<td align='center' bgcolor='#FFFFFF'>05/03/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>1,244</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>19</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=yodazne123'>yodazne123</a></td>
<td align='center' bgcolor='#EEEEEE'>05/02/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,243</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>20</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=jakes999'>jakes999</a></td>
<td align='center' bgcolor='#FFFFFF'>05/02/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>1,243</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>21</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=lazenby11'>lazenby11</a></td>
<td align='center' bgcolor='#EEEEEE'>05/02/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,240</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>22</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=mla_pretty'>mla_pretty</a></td>
<td align='center' bgcolor='#FFFFFF'>05/05/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>1,234</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>23</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=bast0522'>bast0522</a></td>
<td align='center' bgcolor='#EEEEEE'>05/02/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,232</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>24</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=issa_1'>issa_1</a></td>
<td align='center' bgcolor='#FFFFFF'>05/05/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>1,216</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>25</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=yungreek'>yungreek</a></td>
<td align='center' bgcolor='#EEEEEE'>05/05/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>1,215</td>
</tr>
</table></div></div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='footer'>
    
<div id="ad_spot">
    <a href="javascript:void(0);"  onMouseOver="showspot(); return false;" onMouseOut="hidespot(); return false;" >
        <img src="http://devgraphics.millsberry.com/site_gfx/adSpot_icon.gif" width="30" height="25"  border="0"/>
    </a>
</div>
<div id="warning" style="position:absolute; visibility:hidden;">
    <img src="http://devgraphics.millsberry.com/site_gfx/adSpot_popup.gif" hspace="10" width="258" height="49" alt="" border="0"/>
</div>
MILLSBERRY &reg;, characters, logos, product names 
and all related indicia are trademarks of Mills Online, Inc., &copy; 
2004-2008.<BR> &reg; denotes Reg. US Pat. & TM Office. All rights 
reserved.<br>
Use of this site signifies your acceptance of the <a href='/town_hall/terms.phtml'><b>Terms and Conditions</b></a>.
Please view our <a href='/town_hall/terms.phtml'><b>Privacy Policy</b></a>.

</div>
</div>
<div id='bottom'>&nbsp;</div>
</div>
</body>
</html>
