<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- dev.millsberry.com -->
<html>
<head>
    <meta http-equiv="imagetoolbar" content="no">
    <meta name="keywords" content="Mills,Millsbury,Milsberry,Milsbury,Millberry,Millbury,Fun games,Spanish language games,Educational games,Active games,Citizen,Cool stuff,Arcade,Music Mix,Fun,Games,Explore,Adventure,Create,Character,Buddy,Care,Academy,School,Gym,Gymnasium,Solver,Science,Project,Town,Pets,Children's games,Games for kid,Kid games,Kids games,Kid's games,Children,Safe gaming">
    <title>Millsberry - High Scores</title>
    <script type="text/javascript" src="/common.js?v=2"></script>
    <script type="text/javascript" src="/js/swfobject.js"></script>

    <link rel="stylesheet" type="text/css" href="/css/theme/royal.css?v=2">
    <link rel="stylesheet" type="text/css" href="/css/template.css?v=5">
    <link rel="stylesheet" type="text/css" href="/css/global.css?v=2">
    <link rel="stylesheet" type="text/css" href="/css/gamepages/hiscores.css?v=1">

    <!--[if lt IE 7.00]>
        <link rel="stylesheet" type="text/css" href="/css/template.ie.css?v=1">
        <link rel="stylesheet" type="text/css" href="/css/global.ie.css?v=1">
        <![endif]-->

</head>
</head>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<body>
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript"> _uacct = "UA-1272972-1"; urchinTracker();</script>
<div id='top'>
    <a href='/'><span id='logo'>&nbsp;</span></a>
    <div id='layout_head'>
       <div id='login_info'>
           1,861 citizens online now&nbsp;|&nbsp; <a href='/town_hall/faq.phtml'>HELP</a>
       </div> <!--login_info-->
       <div id='stripe'>
                <div id="top_nav_flashcontent">
     <!--default content-->
	 </div>

	<script type="text/javascript">
		// <![CDATA[
        
        // redirect to the upgrade page if flash is installed, but version is too low
		var version = deconcept.SWFObjectUtil.getPlayerVersion();
        if(version["major"] < 8 && version["major"] > 0) {
            window.location='/flash.phtml';
        } else {
            writeFlashContent();
        }
        
        function writeFlashContent() {
            var so = new SWFObject("http://devgraphics.millsberry.com/template/top_nav.swf?url=http%3A%2F%2Fdev.millsberry.com%2Ftop_nav_xml.phtml", "top_nav", "750", "36", "8");
            so.addParam("wmode", "transparent");
            so.addParam("scale", "noscale");
            so.addParam("AllowScriptAccess", "always");
            so.useExpressInstall('http://devgraphics.millsberry.com/expressinstall.swf');
            so.write("top_nav_flashcontent");
        }
		
		// ]]>
	</script>
 
       </div> <!-- stripe -->
    </div> <!-- layout_head -->
</div> <!-- top -->
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='body'>
<div id='layout_body'>
<div id='side_nav'>
<script type='text/javascript'>flash_object ('http://devgraphics.millsberry.com/template/side_nav_v1.swf', '150', '1280', '&url=http%3A%2F%2Fdev.millsberry.com%2Fside_nav_xml.phtml%3Fpage_relative_url%3D%252Fgamepages%252Fhiscores.phtml%253Fgame_id%253D140%26login_status%3D0%26now%3D1209998781&unixTimeStamp=1209998781&serverTimeOffset=28800', '8', 'noscale', 'transparent');</script></div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='main'>

<div id='interior'><script type='text/javascript'>flash_object ('http://devgraphics.millsberry.com/game_interiors/interior_140_v1.swf', '600', '400', '&unixTimeStamp=1209998781&serverTimeOffset=28800', '7', 'noscale', 'transparent');</script></div>
<div id='interior_stripe'>High Scores : <a href='flashgame_ctp.phtml?game_id=140'>Sink The Three!</a></div>
<div id='content'>

<table id='high_scores' width='100%' border='0' cellpadding='5' cellspacing='0'>
<tr>
<td class='high_score_header' width='10%' align='center' bgcolor='silver'>Rank</td>
<td class='high_score_header' align='center' bgcolor='silver'>Username</td>
<td class='high_score_header' align='center' bgcolor='silver'>Date</td>
<td class='high_score_header' width='20%' align='center' bgcolor='silver'>Score</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>1</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=hheaathherr'>hheaathherr</a></td>
<td align='center' bgcolor='#EEEEEE'>05/04/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>4,083</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>2</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=jina007'>jina007</a></td>
<td align='center' bgcolor='#FFFFFF'>05/04/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>4,035</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>3</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=poisonivey45'>poisonivey45</a></td>
<td align='center' bgcolor='#EEEEEE'>05/04/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>3,977</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>4</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=321vovo'>321vovo</a></td>
<td align='center' bgcolor='#FFFFFF'>05/01/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>3,958</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>5</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=mrwoo20'>mrwoo20</a></td>
<td align='center' bgcolor='#EEEEEE'>05/01/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>3,900</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>6</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=madilb93'>madilb93</a></td>
<td align='center' bgcolor='#FFFFFF'>05/01/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>3,879</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>7</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=pirateshockey07'>pirateshockey07</a></td>
<td align='center' bgcolor='#EEEEEE'>05/04/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>3,862</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>8</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=princesscrownz'>princesscrownz</a></td>
<td align='center' bgcolor='#FFFFFF'>05/03/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>3,839</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>9</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=kyzel_cute21'>kyzel_cute21</a></td>
<td align='center' bgcolor='#EEEEEE'>05/02/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>3,749</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>10</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=playmakermax5'>playmakermax5</a></td>
<td align='center' bgcolor='#FFFFFF'>05/03/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>3,716</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>11</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=doggypuppydogpup3'>doggypuppydogpup3</a></td>
<td align='center' bgcolor='#EEEEEE'>05/04/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>3,713</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>12</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=kennyabeast'>kennyabeast</a></td>
<td align='center' bgcolor='#FFFFFF'>05/01/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>3,711</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>13</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=jonhinds'>jonhinds</a></td>
<td align='center' bgcolor='#EEEEEE'>05/01/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>3,658</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>14</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=lil50cent5'>lil50cent5</a></td>
<td align='center' bgcolor='#FFFFFF'>05/03/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>3,656</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>15</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=mark1608'>mark1608</a></td>
<td align='center' bgcolor='#EEEEEE'>05/04/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>3,621</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>16</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=mjsuperstar1'>mjsuperstar1</a></td>
<td align='center' bgcolor='#FFFFFF'>05/03/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>3,609</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>17</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=hawg1'>hawg1</a></td>
<td align='center' bgcolor='#EEEEEE'>05/05/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>3,602</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>18</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=storm_buster'>storm_buster</a></td>
<td align='center' bgcolor='#FFFFFF'>05/05/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>3,570</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>19</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=markey0101'>markey0101</a></td>
<td align='center' bgcolor='#EEEEEE'>05/03/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>3,553</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>20</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=garngarn51294'>garngarn51294</a></td>
<td align='center' bgcolor='#FFFFFF'>05/01/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>3,549</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>21</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=angela272727'>angela272727</a></td>
<td align='center' bgcolor='#EEEEEE'>05/03/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>3,544</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>22</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=raphaellesnok94'>raphaellesnok94</a></td>
<td align='center' bgcolor='#FFFFFF'>05/02/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>3,505</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>23</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=babyblaze101'>babyblaze101</a></td>
<td align='center' bgcolor='#EEEEEE'>05/03/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>3,476</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>24</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=katrice81196'>katrice81196</a></td>
<td align='center' bgcolor='#FFFFFF'>05/02/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>3,414</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>25</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=gyika'>gyika</a></td>
<td align='center' bgcolor='#EEEEEE'>05/04/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>3,409</td>
</tr>
</table></div></div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='footer'>
    
<div id="ad_spot">
    <a href="javascript:void(0);"  onMouseOver="showspot(); return false;" onMouseOut="hidespot(); return false;" >
        <img src="http://devgraphics.millsberry.com/site_gfx/adSpot_icon.gif" width="30" height="25"  border="0"/>
    </a>
</div>
<div id="warning" style="position:absolute; visibility:hidden;">
    <img src="http://devgraphics.millsberry.com/site_gfx/adSpot_popup.gif" hspace="10" width="258" height="49" alt="" border="0"/>
</div>
MILLSBERRY &reg;, characters, logos, product names 
and all related indicia are trademarks of Mills Online, Inc., &copy; 
2004-2008.<BR> &reg; denotes Reg. US Pat. & TM Office. All rights 
reserved.<br>
Use of this site signifies your acceptance of the <a href='/town_hall/terms.phtml'><b>Terms and Conditions</b></a>.
Please view our <a href='/town_hall/terms.phtml'><b>Privacy Policy</b></a>.

</div>
</div>
<div id='bottom'>&nbsp;</div>
</div>
</body>
</html>
