<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- dev.millsberry.com -->
<html>
<head>
    <meta http-equiv="imagetoolbar" content="no">
    <meta name="keywords" content="Mills,Millsbury,Milsberry,Milsbury,Millberry,Millbury,Fun games,Spanish language games,Educational games,Active games,Citizen,Cool stuff,Arcade,Music Mix,Fun,Games,Explore,Adventure,Create,Character,Buddy,Care,Academy,School,Gym,Gymnasium,Solver,Science,Project,Town,Pets,Children's games,Games for kid,Kid games,Kids games,Kid's games,Children,Safe gaming">
    <title>Millsberry - High Scores</title>
    <script type="text/javascript" src="/common.js?v=2"></script>
    <script type="text/javascript" src="/js/swfobject.js"></script>

    <link rel="stylesheet" type="text/css" href="/css/theme/royal.css?v=2">
    <link rel="stylesheet" type="text/css" href="/css/template.css?v=5">
    <link rel="stylesheet" type="text/css" href="/css/global.css?v=2">
    <link rel="stylesheet" type="text/css" href="/css/gamepages/hiscores.css?v=1">

    <!--[if lt IE 7.00]>
        <link rel="stylesheet" type="text/css" href="/css/template.ie.css?v=1">
        <link rel="stylesheet" type="text/css" href="/css/global.ie.css?v=1">
        <![endif]-->

</head>
</head>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<body>
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript"> _uacct = "UA-1272972-1"; urchinTracker();</script>
<div id='top'>
    <a href='/'><span id='logo'>&nbsp;</span></a>
    <div id='layout_head'>
       <div id='login_info'>
           1,876 citizens online now&nbsp;|&nbsp; <a href='/town_hall/faq.phtml'>HELP</a>
       </div> <!--login_info-->
       <div id='stripe'>
                <div id="top_nav_flashcontent">
     <!--default content-->
	 </div>

	<script type="text/javascript">
		// <![CDATA[
        
        // redirect to the upgrade page if flash is installed, but version is too low
		var version = deconcept.SWFObjectUtil.getPlayerVersion();
        if(version["major"] < 8 && version["major"] > 0) {
            window.location='/flash.phtml';
        } else {
            writeFlashContent();
        }
        
        function writeFlashContent() {
            var so = new SWFObject("http://devgraphics.millsberry.com/template/top_nav.swf?url=http%3A%2F%2Fdev.millsberry.com%2Ftop_nav_xml.phtml", "top_nav", "750", "36", "8");
            so.addParam("wmode", "transparent");
            so.addParam("scale", "noscale");
            so.addParam("AllowScriptAccess", "always");
            so.useExpressInstall('http://devgraphics.millsberry.com/expressinstall.swf');
            so.write("top_nav_flashcontent");
        }
		
		// ]]>
	</script>
 
       </div> <!-- stripe -->
    </div> <!-- layout_head -->
</div> <!-- top -->
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='body'>
<div id='layout_body'>
<div id='side_nav'>
<script type='text/javascript'>flash_object ('http://devgraphics.millsberry.com/template/side_nav_v1.swf', '150', '1280', '&url=http%3A%2F%2Fdev.millsberry.com%2Fside_nav_xml.phtml%3Fpage_relative_url%3D%252Fgamepages%252Fhiscores.phtml%253Fgame_id%253D160%26login_status%3D0%26now%3D1209998791&unixTimeStamp=1209998791&serverTimeOffset=28800', '8', 'noscale', 'transparent');</script></div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='main'>

<div id='interior'><script type='text/javascript'>flash_object ('http://devgraphics.millsberry.com/game_interiors/interior_160_v1.swf', '600', '400', '&unixTimeStamp=1209998791&serverTimeOffset=28800', '7', 'noscale', 'transparent');</script></div>
<div id='interior_stripe'>High Scores : <a href='flashgame_ctp.phtml?game_id=160'>Sherman Home Run Derby</a></div>
<div id='content'>

<table id='high_scores' width='100%' border='0' cellpadding='5' cellspacing='0'>
<tr>
<td class='high_score_header' width='10%' align='center' bgcolor='silver'>Rank</td>
<td class='high_score_header' align='center' bgcolor='silver'>Username</td>
<td class='high_score_header' align='center' bgcolor='silver'>Date</td>
<td class='high_score_header' width='20%' align='center' bgcolor='silver'>Score</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>1</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=shy029'>shy029</a></td>
<td align='center' bgcolor='#EEEEEE'>05/04/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>104,448</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>2</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=cheech556'>cheech556</a></td>
<td align='center' bgcolor='#FFFFFF'>05/01/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>103,131</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>3</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=melindachi'>melindachi</a></td>
<td align='center' bgcolor='#EEEEEE'>05/03/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>88,620</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>4</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=peterox12'>peterox12</a></td>
<td align='center' bgcolor='#FFFFFF'>05/03/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>83,448</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>5</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=snot511'>snot511</a></td>
<td align='center' bgcolor='#EEEEEE'>05/04/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>70,044</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>6</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=melissa9222'>melissa9222</a></td>
<td align='center' bgcolor='#FFFFFF'>05/03/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>68,155</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>7</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=magiccheese'>magiccheese</a></td>
<td align='center' bgcolor='#EEEEEE'>05/04/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>68,107</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>8</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=fruitcup12'>fruitcup12</a></td>
<td align='center' bgcolor='#FFFFFF'>05/04/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>65,535</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>9</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=eagles8000'>eagles8000</a></td>
<td align='center' bgcolor='#EEEEEE'>05/04/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>62,540</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>10</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=lkjsd'>lkjsd</a></td>
<td align='center' bgcolor='#FFFFFF'>05/04/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>61,481</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>11</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=pinkcutie1926'>pinkcutie1926</a></td>
<td align='center' bgcolor='#EEEEEE'>05/04/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>60,469</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>12</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=repeatpass'>repeatpass</a></td>
<td align='center' bgcolor='#FFFFFF'>05/03/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>60,390</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>13</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=dl100994'>dl100994</a></td>
<td align='center' bgcolor='#EEEEEE'>05/04/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>60,262</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>14</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=xavier18rocks'>xavier18rocks</a></td>
<td align='center' bgcolor='#FFFFFF'>05/02/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>57,073</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>15</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=jeremiah_p'>jeremiah_p</a></td>
<td align='center' bgcolor='#EEEEEE'>05/05/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>52,842</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>16</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=bagelman8'>bagelman8</a></td>
<td align='center' bgcolor='#FFFFFF'>05/01/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>52,780</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>17</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=agraham673'>agraham673</a></td>
<td align='center' bgcolor='#EEEEEE'>05/03/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>52,120</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>18</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=jlow1998'>jlow1998</a></td>
<td align='center' bgcolor='#FFFFFF'>05/03/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>51,330</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>19</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=celadnaldnew'>celadnaldnew</a></td>
<td align='center' bgcolor='#EEEEEE'>05/03/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>50,660</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>20</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=sauceman449'>sauceman449</a></td>
<td align='center' bgcolor='#FFFFFF'>05/03/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>50,217</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>21</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=mrhotwheel'>mrhotwheel</a></td>
<td align='center' bgcolor='#EEEEEE'>05/03/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>50,212</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>22</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=mark1608'>mark1608</a></td>
<td align='center' bgcolor='#FFFFFF'>05/04/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>47,985</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>23</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=stormman8'>stormman8</a></td>
<td align='center' bgcolor='#EEEEEE'>05/02/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>47,828</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#FFFFFF'>24</td>
<td align='center' bgcolor='#FFFFFF'><a href='/home/?user=dssdss28871135t'>dssdss28871135t</a></td>
<td align='center' bgcolor='#FFFFFF'>05/03/2008</td>
<td width='10%' align='center' bgcolor='#FFFFFF'>45,793</td>
</tr>
<tr>
<td width='10%' align='center' bgcolor='#EEEEEE'>25</td>
<td align='center' bgcolor='#EEEEEE'><a href='/home/?user=bradleyb'>bradleyb</a></td>
<td align='center' bgcolor='#EEEEEE'>05/03/2008</td>
<td width='10%' align='center' bgcolor='#EEEEEE'>45,669</td>
</tr>
</table></div></div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='footer'>
    
<div id="ad_spot">
    <a href="javascript:void(0);"  onMouseOver="showspot(); return false;" onMouseOut="hidespot(); return false;" >
        <img src="http://devgraphics.millsberry.com/site_gfx/adSpot_icon.gif" width="30" height="25"  border="0"/>
    </a>
</div>
<div id="warning" style="position:absolute; visibility:hidden;">
    <img src="http://devgraphics.millsberry.com/site_gfx/adSpot_popup.gif" hspace="10" width="258" height="49" alt="" border="0"/>
</div>
MILLSBERRY &reg;, characters, logos, product names 
and all related indicia are trademarks of Mills Online, Inc., &copy; 
2004-2008.<BR> &reg; denotes Reg. US Pat. & TM Office. All rights 
reserved.<br>
Use of this site signifies your acceptance of the <a href='/town_hall/terms.phtml'><b>Terms and Conditions</b></a>.
Please view our <a href='/town_hall/terms.phtml'><b>Privacy Policy</b></a>.

</div>
</div>
<div id='bottom'>&nbsp;</div>
</div>
</body>
</html>
