
#body #layout_body-nonav {
	clear: both;
	width: 755px;
	margin: 0px auto;
	border-width: 0 2px 0 2px;
}

#body #layout_body-nonav #main-nonav {
	padding: 0px;
	margin: 0px;
	float: right;
	width: 755px;
}

div#registration-content-box-outer {
	background: transparent url(http://graphics.millsberry.com/site_gfx/registration/form-top-right.gif) no-repeat top right;
	background-color:#eeedcd;
	margin: 55px 15px 40px 15px;
	clear: both;
}

div#registration-content-box-inner {
	background: transparent url(http://graphics.millsberry.com/site_gfx/registration/form-bottom-left.gif) no-repeat bottom left;
	margin: 0px;
	padding: 15px 0px 0px 0px;
}

#customize-right-container{
	background-color:#7F98E5;
	padding-top:45px;
	padding-bottom:518px;
}

#customize-content-box-outer{
	background: transparent url(http://graphics.millsberry.com/site_gfx/registration/form-top-right.gif) no-repeat top right;
	background-color:#eeedcd;
	
	/*margin-bottom:55px;*/
	width:585px;
	margin:0px auto 55px auto;
	clear: both;
}
#customize-content-box-inner{
	background: transparent url(http://graphics.millsberry.com/site_gfx/registration/form-bottom-left.gif) no-repeat bottom left;
	margin: 0px;
	padding: 15px 0px 0px 0px;
}

div#buddyedit {
	text-align: center;
}

div.buddyupdate {
	text-align:center;
	margin-left: 290px;
}

div#reg_completed {
	width:750px;
	background: url(http://graphics.millsberry.com/site_gfx/registration/step-3-congratulation-bg.png);
	background-repeat: no-repeat;
}

.spacingcongratboxes{
	margin-right:10px;
}
/* Custom backgrounds for dialog boxes */
div#login_popup {
	background: url(http://graphics.millsberry.com/site_gfx/login/dlg-login.png);
	background-repeat: no-repeat;
}

div#buddy_confirm {
	width:300px;
	background: url(http://graphics.millsberry.com/site_gfx/registration/confirmation-bg.png);
	background-repeat: no-repeat;
}

div.help_6lines_inner {
	background: url(http://graphics.millsberry.com/site_gfx/registration/wt-6-lines.png);
	background-repeat: no-repeat;
}
div.help_4lines_inner {
	background: url(http://graphics.millsberry.com/site_gfx/registration/wt-4-lines.png);
	background-repeat: no-repeat;
}

div.help_3lines_inner {
	background: url(http://graphics.millsberry.com/site_gfx/registration/wt-3-lines.png);
	background-repeat: no-repeat;
}

div.help_privacypolicy_inner {
	background: url(http://graphics.millsberry.com/site_gfx/registration/wt-step1-privacy-policy.png);
	background-repeat: no-repeat;
}

div.help_terms_inner {
	background: url(http://graphics.millsberry.com/site_gfx/registration/wt-step1-terms-conditions.png);
	background-repeat: no-repeat;
}

/* Transparent div over the custom close button */
div.close_overlay {
	width: 48px;
	height: 48px;
	/*background-color: aqua;*/
	cursor: pointer;
	display: block;
}

input.input_field {
	border:solid 1px #182187;
}

div.input_container_inactive {
	background:url(http://graphics.millsberry.com/site_gfx/login/login-input-bg.gif);
	background-position: 0px 0px;
}

div.input_container_active {
	background:url(http://graphics.millsberry.com/site_gfx/login/login-input-bg.gif);
	background-position: 0px -32px;
}

div.input_container_error {
	background:url(http://graphics.millsberry.com/site_gfx/login/login-input-bg.gif);
	background-position: 0px -64px;
}

/* CUSTOMIZE BUDDY APPEARANCE */

div#header-customize-buddy {
	position: absolute;
	width: 579px;
	height: 102px;
	z-index: 10;
	top: 0px;
	left: 310px;
	background: transparent url('http://graphics.millsberry.com/site_gfx/registration/customize-buddy-title.png') no-repeat;
}
div#header-customize-buddy-customize {
	position: absolute;
	width: 385px;
	height: 102px;
	z-index: 10;
	top: 0px;
	left: 310px;
	background: transparent url('http://graphics.millsberry.com/site_gfx/registration/customize-buddy-title.png') no-repeat;
}


div#goto-home-button {
	background: url(http://graphics.millsberry.com/site_gfx/registration/wt-bg-goto-millsberry-home.jpg );
	background-repeat: no-repeat;
	margin-top: -45px;
	margin-left:10px;
	text-align:center;
}

div.buddyupdate-appearance {
	text-align:center;
	margin-left: 225px;
}

/*SIGNUP PAGE*/

div#header-signup-process{
	position: absolute;
	width: 579px;
	height: 102px;
	z-index: 10;
	top: -60px;
	left: 95px;
	background: transparent url('http://graphics.millsberry.com/site_gfx/registration/signup-title.png') no-repeat;
}

/*breadcrumb*/
div#breadcrumbs-signup-step1	{ width: 642px;height: 50px;margin: 0px auto;background: transparent url('http://graphics.millsberry.com/site_gfx/registration/breadcrumb-1.png') no-repeat;		}
div#breadcrumbs-signup-step2	{ width: 642px;height: 50px;margin: 0px auto;background: transparent url('http://graphics.millsberry.com/site_gfx/registration/breadcrumb-2.png') no-repeat;		}
div#breadcrumbs-signup-step3	{ width: 642px;height: 50px;margin: 0px auto;background: transparent url('http://graphics.millsberry.com/site_gfx/registration/breadcrumb-3.png') no-repeat;		}

	/*SIGNUP FORM*/
	div.signup .signup_form{ background:url(http://graphics.millsberry.com/site_gfx/registration/tour-step1.gif) no-repeat top left;margin-top:15px;width:680px;}
	div.signup .signup_form_error{background:url(http://graphics.millsberry.com/site_gfx/registration/tour-error-1.gif) no-repeat bottom left; width:720px;margin-left:-36px;}
	div.signup .signup_form table{ visibility:hidden; }
	div.signup .signup_form .introtext{ margin-left:120px;margin-top:10px;}
	div.signup .signup_form .entry{  margin-left:165px;margin-bottom:10px;float:left; width:511px; display:inline; }
	div.signup .signup_form .entry label{ width:120px;border:0px solid red;float:left;text-align:right;margin-right:10px;padding-top:10px;}
	div.signup .signup_form .entry label.radiolbl{ width:auto;cursor:pointer;}
	div.signup .signup_form .entry input{ width:195px;height:15px;font-size:12px;font-family: "Trebuchet MS","Tahoma";color:#5a6fae;float:left;border:1px solid #182187;}
	div.signup .signup_form .entry input.customradio{display:none;width:20px;height:15px;font:10px Tahoma;float:left;border:1px solid #182187;padding-top:5px; }
	div.signup .signup_form .entry select{font-size:11px;font-family: "Trebuchet MS","Tahoma";color:#5a6fae;}
	div.signup .signup_form .entry .customradio-wrapper{background:url(http://graphics.millsberry.com/site_gfx/registration/radiobuttons.gif) no-repeat;width:26px;height:26px;float:left;cursor:pointer;margin-top:5px;margin-right:5px;}
	div.signup .signup_form .entry .customradio-wrapper-deactivated{background-position:0px 0px;}
	div.signup .signup_form .entry .customradio-wrapper-activated{background-position:0px -26px; }
	

	/*whats this*/
	div.signup .signup_form .entry .whatsthis{float:left;margin-left:10px;padding-top:10px;margin-bottom:5px;display:inline;border:1px solid #EEEDCD;}
	div.signup .signup_form .entry .whatsthis .error_list{float:left;width:150px;margin-top:-10px;font:10px Verdana;}
	div.signup .signup_form .entry .whatsthis a{font:10px Verdana;}
	
	div.signup .signup_form .entry .whatsthissmall{}
	div.signup .signup_form .entry .whatsthissmall .error_list{float:left; width:300px;margin-top:5px;font:10px Verdana;}
	

	
	
	/*suggested usernames*/
	div.signup .signup_form .entry .center_both {text-align:left;vertical-align:middle;margin:0px;margin-left:125px;clear:both;}
	div.signup .signup_form .entry .center_both br{clear:both;}
	div.signup .signup_form .entry .center_both input{width:auto;border:1px solid red;clear:both;margin-top:3px;}



	/*submit*/
	div.signup div.submitcontainer{width:210px;margin-left:232px;margin-top:10px;text-align:center; }
	div.signup div.submitcontainer span{padding-left:5px;}
	div.signup div.submitcontainer span a{font:10px Verdana;}

	/*select*/
	div.signup div.select_container{}
	div.signup div.select_container select{margin-top:6px;margin-left:10px;border:1px solid #004ad5;}
	div.signup div.select_wrapper{background:url(http://graphics.millsberry.com/site_gfx/registration/signup-input-dob.gif) no-repeat;float:left;width:124px;height:35px; }
	div.signup div.select_wrapper-2{background:url(http://graphics.millsberry.com/site_gfx/registration/signup-input-dobsmall.gif) no-repeat;float:left;width:90px;height:35px;}
	div.signup div input{margin-top:6px;margin-left:5px;}

	div.signup div.input_container_inactive{float:left;width:217px;height:31px;background:url(http://graphics.millsberry.com/site_gfx/registration/signup-input.gif);background-position: 0px -32px;}
	div.signup div.input_container_active{float:left;width:217px;height:31px;background:url(http://graphics.millsberry.com/site_gfx/registration/signup-input.gif);background-position: 0px 0px;}

	/*suggested username*/
	div.signup div.suggested_username_container{background:url(http://graphics.millsberry.com/site_gfx/registration/bg-suggested-name.gif) no-repeat;height:23px;margin-left:6px;margin-bottom:2px; cursor:pointer; }
	div.signup div.suggested_username_container .radiolbl{line-height:15px !important;margin:0px;padding:2px 0px 0px 5px !important;font:13px Trebuchet MS;color:#1c2473;height:20px !important;  }
	

	/*CREATE BUDDY FORM*/
	div.create_buddy{}
	div.create_buddy .introtext{margin-left:200px;margin-top:10px;float:left;display:inline;background:url(http://graphics.millsberry.com/site_gfx/registration/intro-createbuddy.png);width:362px;height:54px;}
	div.create_buddy .buddy_form{background:url(http://graphics.millsberry.com/site_gfx/registration/tour-step2.gif) no-repeat 20px 50px;margin-top:15px;width:720px;border:0px solid black;}
	
	div.create_buddy_error {background:url(http://graphics.millsberry.com/site_gfx/registration/tour-error-1.gif) no-repeat bottom left;}
	div.create_buddy_error .buddy_form{background:none;}
	
	div.create_buddy .buddy_form .form-inputtitle{float:left;margin-left:225px;margin-top:20px;display:inline;border:0px solid red;}
	div.create_buddy .buddy_form .form-inputtitle div{float:left;margin-left:10px;display:inline;border:0px solid red;height:20px;}
	div.create_buddy .buddy_form .form-inputtitle div.error{width:250px;font:10px Verdana;text-align:left;margin-bottom:5px;}

	div.create_buddy .buddy_form .form-inputtitle div a{font:10px Verdana;color:#004ad5;float:left;margin-top:2px;}

	div.create_buddy .buddy_form .gender-selector {width:400px;margin-left:180px;height:230px;}
	div.create_buddy .buddy_form .gender-selector .option{width:170px;height:230px;float:left;display:inline;margin-right:30px;cursor:pointer;}
	div.create_buddy .buddy_form .gender-selector .option-m-deactivated{background:url(http://graphics.millsberry.com/site_gfx/registration/wt-step2-gender_man_d.gif) no-repeat top left;}
	div.create_buddy .buddy_form .gender-selector .option-m-activated{background:url(http://graphics.millsberry.com/site_gfx/registration/wt-step2-gender_man_a.gif) no-repeat top left;}
	div.create_buddy .buddy_form .gender-selector .option-f-deactivated{background:url(http://graphics.millsberry.com/site_gfx/registration/wt-step2-gender_women_d.gif) no-repeat top left;}
	div.create_buddy .buddy_form .gender-selector .option-f-activated{background:url(http://graphics.millsberry.com/site_gfx/registration/wt-step2-gender_women_a.gif) no-repeat top left;}
	div.create_buddy .buddy_form .gender-selector .forminputs{display:none;}
	div.create_buddy .buddy_form .input_container input{ width:180px;height:15px;font-size:12px;font-family: "Trebuchet MS","Tahoma";color:#5a6fae;float:left;border:1px solid #182187;margin-left:10px;margin-top:6px;}
	div.create_buddy .buddy_form div.input_container_inactive{float:left;width:217px; height:31px; background:url(http://graphics.millsberry.com/site_gfx/registration/signup-input.gif);background-position: 0px -32px;}
	div.create_buddy .buddy_form div.input_container_active{float:left;width:217px;height:31px;background:url(http://graphics.millsberry.com/site_gfx/registration/signup-input.gif);background-position: 0px 0px;}

	div.create_buddy .buddy_form div.buddynameerror{float:left;width:250px;display:inline;}

	div.create_buddy .buddy_form input.submit{ float:right;display:inline;margin-top:50px;margin-right:20px;}



	/*CUSTOMIZE BUDDY FORM*/

	#customize-tabset{margin-top:50px;margin-left:0px;}
	.customize-tabset-1{background:url(http://graphics.millsberry.com/site_gfx/registration/tabset-customize-1.gif) no-repeat top left;}
	.customize-tabset-2{background:url(http://graphics.millsberry.com/site_gfx/registration/tabset-customize-2.gif) no-repeat top left;}
	#customize-tabset .tabs-head{}
	#customize-tabset .tabs-head div.option{}
	#customize-tabset .tabs-head div.option img{cursor:pointer; }
	#customize-tabset .tabs-head div.option a img{border:0px;}
	#customize-tabset .tabs-head div.option-1{width:290px;height:50px;float:left; overflow:hidden;}
	#customize-tabset .tabs-head div.option-2{width:270px;height:50px;float:left; overflow:hidden; }

	#customize-tabset .tabs-body div.option{}
	#customize-tabset .tabs-body div.option-1{}
	#customize-tabset .tabs-body div.option-2{}
	#customize-tabset .tabs-body div.option-active{display:block;}
	#customize-tabset .tabs-body div.option-inactive{display:none;}

	.traits-selection{}
	.traits-selection .introtext{text-align:center;padding-top:15px;}
	.traits-selection .traitset{ width:560px;margin:20px auto;}
	.traits-selection .traitset .trait{float:left;width:175px;height:32px;background:url(http://graphics.millsberry.com/site_gfx/registration/traits-select-bg.gif) no-repeat;margin-right:5px;margin-top:0px;display:inline;}
	.traits-selection .traitset .trait select{font-size:11px;font-family: "Trebuchet MS","Tahoma";color:#5a6fae;width:160px;height:18px;margin-left:6px;margin-top:6px;}
	.traits-selection .traitbuttonset {float:right;margin-right:40px;display:inline;}
	
br.cleaner{clear:both;}
