<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- chinpweb04.millsberry.com -->
<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
<meta http-equiv='imagetoolbar' content='no'>
<meta name='keywords' content="Mills,Millsbury,Milsberry,Milsbury,Millberry,Millbury,Fun games,Spanish language games,Educational games,Active games,Citizen,Cool stuff,Arcade,Music Mix,Fun,Games,Explore,Adventure,Create,Character,Buddy,Care,Academy,School,Gym,Gymnasium,Solver,Science,Project,Town,Pets,Children's games,Games for kid,Kid games,Kids games,Kid's games,Children,Safe gaming">
<title>Millsberry - Colhurst House</title>
<link rel='stylesheet' type='text/css' href='/css/theme/royal.css'>
<link rel='stylesheet' type='text/css' href='/css/template.css'>
<!--[if IE]>
<link rel='stylesheet' type='text/css' href='/css/ie.css'>
<![endif]-->
<script type='text/javascript' src='/hidden.js'></script>
<script type='text/javascript'>
<!--
// Allows users to assign names to their shortcuts
function addShortcut (to_url, default_title) {
	assign_title = default_title;
	var user_title = prompt ("What name do you want to give this shortcut?\nLeave this blank to use the page's existing title.","");
	if (user_title.length > 0) {
		assign_title = base64_encode (utf8_encode (user_title));
	}
	window.location='/process_shortcut.phtml?action=add&url=' + to_url + '&name=' + assign_title;
}
-->
</script>
<link rel='shortcut icon' href='/favicon.ico'>
</head>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<body >

<div id='top'>
<a href='/index.phtml'><span id='logo'>&nbsp;</span></a>
<div id='layout_head'>
	<div id='login_info'><form name='login' method='post' action='/colhurst/index.phtml?action=rules'>
Username <input type='text' name='login_username' size='10'>&nbsp;&nbsp;
Password <input type='password' name='login_pass' size='10'>
<input type='submit' value='Go'>
</form></div>
	<div id='stripe'>
		<div id='stripe_shortcuts'>
			<table width='95' border='0' cellpadding='0' cellspacing='0'><tr>
				<td width='72'></td>
				<td width='23' valign='bottom'></td>
			</tr></table>
		</div>
		<div id='stripe_search'>
			<form name='search' action='/site_search.phtml' method='get'>
			<table width='340' border='0' cellpadding='0' cellspacing='0'><tr>
				<td width='135' align='right'>Address Book&nbsp;</td>
				<td width='105' align='left' valign='middle'><input type='text' name='search' size='15'></td>
				<td width='30' align='center' valign='bottom'><a href='javascript: document.search.submit();' class='stripe_button'><div id='search_button'></div></a></td>
				<td width='60' align='right'><a href='/town_hall/faq.phtml'>Help</a></td>
			</tr></table>
			</form>
		</div>
	</div>
</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='body'>
<div id='layout_body'>
<div id='side_nav'>

<!-- Exclude these from the stylesheet so they can be translated -->
<style type='text/css'>
#body #layout_body #side_nav .nav_button_hover #nav_signup {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_signup_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_start {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_start_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_the_city {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_the_city_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_downtown {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_downtown_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_arcade {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_arcade_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_my_stuff {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_my_stuff_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_my_home {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_my_home_1.png') no-repeat;
}
#body #layout_body #side_nav .nav_button_hover #nav_customize {
	background: transparent url('http://graphics.millsberry.com/site_gfx/nav/nav_customize_1.png') no-repeat;
}
</style>
<!--[if lt IE 7.00]>
<style type='text/css'>
#body #layout_body #side_nav .nav_button_hover #nav_signup {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_signup_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_start {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_start_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_the_city {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_the_city_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_downtown {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_downtown_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_arcade {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_arcade_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_my_stuff {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_my_stuff_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_my_home {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_my_home_1.png');
}
#body #layout_body #side_nav .nav_button_hover #nav_customize {
	background-image: none;
	filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://graphics.millsberry.com/site_gfx/nav/nav_customize_1.png');
}
</style>
<![endif]-->

<a href='/signup.phtml' class='nav_button_hover'><span id='nav_signup' class='nav_button'>&nbsp;</span></a>
<a href='/main_map.phtml' class='nav_button_hover'><span id='nav_the_city' class='nav_button'>&nbsp;</span></a>
<a href='/main_map.phtml?location=downtown' class='nav_button_hover'><span id='nav_downtown' class='nav_button'>&nbsp;</span></a>
<a href='/complex/arcade.phtml' class='nav_button_hover'><span id='nav_arcade' class='nav_button'>&nbsp;</span></a>
<br><img src='http://graphics.millsberry.com/site_gfx/prebuddy.gif' border='1'>
<table width='100%' border='0' cellpadding='5' cellspacing='0' id='side_nav_options'>
<tr>
	<td align='right'>Language</td>
	<td>
		<form name='language_form' method='post' action='/colhurst/index.phtml?action=rules'>
		<select name='lang' onChange='document.language_form.submit();' style='width: 75px;'>
			<option value='en' selected>English</option>
			<option value='es' >Espa&ntilde;ol</option>
		</select>
		</form>
	</td>
</tr>

</table>

</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='main'>

<div id='interior'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/site_gfx/interiors/int_colhurst_house_v1.swf', 600, 400, 'unixTimeStamp=1144725094', 6);</script></div>
<div id='interior_stripe'>Treasure Hunting tips & rules</div>
<div id='content'>
<b>THE RULES:</b>
	<ol>
	<li>Entry requires a dig ticket. These can be purchased at the counter. If you leave the tunnels, you must use another ticket to enter again. Remember, don't leave your ticket at home!
	<li>Entry requires some kind of shovel. Shovels can be purchased at <a href='/shop.phtml?shop_id=8'><b>Peterson's Hardware Emporium</b></a>. If you have many tools for digging, we'll assume you'll want to use the most appropriate one. Remember, don't leave your shovel at home!
	<li>All participants must be in good health to enter the tunnels. A healthy body is more important than any treasure, so <a href='/shop.phtml?shop_id=4'><b>take care of yourself first</b></a>! The healthier you are, the more you can dig.
	<li>Digging for treasure is hard work. Once you become too fatigued, you are required to leave the tunnels. <a href='/shop.phtml?shop_id=4'><b>A balanced diet</b></a> and sound sleep are key to regaining your energy.
	<li>During your daily visit, you may dig in as many places as you wish, except in sites marked with a "Dig Site Reserved" sign.
	<li>During your daily visit, you may continue to dig for treasure even after you find something, so long as you are not too fatigued to continue.
	</ol>
	<b>SOME TIPS:</b>
	<ul>
	<li>According to Cecil Colhurst's diary, more valuable artifacts are buried deeper. 
	<li>Make sure you have the right tool for the right job. It will make digging easier.
	<li>When it comes to treasure hunting, a sharp mind is as important as a healthy body.
	<li>Digging one deep hole requires more energy than digging many shallow holes.
	<li>If you conserve your energy when digging, you can recover more quickly and dig more often. If you dig until you're exhausted, it will take much longer to fully recover, and you'll dig less often.	 
	<li>Treasure hunting requires patience and perseverance. Even Cecil Colhurst spent years looking for treasure, so don't expect to build your collection overnight!
	</ul>
</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='footer'>
MILLSBERRY, characters, logos, product names and all related indicia are trademarks of Mills Online, Inc., &copy; 2004-2006.<BR> &reg; denotes Reg. US Pat. & TM Office. All rights reserved.<br>Use of this site signifies your acceptance of the <a href='/town_hall/terms.phtml'><b>Terms and Conditions</b></a>.<br>Please view our <a href='/town_hall/terms.phtml'><b>Privacy Policy</b></a>
</div>
</div>
<div id='bottom'>&nbsp;</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='debug'>
</div>
</body>
</html>
