<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- 10.100.56.26 -->
<html>
<head>
<meta http-equiv='imagetoolbar' content='no'>
<meta name='keywords' content="Mills,Millsbury,Milsberry,Milsbury,Millberry,Millbury,Fun games,Spanish language games,Educational games,Active games,Citizen,Cool stuff,Arcade,Music Mix,Fun,Games,Explore,Adventure,Create,Character,Buddy,Care,Academy,School,Gym,Gymnasium,Solver,Science,Project,Town,Pets,Children's games,Games for kid,Kid games,Kids games,Kid's games,Children,Safe gaming">
<title>Millsberry - Student Gallery</title>
<script type='text/javascript' src='/common.js?v=2'></script>
<link rel='shortcut icon' type='image/x-icon' href='/favicon.ico'>
<!-- Appending v=# to these files causes them to recache in the user's browser when # changes -->
<link rel='stylesheet' type='text/css' href='/css/theme/royal.css?v=2'>
<link rel='stylesheet' type='text/css' href='/css/template.css?v=5'>
<link rel='stylesheet' type='text/css' href='/css/global.css?v=2'>
<!--[if lt IE 7.00]>
<link rel='stylesheet' type='text/css' href='/css/template.ie.css?v=1'>
<link rel='stylesheet' type='text/css' href='/css/global.ie.css?v=1'>
<![endif]-->
<link rel='stylesheet' type='text/css' href='/css/museum/paint/vote.css?v=1'>
</head>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<body>

<!--<div id='leaderboard'><h2>Leader Board</h2></div>-->
<div id='top'>
<a href='/'><span id='logo'>&nbsp;</span></a>
<div id='layout_head'>
	<div id='login_info'><form name='login' method='post' action='/museum/paint/vote.phtml?p=6'>
Username <input type='text' name='login_username' size='10'>&nbsp;&nbsp;
Password <input type='password' name='login_pass' size='10'>
<input type='submit' value='Go'>
</form></div>
	<div id='stripe'>
		<div id='stripe_shortcuts'>
			<table width='95' border='0' cellpadding='0' cellspacing='0'><tr>
				<td width='72'></td>
				<td width='23' valign='bottom'></td>
			</tr></table>
		</div>
		<div id='stripe_search'>
			<form name='search' action='/site_search.phtml' method='get'>
			<table width='340' border='0' cellpadding='0' cellspacing='0'><tr>
				<td width='135' align='right'>Address Book&nbsp;</td>
				<td width='105' align='left' valign='middle'><input type='text' name='search' size='15'></td>
				<td width='30' align='center' valign='bottom'><a href='javascript: document.search.submit();' class='stripe_button'><span id='search_button'>&nbsp;</span></a></td>
				<td width='60' align='right'><a href='/town_hall/faq.phtml'>Help</a></td>
			</tr></table>
			</form>
		</div>
	</div>
</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='body'>
<div id='layout_body'>
<div id='side_nav'>
<a href='/main_map.phtml' class='nav_button_hover'><span id='nav_the_city' class='nav_button'>&nbsp;</span></a>
<a href='/main_map.phtml?location=downtown' class='nav_button_hover'><span id='nav_downtown' class='nav_button'>&nbsp;</span></a>
<a href='/tour.phtml' class='nav_button_hover'><span id='nav_tour' class='nav_button'>&nbsp;</span></a>
<a href='/signup.phtml' class='nav_button_hover'><span id='nav_signup' class='nav_button'>&nbsp;</span></a>
<a href='/complex/arcade.phtml' class='nav_button_hover'><span id='nav_arcade' class='nav_button'>&nbsp;</span></a>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='main'>
<div id='interior'><script type='text/javascript'>flash_object ('http://graphics.millsberry.com/site_gfx/interiors/int_gallery_v2.swf', '600', '400', '&unixTimeStamp=1170967345&serverTimeOffset=28800', '7', 'noscale');</script></div>
<div id='interior_stripe'>Student Gallery</div>
<div id='content'>
Choose which painting you wish to vote for. You can only vote for one painting per day, so make your vote count! Read the <a href='vote.phtml?view=rules'>rules</a> to learn more.<div id='select_winners'><form method='get' action='winners.phtml'><b>Select a neighborhood to view past winners:</b>
<select name='neighborhood'>
<option value='Golden Valley'>Golden Valley</option>
<option value='Lakeview'>Lakeview</option>
<option value='Metro Park'>Metro Park</option>
<option value='Ravenwood'>Ravenwood</option>
<option value='Westridge'>Westridge</option>
</select>
<input type='submit' value='Go'></form>
</div>
<table align='center' border='0' cellpadding='0' cellspacing='0'><tr>
<td width='21' align='right' height='20'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='21' height='20'></td>
<td width='16' align='right' height='20'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='16' height='20'></td>
<td align='center' height='20' valign='top'><a href='vote.phtml?p=1' class='page_link'>1</a><span class='page_spacer'>|</span><a href='vote.phtml?p=2' class='page_link'>2</a><span class='page_spacer'>|</span><a href='vote.phtml?p=3' class='page_link'>3</a><span class='page_spacer'>|</span><a href='vote.phtml?p=4' class='page_link'>4</a><span class='page_spacer'>|</span><a href='vote.phtml?p=5' class='page_link'>5</a><span class='page_spacer'>|</span><span class='page_selected'>6</span></td>
<td width='16' height='20' align='left'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='16' height='20'></td>
<td width='21' height='20' align='left'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='21' height='20'></td>
</tr></table>
<hr noshade size='1'>
<form method='post'>
<table width='100%' align='center' border='0' cellpadding='0' cellspacing='30'>
<tr>
<td width='50%' align='center'><b><i>Sylvane Lake</i></b><br>
<script type='text/javascript'>flash_object ('http://graphics.millsberry.com/museum/paint_v4.swf', '200', '133', 'scriptURL_str=http%3A%2F%2Fwww.millsberry.com%2Fmuseum%2Fpaint%2Fload_paint_xml.phtml&mode_str=SHOW&show_id=98f30ad2c1fb56d31ad0c1f8eb661eba&unixTimeStamp=1170967345&serverTimeOffset=28800', '', 'noborder');</script><br>
<table class='art_caption' width='100%' border='0' cellpadding='0' cellspacing='0'>
<tr><td colspan='2' align='center'><input disabled type='radio' name='paint_vote' value='98f30ad2c1fb56d31ad0c1f8eb661eba'>
<a href="javascript: openWin ('zoom.phtml?id=98f30ad2c1fb56d31ad0c1f8eb661eba', 600, 400, false, 'Enlarge');"><img src='http://graphics.millsberry.com/site_gfx/site_images/zoom.gif' alt='Enlarge' title='Enlarge' style='margin: 2px 0 0 0; border: 0;'></a></td></tr>
<tr><td width='50%' align='right'>Artist:&nbsp;</td><td width='50%' align='left'><a href='/home/?user=jmonteleone'>jmonteleone</a></td></tr>
<tr><td align='right'>Neighborhood:&nbsp;</td><td align='left'><a href='/main_map.phtml?location=Metro+Park'>Metro Park</a></td></tr>
</table>
</td>
<td width='50%' align='center'><b><i>Sylvane Lake</i></b><br>
<script type='text/javascript'>flash_object ('http://graphics.millsberry.com/museum/paint_v4.swf', '200', '133', 'scriptURL_str=http%3A%2F%2Fwww.millsberry.com%2Fmuseum%2Fpaint%2Fload_paint_xml.phtml&mode_str=SHOW&show_id=b0e7616c6c8ced420425651aedab1cad&unixTimeStamp=1170967345&serverTimeOffset=28800', '', 'noborder');</script><br>
<table class='art_caption' width='100%' border='0' cellpadding='0' cellspacing='0'>
<tr><td colspan='2' align='center'><input disabled type='radio' name='paint_vote' value='b0e7616c6c8ced420425651aedab1cad'>
<a href="javascript: openWin ('zoom.phtml?id=b0e7616c6c8ced420425651aedab1cad', 600, 400, false, 'Enlarge');"><img src='http://graphics.millsberry.com/site_gfx/site_images/zoom.gif' alt='Enlarge' title='Enlarge' style='margin: 2px 0 0 0; border: 0;'></a></td></tr>
<tr><td width='50%' align='right'>Artist:&nbsp;</td><td width='50%' align='left'><a href='/home/?user=mackens80'>mackens80</a></td></tr>
<tr><td align='right'>Neighborhood:&nbsp;</td><td align='left'><a href='/main_map.phtml?location=Golden+Valley'>Golden Valley</a></td></tr>
</table>
</td>
</tr>
<tr>
<td width='50%' align='center'><b><i>Fruit Bowl</i></b><br>
<script type='text/javascript'>flash_object ('http://graphics.millsberry.com/museum/paint_v4.swf', '200', '133', 'scriptURL_str=http%3A%2F%2Fwww.millsberry.com%2Fmuseum%2Fpaint%2Fload_paint_xml.phtml&mode_str=SHOW&show_id=043b5eae11d7d9bf13244e3795be1324&unixTimeStamp=1170967345&serverTimeOffset=28800', '', 'noborder');</script><br>
<table class='art_caption' width='100%' border='0' cellpadding='0' cellspacing='0'>
<tr><td colspan='2' align='center'><input disabled type='radio' name='paint_vote' value='043b5eae11d7d9bf13244e3795be1324'>
<a href="javascript: openWin ('zoom.phtml?id=043b5eae11d7d9bf13244e3795be1324', 600, 400, false, 'Enlarge');"><img src='http://graphics.millsberry.com/site_gfx/site_images/zoom.gif' alt='Enlarge' title='Enlarge' style='margin: 2px 0 0 0; border: 0;'></a></td></tr>
<tr><td width='50%' align='right'>Artist:&nbsp;</td><td width='50%' align='left'><a href='/home/?user=kate_r_lehmkuhl'>kate_r_lehmkuhl</a></td></tr>
<tr><td align='right'>Neighborhood:&nbsp;</td><td align='left'><a href='/main_map.phtml?location=Ravenwood'>Ravenwood</a></td></tr>
</table>
</td>
<td width='50%' align='center'><b><i>Hidaka Sensei</i></b><br>
<script type='text/javascript'>flash_object ('http://graphics.millsberry.com/museum/paint_v4.swf', '200', '133', 'scriptURL_str=http%3A%2F%2Fwww.millsberry.com%2Fmuseum%2Fpaint%2Fload_paint_xml.phtml&mode_str=SHOW&show_id=4c00c4123540772dfa105cdfecf6dad5&unixTimeStamp=1170967345&serverTimeOffset=28800', '', 'noborder');</script><br>
<table class='art_caption' width='100%' border='0' cellpadding='0' cellspacing='0'>
<tr><td colspan='2' align='center'><input disabled type='radio' name='paint_vote' value='4c00c4123540772dfa105cdfecf6dad5'>
<a href="javascript: openWin ('zoom.phtml?id=4c00c4123540772dfa105cdfecf6dad5', 600, 400, false, 'Enlarge');"><img src='http://graphics.millsberry.com/site_gfx/site_images/zoom.gif' alt='Enlarge' title='Enlarge' style='margin: 2px 0 0 0; border: 0;'></a></td></tr>
<tr><td width='50%' align='right'>Artist:&nbsp;</td><td width='50%' align='left'><a href='/home/?user=thundercloud23'>thundercloud23</a></td></tr>
<tr><td align='right'>Neighborhood:&nbsp;</td><td align='left'><a href='/main_map.phtml?location=Westridge'>Westridge</a></td></tr>
</table>
</td>
</tr>
<tr>
<td width='50%' align='center'><b><i>Sylvane Lake</i></b><br>
<script type='text/javascript'>flash_object ('http://graphics.millsberry.com/museum/paint_v4.swf', '200', '133', 'scriptURL_str=http%3A%2F%2Fwww.millsberry.com%2Fmuseum%2Fpaint%2Fload_paint_xml.phtml&mode_str=SHOW&show_id=10117307612cceaff06f1c16ee09d6db&unixTimeStamp=1170967345&serverTimeOffset=28800', '', 'noborder');</script><br>
<table class='art_caption' width='100%' border='0' cellpadding='0' cellspacing='0'>
<tr><td colspan='2' align='center'><input disabled type='radio' name='paint_vote' value='10117307612cceaff06f1c16ee09d6db'>
<a href="javascript: openWin ('zoom.phtml?id=10117307612cceaff06f1c16ee09d6db', 600, 400, false, 'Enlarge');"><img src='http://graphics.millsberry.com/site_gfx/site_images/zoom.gif' alt='Enlarge' title='Enlarge' style='margin: 2px 0 0 0; border: 0;'></a></td></tr>
<tr><td width='50%' align='right'>Artist:&nbsp;</td><td width='50%' align='left'><a href='/home/?user=beautylisa'>beautylisa</a></td></tr>
<tr><td align='right'>Neighborhood:&nbsp;</td><td align='left'><a href='/main_map.phtml?location=Lakeview'>Lakeview</a></td></tr>
</table>
</td>
</table>
</form>
<hr noshade size='1'>
<table align='center' border='0' cellpadding='0' cellspacing='0'><tr>
<td width='21' align='right' height='20'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='21' height='20'></td>
<td width='16' align='right' height='20'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='16' height='20'></td>
<td align='center' height='20' valign='top'><a href='vote.phtml?p=1' class='page_link'>1</a><span class='page_spacer'>|</span><a href='vote.phtml?p=2' class='page_link'>2</a><span class='page_spacer'>|</span><a href='vote.phtml?p=3' class='page_link'>3</a><span class='page_spacer'>|</span><a href='vote.phtml?p=4' class='page_link'>4</a><span class='page_spacer'>|</span><a href='vote.phtml?p=5' class='page_link'>5</a><span class='page_spacer'>|</span><span class='page_selected'>6</span></td>
<td width='16' height='20' align='left'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='16' height='20'></td>
<td width='21' height='20' align='left'><img src='http://graphics.millsberry.com/site_gfx/pixel.gif' width='21' height='20'></td>
</tr></table>
<br><div id='content_gutter'><a href='../'>Back to the Museum</a></div>
</div>
</div>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div id='footer'>
MILLSBERRY &reg;, characters, logos, product names and all related indicia are trademarks of Mills Online, Inc., &copy; 2004-2006.<BR> &reg; denotes Reg. US Pat. & TM Office. All rights reserved.<br>
Use of this site signifies your acceptance of the <a href='/town_hall/terms.phtml'><b>Terms and Conditions</b></a>.
Please view our <a href='/town_hall/terms.phtml'><b>Privacy Policy</b></a>.
</div>
</div>
<div id='bottom'>&nbsp;</div>
</div>
</body>
</html>
